### ISSUE TITLE
I just love this tool!

### ISSUE THREAD

**Issue by wetneb** [nrenner/brouter-web#108]
Hi - there does not seem to be any designated way to communicate enthusiasm about this tool. I don't have any particular issue to report, I just want to say that it's a fantastic service that I have used for thousands of kilometers and it just works great. I mostly use it in the UK with the fastbike profile and it's marvelous. Keep up the awesome work!
(feel free to close this issue of course, as it is not actually an issue!)

**Comment by nrenner** [comment]
Thanks, nice to hear!
