### ISSUE TITLE
Replace Bower with Yarn/npm

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#116]
Bower is deprecated:
> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate! 

https://bower.io/

And projects are dropping bower support:
- [Bootstrap](https://getbootstrap.com/docs/4.0/migration/#beta-2-changes)
  > Dropped Bower support as the package manager has been deprecated for alternatives (e.g., Yarn or npm). See bower/bower#2298 for details.
- [leaflet.pm](https://github.com/codeofsumit/leaflet.pm#install-via-bower-deprecated---leafletpm-is-no-longer-supporting-bower-since-0170)
  > Install via Bower (DEPRECATED - leaflet.pm is no longer supporting bower since 0.17.0)

Migration:
- [How to migrate away from Bower? · Bower blog](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)
  > Indeed, until recently Yarn neither could install Bower packages (i.e. GitHub repositories without package.json) nor resolve semver ranges on git tags. I focused on this for a while and the result is pleasing: Yarn 1.x is able to install most of Bower packages.
- what about npm?
- check which dependencies are without package.json

**Comment by bagage** [comment]
Hey @nrenner is there anynews about that?

I've read [https://medium.com/appifycanada/migrate-to-webpack-from-grunt-bower-legacy-build-system-344526f47873](this article) recently, and bower is giving me headache with #132.

Do you plan to work on that? Should I try it? I've no experience with all that but I'll be glad to drop bower/gulp!

**Comment by nrenner** [comment]
No news. Still working on rounding off the mobile support release to finally get it out for brouter.de, only a couple of details left, and won't do anything else – and also would not want to merge such a change – until then.

Also not my top priority, and not sure yet if it will be part of [milestone 0.8.0](https://github.com/nrenner/brouter-web/milestone/5). 

My idea was to do this in steps and replace Gulp later, but not sure if that makes sense.

Feel free to have a go at this.

What are your issues with bower?
