### ISSUE TITLE
Custom routing profile too big

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#118]
Hey @nrenner, I merged latest changes into brouter.damsy.net, cool changes :)!

One small bug though, with the new right sidebar: when the profile custom option is shown, the sidebar grows to 4000px (400% height ~), which make the bottom toolbar hidden. I guess some CSS needs to be tweaked?

![image](https://user-images.githubusercontent.com/1451988/38691849-58ca7df0-3e82-11e8-818a-bb2ead18f57c.png)

**Comment by nrenner** [comment]
Oh my, flexbox is killing me. I'm sure this was working in Firefox at some point. Thanks for the report.
