### ISSUE TITLE
Upload error on profiles with Safari 8.0

### ISSUE THREAD

**Issue by mgmart** [nrenner/brouter-web#12]
I tried to upload the sample profiles and I get an "Upload error:" without any further explanation.
Browser is Safari Version 8.0 (10600.1.25.1)
brouter-web is alpha3

**Comment by nrenner** [comment]
Is this still an issue? I don't know how to test on Ubuntu, and Safari for Windows is abandoned and quite old.

**Comment by mgmart** [comment]
```[Warning] Unexpected CSS token: : (leaflet.css, line 459
[Warning] Unexpected CSS token: : (bootstrap-theme.min.css, line 5, x38)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5, x3)
[Warning] Invalid CSS property declaration at: * (jquery.dataTables.css, line 39)
[Warning] Invalid CSS property declaration at: * (jquery.dataTables.css, line 302)
[Warning] Invalid CSS property declaration at: * (jquery.dataTables.css, line 334)
[Warning] Invalid CSS property declaration at: * (jquery.dataTables.css, line 432)
[Error] Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers. (profile, line 0)
[Error] XMLHttpRequest cannot load http://h2096617.stratoserver.net:443/brouter/profile. Request header field Content-Type is not allowed by Access-Control-Allow-Headers. (brouter-web, line 0)```

**Comment by nrenner** [comment]
Thanks. It just came to mind, that I can simulate this with Chromium by adding an extra request header, that should help with implementing and testing.

**Comment by mgmart** [comment]
Don't know if it's the new Safari (Version 8.0.5 (10600.5.17)) or some changes you made. But I gave it another try just now and it worked like a charm.

Thanks and keep up the good work!

**Comment by nrenner** [comment]
Good to hear, was going to ask. The linked PR was supposed to fix this and has already been deployed some time ago.

Thanks for reporting and testing!
