### ISSUE TITLE
Error: from-position not mapped in existing datafile

### ISSUE THREAD

**Issue by panteo** [nrenner/brouter-web#125]
Problems with http://brouter.de/brouter-web/ 
It keeps showing "Error: from-position not mapped in existing datafile"

Chrome on Ubuntu 18.04.

**Comment by zackenundpunkte** [comment]
I have the same problem in the "rails only" mode. "Trekking" and others work fine.
Current Firefox and Chrome versions on MacOS 10.12.6

**Comment by nrenner** [comment]
Thanks for reporting. Closing as duplicate of #126.

**Comment by Twisterrrrr** [comment]
same problem in "River mode"
Chrome and Opera on Windows 10 x64

**Comment by nrenner** [comment]
Works for me, so no general problem.

Can you please create a new issue for the backend brouter repo:
https://github.com/abrensch/brouter/issues/new
and post your URL from the browser address bar.
