### ISSUE TITLE
brouter-web error - datafile not found

### ISSUE THREAD

**Issue by zoladkow** [nrenner/brouter-web#126]
Since this sunday, around noon, following error keeps showing when setting new waypoints:

![obraz](https://user-images.githubusercontent.com/11553616/43691056-2ff4399a-9916-11e8-9f8c-1f70ca55921d.png)

possible reason is an error with copying of new datafiles, this is how the folder content looks now:

![obraz](https://user-images.githubusercontent.com/11553616/43691052-1b7da7e4-9916-11e8-963a-97afd838d442.png)

**Comment by VolkerH** [comment]
Just encountered the same issue trying to create a route in Geelong, VIC, Australia.
Error Message: 
![image](https://user-images.githubusercontent.com/2210044/43691343-5cb64700-995e-11e8-9c54-6c98c1d344fa.png)

**Comment by zoladkow** [comment]
Don't think so. When it started I was in the middle of planing a route through France and the error appeared also for waypoints already set. 

I was using Firefox.



On August 6, 2018 9:23:48 AM GMT+02:00, Norbert Renner <notifications@github.com> wrote:
>Yes, seems like data files directory is empty. Some regions might still
>work when in cache? Thanks for reporting.
>
>@abrensch
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nrenner/brouter-web/issues/126#issuecomment-410612872

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nrenner** [comment]
Germany is still working. So I'm just guessing, don't really know about caching.

**Comment by abrensch** [comment]
Sorry there were server-problems on the server processing the data-file update

An somehow the script did not terminate but copied the empty result to the download server.

Germany continued to work because there's a "secondary-data" link to a daily processing of germany.

I copied the old files back, so it does wok again, but of course there is not yet the weekly update.

regards, Arndt

**Comment by zoladkow** [comment]
Hi,

I confirm it's fine now. closing the issue.
Great work overall 

brouter (and brouter-web) is fantastic! ;)
