### ISSUE TITLE
Use distinct from, to and via markers

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#129]
It seems there is no way today to know in which the route is going:

![image](https://user-images.githubusercontent.com/1451988/44277359-c0291e80-a24a-11e8-8d9f-e0c75e2f53ad.png)

It would be nice to have different icon and/or color for start marker and end marker, for instance on osm.org:

![image](https://user-images.githubusercontent.com/1451988/44277745-e4d1c600-a24b-11e8-91c2-3434ce0157c3.png)

**Comment by nrenner** [comment]
I agree, it's just not implemented yet (Turistforeningen/leaflet-routing#8).

An idea was to first evaluate whether it would make sense to switch to [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine/), which is lacking other features.

**Comment by bagage** [comment]
Thanks for the quick insight @nrenner. The main advantage of leaflet-routing-machine I see is that it is still under development, but I do not know much more about each project and the features its lacking.

If it requires huge work to be replaced, maybe I'll give leaflet routing icons configuration a try.

**Comment by nrenner** [comment]
I updated the `dev` branch of my leaflet-routing fork that we reference with your PR. You should be able to update to that with `yarn upgrade leaflet-routing`.
