### ISSUE TITLE
Search on lat/lon does return correct location

### ISSUE THREAD

**Issue by MaartenDeen** [nrenner/brouter-web#134]
When I search on a lat/lon location (`51.341, 6.0`) in the search box, brouter returns a different location then OSM with nominatim.
With OSM/Nominatim:
https://www.openstreetmap.org/search?query=51.341%2C%206.0#map=16/51.3410/6.0000
![nominatim](https://user-images.githubusercontent.com/1825970/46733454-a9bea280-cc90-11e8-8e2e-722d9e654ab7.png)
Using brouter search:
![brouter](https://user-images.githubusercontent.com/1825970/46733565-f609e280-cc90-11e8-941b-810f72aa7b14.PNG)

The difference is not constant, here it is 200m north-south, with 51.68065844172967, 11.143805969953538 it is 400 meters NE-SW.

**Comment by nrenner** [comment]
The main difference seems to be that osm.org parses and recognizes the coordinates and calls Nominatim reverse search, while BRouter-Web simply passes the coordinates as search string to the regular Nominatim forward search. Nominatim reverse seems to snap coordinates to the nearest point on the way, while forward returns the center of the nearest way:

https://nominatim.openstreetmap.org/reverse.php?format=html&lat=51.341&lon=6.0&zoom=18
https://nominatim.openstreetmap.org/search.php?q=51.341%2C+6.0&polygon_geojson=1&viewbox=

So the current BRouter-Web result isn't really wrong and good enough in my opinion. The [Leaflet Control Geocoder](https://github.com/perliedman/leaflet-control-geocoder) plugin used here doesn't seem to provide parsing coordinates and switching to reverse, and I don't see a reason to put additional effort into implementing this.

**Comment by MaartenDeen** [comment]
I don't agree. When you take JOSM and put a node at that location (be it 51.341, 6.0 or 51.68065844172967, 11.143805969953538) the "result from internal" is that exact location and the result from Nominatim is not far off.
Especially with the latter coordinate, brouter is 700 meters off. It is nowhere near where you expect it to be (a junction between a road and a track), there is even another junction inbetween. It will seriously put you on the wrong foot.

Taking the center of the nearest way is just plain wrong. It will also give an unpredictable error, the error is dependant on the length of the way and the relative position in the way, both of which are unknown to the user.
To keep near the second example: 51.681605, 11.1441273 is where the B185 branches off into the Alexanderstraße. Brouter will put you 800 meters away, which is not what you're looking for. Especially for coordinates it should be no problem returning the exact location.

I didn't know you were using the Leaflet Control Geocoder, so maybe this bug belongs there.

**Comment by nrenner** [comment]
Probably depends on expectation. I'm already happy that searching for coordinates works at all with the current setup. Also, I consider entering coordinates not a common use-case, but that's very subjective and I'm open to hear otherwise.

A workaround for now for getting exact location could be to edit the route points `lonlats` parameter in the URL (lon, lat order):
http://brouter.de/brouter-web/#map=16/51.3421/6.0002/OpenStreetMap&lonlats=6,51.341

Improving this in [Leaflet Control Geocoder](https://github.com/perliedman/leaflet-control-geocoder) would probably be the best solution.

**Comment by MaartenDeen** [comment]
To explain my usage: because brouter is probably the best configurable router for OSM I use it for walking trips. To mark a point where you want to start or go to, you often do not have very well defined addresses, especially in less populated areas so you have to rely on coordinates.

**Comment by MaartenDeen** [comment]
That makes it harder to find it again. When I'm planning trips I write my locations down. The planning is not done in one sitting, I may stop and continue the next day. What other method do I have to know where the locations are then by using lat-lon.
Then the next day I continue, search for the location I wrote down and am shown a different location than what I remember. That's not how it should work.
And when I'm in my car, which has a built-in navigation, I have to select the location there too. To do that interactively is just close to impossible so I enter the lat-lon there too.

**Comment by bagage** [comment]
A new LatLng provider that added in https://github.com/perliedman/leaflet-control-geocoder, but it was not yet released. As soon as it is, we can simply update `BR.Search` with:

```diff
-        geocoder: new L.Control.Geocoder.Nominatim({
+        geocoder: new L.Control.Geocoder.LatLng({
+            next: new L.Control.Geocoder.Nominatim({
                serviceUrl: 'https://nominatim.openstreetmap.org/'
+            })
        }),
```
