### ISSUE TITLE
strange route proposal from brouter web client

### ISSUE THREAD

**Issue by stephan-weber-di** [nrenner/brouter-web#139]
see gpx file attached. it was generated with profile "trekking, original", however, this track is to a larger extent not usable with a trekking bike.

[brouter-trekking-original_aber_nicht_fahrbar.gpx.txt](https://github.com/nrenner/brouter-web/files/2555012/brouter-trekking-original_aber_nicht_fahrbar.gpx.txt)

**Comment by poutnikl** [comment]
It may be better to post it in project abrensch/Brouter, managed by @abrensch. The nrenner/brouter-web is just for the web frontend, not for routing engine itself.

**Comment by stephan-weber-di** [comment]
ok, thanks, i will do so. i'm quite new here.

Am 7. November 2018 00:04:50 MEZ schrieb Poutnik <notifications@github.com>:
>It may be better to post it in project abrensch/Brouter, managed by
>@abrensch. The nrenner/brouter-web is just for the web frontend, not
>for routing engine itself.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nrenner/brouter-web/issues/139#issuecomment-436441835

-- 
Stephan Weber

**Comment by bagage** [comment]
Closing as suggested by @poutnikl (thanks :)).
