### ISSUE TITLE
Overlays hidden under custom layer

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#143]
*Reported in BRouter Group thread [BRouter-Web Release 0.7.0](https://groups.google.com/d/msg/osm-android-bikerouting/xAJw6uLigwY/EIQeScKiBQAJ).*

When adding a custom layer (e.g. `http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.png`) as base layer, it gets a `z-index: 9`, while the Cycling and Hiking overlay layers remain at `z-index: 7` and `8`, so they are displayed below the custom base layer and are not visible.

I guess this is just how the Leaflet Layers Control works by default. Maybe we could set [autoZIndex](https://leafletjs.com/reference-1.3.4.html#control-layers-autozindex) to false?

**Comment by littlehelper** [comment]
Hi, I observe the same issue. It seems that currently the drawing order is related to the order of adding the custom layers, is'n it?
Would be great if the custom layer's drawing order/priority could be set for each custom layer.
Thanks in advance.

BTW: Is '{s}' as placeholder for subdomain 0,1,2,3... as part of the layer's URL already supported?
