### ISSUE TITLE
NaN elevation breaks elevation profile

### ISSUE THREAD

**Issue by MichaelK92** [nrenner/brouter-web#147]
Hi!

I can’t really pin-point it but for some routes along the Croatian coast I get points with NaN elevation in brouter-web which break the elevation profile. Interestingly, when I re-draw it with slightly different coordinates I don’t get NaN at all or at other points (even though the route still follows the same roads).

Route used:
http://brouter.de/brouter-web/#map=9/44.9134/14.5322/OpenStreetMap&lonlats=14.548645,45.117987|14.488907,45.052238|14.726315,44.836032|15.183105,44.447469|14.007568,45.57557&profile=fastbike

Screenshot:
![screenshot of broken elevation profile](https://user-images.githubusercontent.com/24712390/50372871-76748a00-05d6-11e9-8fa3-36395231f556.png)

**Comment by MichaelK92** [comment]
Without looking at any of the code or number representations my personal guess would be that it gets a "-0" meter elevation and the language/lib doesn't know what to do with such a signed zero number/string.

**Comment by nrenner** [comment]
Thanks for reporting.

I tracked it down to a small example and it's missing elevation data for some points, see abrensch/brouter#137.

There is a PR at MrMufflon/Leaflet.Elevation#60 that might fix the profile, but not sure if just skipping those points is a good idea.

**Comment by abrensch** [comment]
For BRouter that's just the intended behaviour. If the elevantion from the SRTM data is "void" (=no data exists), then the last elevation along the track is repeated. But if the starting point is inside a SRTM void, you will have no data in the elevation profile up to the first non-void value.

**Comment by nrenner** [comment]
Are you actually already using the 30m SRTM or still the 90m CGIAR data? Isn't at least the CGIAR data supposed to be void-filled?

**Comment by bagage** [comment]
Another example (bridge is the issue): https://brouter.damsy.net/latest/#map=15/45.1781/4.8188/standard&lonlats=4.814286,45.18863|4.811883,45.184122|4.814329,45.180613

ps: posting it there too because I'm unsure if it's a front or engine issue actually, it might not be the same issue because it's not the starting point that is causing issue there.

**Comment by nrenner** [comment]
Another example from the [German Forum](https://forum.openstreetmap.org/viewtopic.php?pid=749903#p749903) today:
http://brouter.de/brouter-web/#map=13/53.5240/8.5720/osm-mapnik-german_style&lonlats=8.584442,53.538267;8.565903,53.529595;8.545475,53.520411

(Really fixed now by additionally loading the src file in 60b9a45)

**Comment by nrenner** [comment]
Some more details about why there is no data see [abrensch/brouter#137 (comment)](https://github.com/abrensch/brouter/issues/137#issuecomment-497462644).
