### ISSUE TITLE
Route through **all** roads?

### ISSUE THREAD

**Issue by govvin** [nrenner/brouter-web#155]
This is an awesome tool. I use it to plan my bike route in areas where I want to collect street-level imagery for Mapillary or OpenStreetCam. 

I'm wondering if it's possible to generate a route for a given area (selected by a polygon?) when I want to make sure I **go through all the roads within the network**.

**Comment by nrenner** [comment]
No, this is not supported by the backend routing engine https://github.com/abrensch/brouter.

This is the separate [Route inspection problem](https://en.wikipedia.org/wiki/Route_inspection_problem) or Chinese postman problem (CPP) and would require a specific implementation.

Potential alternatives I found (not tested):
- experimental [QGIS](https://qgis.org/) plugin [Chinese Postman Solver](https://plugins.qgis.org/plugins/chinesepostman/)
  - perhaps along with the [QuickOSM](http://plugins.qgis.org/plugins/QuickOSM/) plugin to download OSM data into QGIS
- [Sleeping Giant Rural Postman Problem](http://brooksandrew.github.io/simpleblog/articles/sleeping-giant-rural-postman-problem/) - blog post, using Python

**Comment by Phyks** [comment]
Quick comment on this, you can have a look at Vroom: http://vroom-project.org/ which is a FOSS doing this.
