### ISSUE TITLE
Import no-go areas from file

### ISSUE THREAD

**Issue by alesarrett** [nrenner/brouter-web#160]
It would be great to have the option to add a file of no-go areas previously prepared (maybe in geoJSON) to be included in BRouter Web. It would allow the calculation of routes based on more complex patterns than on the fly drawing no-goareas on the map.

**Comment by Phyks** [comment]
Hi,

This is something I was needed as well and I started a PR at https://github.com/nrenner/brouter-web/pull/161. This is still very much a work in progress, but feel free to give feedback :)

Best,

**Comment by Phyks** [comment]
#161 was merged, this issue can probably be closed, isn't it? :)
