### ISSUE TITLE
HU translation ready

### ISSUE THREAD

**Issue by debyos** [nrenner/brouter-web#167]
Dear All,

after consultations I have completed the [Hungarian translation](https://www.transifex.com/openstreetmap/brouter-web/dashboard/) so you can implement it [on the website](http://brouter.de/brouter-web/).

**Comment by bagage** [comment]
@debyos There are a few new strings (7) - could you translate them please? I'll do a release and Hungarian will be available on https://brouter.damsy.net after that (it is similar to brouter.de/brouter-web instance but with a more bleeding edge version).

**Comment by bagage** [comment]
BTW thanks for translating Brouter in Hungarian :tada:

**Comment by debyos** [comment]
OK, I have translated also the remaining strings. Thanks for putting it online!

**Comment by bagage** [comment]
Thanks @debyos, this is now live on https://brouter.damsy.net (version 99.18.0). Hit `ctrl+f5` if the version displayed is wrong and it should be ok!
