### ISSUE TITLE
HU version missing

### ISSUE THREAD

**Issue by debyos** [nrenner/brouter-web#168]
Dear All,
the Hungarian version at https://brouter.damsy.net/ does not seem to work, not even after hitting (ctrl) F5. 

Only the "About" section is in Hungarian plus one word (Distance/Távolság) at the bottom of the screen. Everything else continues to be in English. (And even the About section seems an outdated translation.)
Please try to fix it.
Thanks

Gábor

**Comment by bagage** [comment]
You should see the following:

![image](https://user-images.githubusercontent.com/1451988/55429208-39cc0d80-558b-11e9-8a8a-01779f7aeb22.png)

If not, can you take a screenshot of this page please: https://brouter.damsy.net/latest/?lng=hu#map=16/43.6634/3.8539/OpenStreetMap

**Comment by debyos** [comment]
Apparently, it depends on the browser: 
with Firefox it is in English whatever I do, 
with Chrome it is in Hungarian…

German and French work also with Firefox just Hungarian not.

**Comment by bagage** [comment]
Can you screenshot your firefox version please? Can you ensure that it is displaying Brouter 99.18.0 and not something else?

**Comment by debyos** [comment]
Yes, here you are! A brand new screenshot of my Firefox window:

![kép](https://user-images.githubusercontent.com/26843901/55435146-8cacc180-5599-11e9-85fb-b3a9385dd99b.png)

**Comment by bagage** [comment]
There is indeed something wrong. When you open the developer console (right click -> examine), if you hit F5 it will work. 
But as soon as the console is closed, it stops working… I'll investigate this further. Thanks for reporting!

**Comment by debyos** [comment]
Je t'en prie! ;-)

**Comment by bagage** [comment]
The issue seems to be fixed - I didn't do anything special but there was maybe a bug that was fixed when version 99.19.0 was deployed over 99.18.0.
