### ISSUE TITLE
distance marker (adjustable)

### ISSUE THREAD

**Issue by radlerandi** [nrenner/brouter-web#169]
I use brouter-web since some years to plan my bike trips, and i like it very much! thanks to your efforts!

It would be very helpful if there would be a distance marker, for example every 50 or 100 km (probably adjustable).

Also very helpful would be a button to split a track in 2 parts and get 2 perma links, that i can open in a new browser window.

**Comment by bagage** [comment]
Markers are currently used as a way to adjust the route generated by brouter engine. Maybe distance markers could be added on top of the route, but without interactivity enabled ("read only")?
