### ISSUE TITLE
Wrong reading of isunpaved in profile fastbike?

### ISSUE THREAD

**Issue by MaartenDeen** [nrenner/brouter-web#17]
I have [this route] (http://brouter.de/brouter-web/#zoom=16&lat=51.42302&lon=5.96575&layer=OpenStreetMap&lonlats=5.967979,51.429825|5.963602,51.419389&nogos=&alternativeidx=0&format=geojson&profile=fastbike).
With profile fastbike this has a cost of 3217.

It traverses a few ways tagged as highway=track, tracktype=grade2 with no additional tags: ways [140423237](http://www.openstreetmap.org/way/140423237), [277710748](http://www.openstreetmap.org/way/277710748) and [140423241](http://www.openstreetmap.org/way/140423241).
If I read the profile of fastbike right, an unpaved grade2 has cost 10, paved (not unpaved) grade2 has cost 3
**switch tracktype=grade2 switch isunpaved 10 3**

When I edit the profile and change this line to **switch tracktype=grade2 switch isunpaved 100 3**, the route is the same and the cost also stays on 3217. If I do **switch tracktype=grade2 switch isunpaved 10 3.1**, the cost goes to 3286.

For some reason, the tracks are seen as paved?
Or does the switch not work for some reason?

**Comment by nrenner** [comment]
It seems to me (if I get the notation right) that the [isunpaved assignment](https://github.com/abrensch/brouter/blob/5fd1e2e734667f8ba9b60272c28280a624a8bbad/misc/profiles2/fastbike.brf#L36) is negating the whole statement with ``not``:
``assign isunpaved not or surface= or ispaved or surface=fine_gravel surface=cobblestone``

instead of just ``ispaved``:
``assign isunpaved or surface= or not ispaved or surface=fine_gravel surface=cobblestone``

@abrensch

**Comment by MaartenDeen** [comment]
That does solve it, but I don't really see why it should matter.

I need to reconstruct the logic:
surface=cobblestone is false
surface=fine_gravel is false
ispaved is false
surface= is false (I assume this means any surface key)
Then the original version is
isunpaved = not (or surface= (or ispaved (or surface=fine_gravel surface=cobblestone)))
isunpaved = not (or false (or false (or false false)))
isunpaved = not (or false (or false false))
isunpaved = not (or false false)
isunpaved = not (false)
isunpaved = true

In the corrected version:
isunpaved = (or surface= (or (not ispaved) (or surface=fine_gravel surface=cobblestone)))
isunpaved = (or false (or true (or false false)))
isunpaved = (or false (or true false))
isunpaved = (or false true)
isunpaved = true

Also: if surface= is true when any surface key is set, then surface=fine_gravel and surface=cobblestone are not necessary in the logic.
Maybe it was meant as `assign isunpaved or not surface= or ispaved or surface=fine_gravel surface=cobblestone`
Anyway, why should `isunpaved` not be just `not ispaved`?

**Comment by nrenner** [comment]
> surface= is false (I assume this means any surface key)

I assumed ``surface=`` means "surface is not set", so it would be true.

From the http://brouter.de/brouter/profile_developers_guide.txt:
> \- \<empty> if the tag is not set or the value is empty
[...]
> The \<empty> value is refered to as an empty string, e.g. access=

**Comment by MaartenDeen** [comment]
That would make sense yes. If you read it like that than the switch is explained.

Still, my comment: why should `isunpaved` not be just `not ispaved`? To do it like it is now means some combinations are neither paved nor unpaved and fall through to the default cost at the end of the switch.

**Comment by MaartenDeen** [comment]
Changing it like that gives errors in other places, but that might be due to changes I made recently.
[This route](http://brouter.de/brouter-web/#zoom=14&lat=51.26118&lon=6.14324&layer=OpenStreetMap&lonlats=6.1199,51.275877|6.18084,51.256812&nogos=&alternativeidx=0&format=geojson&profile=fastbike) goes haywire when I change the isunpaved assignment. I changed most (all?) of the grade1 tracks in that area to surface=asphalt on april 7th. I assume those changes are in the online router?

**Comment by nrenner** [comment]
> Still, my comment: why should isunpaved not be just not ispaved?

abrensch would need to comment on this, he is the author of the profiles.

> I changed most (all?) of the grade1 tracks in that area to surface=asphalt on april 7th. I assume those changes are in the online router?

The routing data files at http://brouter.de/brouter/segments3/ are from April 15th, as well as the latest planet http://planet.openstreetmap.org/planet/ on which they should be based on, so your changes should be included.

You can check by switching to the "Data" tab in the web client where the tags are listed.

**Comment by abrensch** [comment]
>> Still, my comment: why should isunpaved not be just not ispaved?
> abrensch would need to comment on this, he is the author of the profiles

True, "isunpaved" is not just the inverse of "ispaved". The cases where isunpaved=ispaved=false are:
- some surfaces like cobblestone or compacted that you are not really looking for, but are solid surfaces still usable when wet
- the surface is not tagged

The second case is an important design principle of these profiles: "no news is good news". The level of detail in the tagging is not homogenous in OpenStreetMap, so if you e.g. require a grade1 to be tagged surface=paved, you will miss a lot of perfect grade1's that just don't habe the tag.
