### ISSUE TITLE
Some profiles route over highway=construction

### ISSUE THREAD

**Issue by MichaelK92** [nrenner/brouter-web#172]
The „Neue Linzer Donaubrücke“ is tagged as highway=construction, construction=secondary and still some profiles (e.g. trekking, shortest) route over it:

http://brouter.de/brouter-web/#map=16/48.3160/14.2961/OpenStreetMap&lonlats=14.288642,48.319634|14.298084,48.313462

Other profiles like car-fast or fastbike correctly route around it.

![Screenshot_2019-04-27_09-11-34](https://user-images.githubusercontent.com/24712390/56846193-7b22b500-68cc-11e9-9c85-7fede1e258c7.png)

**Comment by poutnikl** [comment]
It is matter rather of BRouter built in profiles, you may want to raise the issue at abrensch/brouter

**Comment by bagage** [comment]
As said by @poutnikl, this issue should be reported on brouter engine repository instead: https://github.com/abrensch/brouter/pull/132 

I'm closing this issue but feel free to reopen it on the engine side obviously!
