### ISSUE TITLE
Leaflet CDN is unreachable

### ISSUE THREAD

**Issue by leoluk** [nrenner/brouter-web#18]
Leaflet's CDN is down: http://cdn.leafletjs.com/leaflet-0.7.3/leaflet-src.js

Maybe use Cloudflare's instead? (https://cdnjs.com/libraries/leaflet)

**Comment by nrenner** [comment]
It's working for me. There has been an outage, but that should have been fixed: https://twitter.com/LeafletJS/status/603856231091064833 ?

For the upcoming release I'm bundling all dependencies and not use CDNs anymore.

**Comment by leoluk** [comment]
Weird - it's down for me. Probably depends on the location.

**Comment by krmr** [comment]
It is also down for me - but it seems not to be a location issue but rather related to https: After deactivating the rule for Leaflet JS.com in HTTPS Everywhere everything works fine again.

**Comment by nrenner** [comment]
cdn.leafletjs.com does not support HTTPS (neither does brouter.de).

Using Cloudflare would be an option, but I would rather move forward and bundle all with the upcoming release, unless people are still having issues with the Leaflet CDN.
