### ISSUE TITLE
Toggle network routing on/off, to enable route drawing in areas without route network 

### ISSUE THREAD

**Issue by gimoya** [nrenner/brouter-web#181]
Hi! Brouter is the best routing tool ever! - I use it online and as Locus add-on on my android device! In Locus, however, I have the option to digitize a route by hand, in areas where no routing network exists. This is not possible in the online version, but it would be an easy to implement feature, which would be a great advantage! For now, I always need to stop If I get to areas without route network! Many thanks, Kay

**Comment by bagage** [comment]
Can be either a duplicate or at least related to #68?

**Comment by gimoya** [comment]
@bagage yes, duplicate of #68 - thanks for the pointer!
