### ISSUE TITLE
nogo's are broken in current release

### ISSUE THREAD

**Issue by abrensch** [nrenner/brouter-web#183]
without a nogo, the server sees:

GET /brouter?lonlats=8.61886,49.692536|8.615341,49.699832&profile=trekking&alternativeidx=0&format=geojson

with a nogo, this gets:

GET /brouter?lonlats=8.61886,49.692536|8.615341,49.699832&nogos=8.614697,49.696536,105,undefined&profile=trekking&alternativeidx=0&format=geojson HTTP/1.1

and that results in a parsing error.

this is with or without the latest pull request on the brouter-repo applied, so looks like something is missing for parsing nogo-weights ?

**Comment by abrensch** [comment]
... fixed that by adding a "undefined"->NaN in the server code

**Comment by nrenner** [comment]
> ... fixed that by adding a "undefined"->NaN in the server code

Thanks. Does that mean that latest PRs abrensch/brouter#158 and abrensch/brouter#157 are also already deployed now?

**Comment by abrensch** [comment]
> 
> 
> > ... fixed that by adding a "undefined"->NaN in the server code
> 
> Does that mean that latest PRs [abrensch/brouter#158](https://github.com/abrensch/brouter/pull/158) and [abrensch/brouter#157](https://github.com/abrensch/brouter/pull/157) are also already deployed now?

yes
