### ISSUE TITLE
Upload (old) GPX tracks (e.g. from files or strava or runtastic)

### ISSUE THREAD

**Issue by Katzenstreu** [nrenner/brouter-web#192]
Hi!

I would like to optimize my routes and see some old routes at the same time on your map. I would like to change the new route a little bit.
Great would be the possibility to upload GPX files. And even more comfortable: Upload from fitness websites with tracking functions, e.g. from strava or runtastic.

Best regards
Tim

**Comment by nrenner** [comment]
Closing as duplicate of #30.

Loading tracks from third party sites is out of scope for me, unless someone else would be willing to implement this.

A general solution might be to offer pasting or dragging a download URL from some other site.
