### ISSUE TITLE
Wrong host in download URL in Microsoft Edge

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#193]
![Screenshot_2019-05-27 Dashboard(1)](https://user-images.githubusercontent.com/1092030/58437749-a36c2200-80cb-11e9-9e26-0b7906f765ca.png)

*Screenshot [https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0 ...](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fbrouter.de%2Fbrouter-web%2F%23map%3D13%2F47.7038%2F9.3653%2Fstandard%26lonlats%3D9.391594%2C47.721193%3B9.284649%2C47.694734&speed=1)*

Seems like the server request URL generated by Export is using `http://brouter.de` instead of  `http://h2096617.stratoserver.net:443`.

**Comment by nrenner** [comment]
Which is because `document.forms['export']['format'].value` returns `undefined` in Edge.

https://github.com/nrenner/brouter-web/blob/481b28759c9bf9952307190e5fd19d81a793eab7/js/control/Export.js#L25-L26

**Comment by bagage** [comment]
I don't have a windows here, but I'll try to fix this by the end of the week. Thanks for pinning it down @nrenner.

**Comment by nrenner** [comment]
I don't have a current Windows with Edge either, I tested with BrowserStack (cloud VM), which is free for Edge: https://www.browserstack.com/test-on-microsoft-edge-browser#

**Comment by bagage** [comment]
I've tested it and it works with Edge 18, but not with older Edge 17.
