### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by VoyteckPL** [nrenner/brouter-web#20]
Hi,
Is there any way to contact you Norbert? :) I would be greatful if you could contact me at wojciech.racek@gmail.com . Thank you in advance!
Best regards,

**Comment by nrenner** [comment]
The preferred way of contact is via GitHub issue or BRouter Google Group (see readme). I'm reluctant to publish a private contact as most are support requests and these should be public for the benefit of everyone. Will send you a PM.
