### ISSUE TITLE
Export: file name is the URI-encoded original name in MS Edge

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#201]
![grafik](https://user-images.githubusercontent.com/1092030/58784899-b8bde080-85e4-11e9-89dd-cb04b48f7691.png)

*Screenshot [https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0 ...](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fbrouter.de%2Fbrouter-web%2F%23map%3D13%2F47.7038%2F9.3653%2Fstandard%26lonlats%3D9.391594%2C47.721193%3B9.284649%2C47.694734&speed=1)*

The `Content-Disposition` header is as expected. I suppose Edge is taking the `download` attribute of the link instead of `Content-Disposition` header:

https://github.com/nrenner/brouter-web/blob/00ed1b53523562ab40ee97186113d7201034a1a1/js/control/Export.js#L52

**Comment by bagage** [comment]
Maybe for both this and #202 we should force regex validation on `input` client-side? We can copy/paste we regex used in brouter engine for that, probably the simplest fix?

**Comment by nrenner** [comment]
Not sure anymore, but it might be that we don't need both the `download` attribute and the `Content-Disposition` header. Maybe we could just remove the `download` attribute and Edge would also use the `Content-Disposition` header?

Otherwise, the solution for this one would be to use the unencoded name and apply the server file name regex.

> Maybe for both this and #202 we should force regex validation on input client-side?

You probably mean #194? Using the server regex alone won't help with #202?

**Comment by nrenner** [comment]
Edited above comment: I guess we need the `download` attribute itself, but maybe not the file name twice:

> If the HTTP header Content-Disposition: gives a different filename than this attribute, the HTTP header takes priority over this attribute.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes

Edge seems to behave differently (the other way round?).

**Comment by nrenner** [comment]
I removed the `download` attribute, it's redundant when `Content-Disposition` header is set. Should have done this when adding the latter because of cross-origin issue in #6.
