### ISSUE TITLE
Overlay transparency

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#213]
Hi,

I'm currently using an overlay map to show the noise in the streets in Paris (`https://tiles.phyks.me/bruitparif/{z}/{x}/{y}.png`). Sadly, this overlay is not semi-transparent (it is fully colored, without any alpha level).

I guess this is not the only map one would like to overlay which does not have an alpha channel. What about adding a setting to let user change opacity of the overlays (just the same as what is currently done for the route opacity).

This could be useful as well for very dense overlays, such as the Mapillary coverage in urban areas.

Thanks!

**Comment by nrenner** [comment]
I started testing blending modes a while ago with the idea to use for the route and overlays, in the hope that it might look better overall and the route/overlay might be less pale than with reducing opacity alone:

http://plnkr.co/edit/2n3YEksk1QBz8VjxGf2r?p=preview

This is setting [mix-blend-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) CSS style on the overlay layer container. Mode `multiply` is probably most helpful, not sure about the others, also depends on the background layer.

But not sure yet if this would be useful in addition to an opacity slider.

**Comment by Phyks** [comment]
I'd say that an opacity slider is the simplest (both from coding and usage) control on this.

Having the control on blending mode could be super useful indeed, but probably a more technical (for the user in particular)? A typical use case would be to have a nice render of relief with a relief overlay (which is usually done with a multiply operation). I did not know we could do it with CSS and Leaflet!

**Comment by nrenner** [comment]
The blending control in this form is just meant for testing. Most probably would be just a "blending" checkbox using multiply mode. But that would be a separate feature and also not really that helpful for the bruitparif layer, so just adding opacity slider now is fine.

**Comment by Phyks** [comment]
Closing this one as #215 has been merged.
