### ISSUE TITLE
Add a transport map in the available map tiles

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#214]
Hi,

I think it could be super useful to have a transport-oriented set of tiles available directly in Brouter-web (without adding one manually). The main use case would be to easily see end of rail lines to start a trip. 

Not sure about the possible candidates. I know https://www.thunderforest.com/maps/transport/, which is ok but has the default of displaying both buses and rails (whereas you usually cannot use a bike in a bus). This issue is specific to bike and would not affect someone using BRouter-web for hiking for instance.

I also know http://öpnvkarte.de/#3.04;48.845;12 which is not as readable I think. 

http://openptmap.org/ is probably a very good alternative.

Best,

**Comment by nrenner** [comment]
I'm going to remove Thunderforest maps, so the Transport layer is not an option. Added the other two.

**Comment by Phyks** [comment]
Thanks!

> I'm going to remove Thunderforest maps

Are you going to remove them alltogether (from the codebase as well)? Or are you simply going to remove them from the brouter.de website?

I think it would make sense to remove them from brouter.de (as discussed in #145), but it could still be useful within the codebase, conditionning on the presence of an API key in https://github.com/nrenner/brouter-web/blob/master/keys.template.js#L12.
