### ISSUE TITLE
Delete nogo areas

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#217]
Hi,

There is currently no way in BRouter-web to delete only the nogo areas, which could be especially useful with the new "upload" feature.

What about switching the trash icon to simply "Delete" and in the next modal having two checkboxes, (eventually ticked)?

- [x] Delete the itinerary
- [ ] Delete the nogos

Best,

**Comment by nrenner** [comment]
Yes, would make sense.

Not sure about the wording, maybe:
- [x] Delete route
- [ ] Delete all nogos
