### ISSUE TITLE
Add POIs in the exported route

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#222]
I thought that there was already an issue about that, but I'd like to:

- draw points on BRouter website, and enter a name for each
- then, when exporting the route (at least as GPX), export these points as `waypoints`. 

GPX syntax is:

```xml
<gpx>
  <wpt lon="3.866962" lat="43.674468">
    <name>My POI to visit</name>
  </wpt>
 <trk>...</trk>
</gpx>
```

**Comment by bagage** [comment]
NVM, it was on brouter engine side: https://github.com/abrensch/brouter/issues/91

I can see that you @Phyks already started working on it. Have you a plan for brouter-web side?

**Comment by Phyks** [comment]
I started to work on the BRouter side, adding an `exportWaypoints` parameter to export them in the traces (any file format). This is currently a boolean exporting all (from, to, via) or nothing.

This is replicated in brouter-web in https://github.com/nrenner/brouter-web/pull/221, but still very basic.

**Comment by bagage** [comment]
Indeed we talked about it and indeed currently we can export brouter 
![image](https://user-images.githubusercontent.com/1451988/62011048-5829ca80-b173-11e9-8705-d66a84adf9d1.png) markers as waypoints (from, to and via).

I'll add a button in brouter-web to add another type of waypoints, which are "not on the route" markers (nearby restaurants, campings, etc.), where one can add some custom text. Is that ok for you @nrenner @Phyks?

**Comment by nrenner** [comment]
Ok for me (although encoding user input is not properly solved yet, will create an issue with a suggestion). Would be useful for all formats.
