### ISSUE TITLE
Development: enable hot reload

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#230]
It would be great if site could be automatically reloaded on sourcecode changes. 

I saw that [SO post](https://stackoverflow.com/questions/43415506/how-to-make-a-refresh-in-browser-with-gulp) that links to gulp-livereload and also browsersync.

**Comment by nrenner** [comment]
Yes, might be nice to have. I guess BrowserSync would be the way to go, found these recipies in the official repo:
[Minimal BrowserSync setup with Gulp 4](https://github.com/gulpjs/gulp/blob/master/docs/recipes/minimal-browsersync-setup-with-gulp4.md)
[Server with live-reloading and CSS injection](https://github.com/gulpjs/gulp/blob/master/docs/recipes/server-with-livereload-and-css-injection.md)

**Comment by Phyks** [comment]
If anyone is working on this, seems that `yarn watch` only works for the first change and does not rebuild afterwards on subsequent changes :/

**Comment by bagage** [comment]
I'm seeing the same issue actually - it's not 100% reproducible but happens quite often. Let's create a separate issue :).

**Comment by bagage** [comment]
#238
