### ISSUE TITLE
allow to export import selected points

### ISSUE THREAD

**Issue by bmmt** [nrenner/brouter-web#231]
It would be very beneficial to Export and Re-import only the selected Points = waypoints =(Start+end+via) Points.
This would enable to modify an own trip and adopt the planed trip simply without reentering all Points. GPX and the other files allowing to Export the complete Track and contains much more Points.
Using Export Import (instead of saving on server) any data privacy / security concerns should not be relevant.

**Comment by nrenner** [comment]
The entered route points are reflected in the URL, so you can bookmark the current page in the Browser for later (re-)use.

Drag or copy the URL (in the address bar) to a new tab or window if you want to modify a copy the current route, e.g. to test and compare variants of it.

For exporting and importing the route (i.e. the route from/to/via points) to a file there already is the still open issue #16, so closing this one as duplicate.
