### ISSUE TITLE
sharing a customized profile with friends

### ISSUE THREAD

**Issue by EssBee59** [nrenner/brouter-web#232]
Hello,

I open this issue to get the Status of this old request:
Today, the use of a "customized profile" in the Brouter-web is not very easy. Many issues/requests exist, see 
https://github.com/nrenner/brouter-web/issues/26
as exemple.
For my own, I have such a customized profile (base on fastbike.brf) which I liked to share with Friends....
To make the use of a custom profile easier, many solutions are possible:
- Adding my profile in the list of the standards profiles (who / which concil can validate this?)  
- Extend the "profile box" in brouter-web (nearly as the nogo upload). As result, a custom profile saved on the PC could be uploaded and activated automatically by start)
- or or or…
Hope a solution can be found soon, and the fantastic Features of brouter can be used by all 
Regards

**Comment by nrenner** [comment]
For sharing #26 is the intended solution, so closing as duplicate.

The status is that #26 and some form of #127 are planned for of the upcoming version, see [milestone](https://github.com/nrenner/brouter-web/milestone/7) (from my part; there will probably be some intermediate release). But I keep planning this for quite some time now with always something else getting inbetween, so ...

> Adding my profile in the list of the standards profiles (who / which concil can validate this?)

As @abrensch is responsible for the domain and hosting, I leave it to him to decide if or which additional profiles should be added. You could add an issue or pull request at https://github.com/abrensch/brouter (see e.g. abrensch/brouter#179).
