### ISSUE TITLE
Show exact distance in meters

### ISSUE THREAD

**Issue by francwalter** [nrenner/brouter-web#237]
Hello
on the online BRouter Web Client there is the distance (de: "Entfernung") in km on the bottom left.
The km is rounded to the first digit after the dot, e.g. 0.5 km for 549 meter or 0.6 for 551 meter.
I did not find any setting or switch to show meter instead of km.

Frank

**Comment by nrenner** [comment]
You can see the not rounded value with meter precision in the tooltip when hovering over the value.
