### ISSUE TITLE
dist directory is missing from releases

### ISSUE THREAD

**Issue by giggls** [nrenner/brouter-web#257]
Regarding the installation instructions in README.md only config.js needs to be adjusted.

Unfortunately the index.html references files which are not even part of the distributionat least in release 0.10.3

Is there a build step for dist directory missing from README.md?

**Comment by nrenner** [comment]
What URL are you using to download the distribution?

I do see a `dist` folder in 
https://github.com/nrenner/brouter-web/releases/download/0.10.3/brouter-web.0.10.3.zip

Which is listed first under Assets for 0.10.3 at https://github.com/nrenner/brouter-web/releases.

**Comment by giggls** [comment]
*Argh* looks I downloaded source code. OK, layer 8 Problem then.

Sorry

**Comment by nrenner** [comment]
No worries.

Maybe Docker could help with installing and keeping it updated. I recently discovered there were some [Docker scripts](https://github.com/bstegmaier/docker-brouter-web) - now archived and not maintained. But not a priority for me.
