### ISSUE TITLE
Replace gulp-uglify with gulp-uglify-es

### ISSUE THREAD

**Issue by YaroShkvorets** [nrenner/brouter-web#258]
gulp-uglify doesn't support ES6+, so `yarn build` fails on simple `const`
Replacing it with gulp-uglify-es should do it

**Comment by nrenner** [comment]
gulp-uglify is not the problem. It's that my intention was to still support older browsers and that I haven't taken the time and energy to either properly define what browsers we still need/want to support or to introduce Babel (probably with Webpack) yet.

See #249 and discussion in #250.

**Comment by nrenner** [comment]
We're now using Babel to support ES6+, see #367.
