### ISSUE TITLE
Feature: possiblitiy to save latest location in user session?

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#28]
Currently when going on Brouter web, map is always on Germany and you have to zoom on your zone of interest. At least for me, my zone is always my home and so I always start by searching my city location, zoom on my street and then start drawing a new area.

Would it be feasible to store in a cookie (or else?) the latest location when exiting website and restoring it each time Brouter is launched? Or would it be too difficult/not appropriate/another solution is planned?

**Comment by nrenner** [comment]
Currently, the "Permalink" on the bottom right of the map is meant for this. It can be used both for sharing a route and to bookmark a specific map location. 

You also can set a first waypoint at your home location and then bookmark the Permalink, this way you already have the starting point set and can continue with drawing a route right away (pressing 'd'), e.g.:
http://brouter.de/brouter-web/index.html#zoom=13&lat=52.5059&lon=13.3471&layer=OpenStreetMap&lonlats=13.377206,52.51626&nogos=&profile=trekking&alternativeidx=0&format=geojson

**Comment by bagage** [comment]
Oh, I missed that tiny `Permalink` item which is great! I think I can live with that for now, thanks!

**Comment by nrenner** [comment]
Other people seem to miss that too, so I guess I need to make it more prominent or switch to an always updated Hash-URL, which seems to be more common nowadays.

**Comment by bagage** [comment]
An Hash-URL would have worked for me at least, definitely! 
But the fact that this is in bottom right corner of screen does not help spotting the label, since this is generally for license and boring stuff I never read :).
