### ISSUE TITLE
manual mode drawing

### ISSUE THREAD

**Issue by ryu80** [nrenner/brouter-web#282]
Hello,
sometimes i need to draw manually small parts of  the track without autorouting feature because there is not track at all on the map.
it could be nice to have an icon on which we can disable or enable autorouting .
thanks

**Comment by bagage** [comment]
Hi @ryu80,
Indeed it would be a nice feature to have, we already have #68 issue open for that actually :). You can upvote it if you wish so that we can see which features are the nost valued ones!
Thanks,
