### ISSUE TITLE
Waterway routing

### ISSUE THREAD

**Issue by Dirk--** [nrenner/brouter-web#283]
My little waterway-router https://routino.grade.de is pretty outdated. How about adding sophisticated waterway-routing to brouter-web?
As far as I know, some work is already in progress:
- https://github.com/poutnikl/Brouter-profiles/blob/master/river-poutnik.brf
- https://github.com/afischerdev/brouter-profile

**Comment by nrenner** [comment]
In theory you could setup your own specialized instance of BRouter-Web, see [standalone install instructions](https://github.com/nrenner/brouter-web#install-standalone-zip-client-and-server) to get you started locally and [BRouter instructions](https://github.com/abrensch/brouter#brouter-on-windowslinuxmac-os) for more details.

I leave it to abrensch to decide what profiles to add, and adding tags to lookup.dat would need to be done in the brouter repository, so could you please open an issue there:
https://github.com/abrensch/brouter/issues/new

**Comment by Dirk--** [comment]
example: https://brouter.grade.de
