### ISSUE TITLE
vector-tile support

### ISSUE THREAD

**Issue by Dirk--** [nrenner/brouter-web#289]
How about implementing vector-tile support? 

Setup of a vector-tile provider is quite cheap (compared to generating raster tiles) on network data:
e.g. https://maps.grade.de/cemt.html

Having a chance integrating this to bouter-web would make this great framwork even greater!

**Comment by nrenner** [comment]
Leaflet doesn't support vector tiles natively and I fear there is no ideal [plugin](https://leafletjs.com/plugins.html#vector-tiles) either, as we have learned in [#153 (comments)](https://github.com/nrenner/brouter-web/issues/153#issuecomment-464390856).

Maybe the [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet) binding would be the best option, but synchronizing two libraries probably also has its flaws and it's a bit like carrying a lorry with a van.

Don't know what your setup is, an easy way for integration would be serving the vector tiles as raster with [Tileserver GL](https://openmaptiles.org/docs/host/tileserver-gl/), but that would mean loosing many advantages of vector tiles.

**Comment by womisa** [comment]
Hello
I've come up with a makeshift solution.
 installed a local Vector Tileserver and integrated it via configuration in Brrouter web. This works very well for me.
server: [hier](https://github.com/telemaxx/mapsforgesrv_with_gradle/tree/master/mapsforgesrv_with_gradle/jars_ready2use)
Maps:[hier](https://www.openandromaps.org/)

**Comment by Dirk--** [comment]
@womisa : please share the brouter-web part

**Comment by womisa** [comment]
Am 11.05.2020 um 10:40 schrieb Dirk--:
>
> @womisa <https://github.com/womisa> : please share the brouter-web part
>

?????
Ich nehme den Telemaxx Server mit den OpenAndromap Karten. Ich starte 
die Jar Datei mit den entsprechenden Parameter MAP Stylesheet.

Beispiel BRouter-WEB config.js

(function() {

     var hostname = window.location.hostname;
     var params = new URLSearchParams(window.location.search.slice(1));

     BR.conf = {};

     // Switch for intermodal routing demo
     BR.conf.transit = false;
     // or as query parameter (index.html?transit=true#zoom=...)
     // (uses search/query (?) not hash (#) params, as config only 
executed once at load)
     // TODO not included in permalink (better replace permalink with 
hash plugin)
     //BR.conf.transit = params.has('transit') && (params.get('transit') 
=== 'true');

     if (hostname === 'brouter.de' || hostname === 
'h2096617.stratoserver.net') {

         // online service (brouter.de) configuration

         BR.conf.profiles = [
             'trekking',
             'fastbike',
             'car-eco',
             'car-fast',
             'safety',
             'shortest',
             'trekking-ignore-cr',
             'trekking-steep',
             'trekking-noferries',
             'trekking-nosteps',
             'moped',
             'rail',
             'river',
             'vm-forum-liegerad-schnell',
             'vm-forum-velomobil-schnell',
             'fastbike-lowtraffic',
             'fastbike-asia-pacific'
         ];

         BR.conf.host = 'http://h2096617.stratoserver.net:443';
         BR.conf.profilesUrl = 'http://brouter.de/brouter/profiles2/';

     } else {

         // desktop configuration

         BR.conf.profiles = [
             'trekking',
             'fastbike',
             'car-eco',
             'car-fast',
             'car-vario',
             'car-test',
             'shortest',
             'moped',
             'vm-forum-liegerad-schnell',
             'vm-forum-velomobil-schnell',
             'fastbike-lowtraffic',
             'fastbike-asia-pacific',
             'hiking-beta',
             'hugo'
         ];

         BR.conf.host = 'http://127.0.0.1:17777';

         // Pre-loading selected profile disabled locally. Needs 
brouter-web to run on a
         // local web server with the profiles in a subdirectory or 
allowing file access
         // in the Browser (security!), see
         // 
https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally
//        BR.conf.profilesUrl = 'http://localhost:17777/./customprofiles/';
//        BR.conf.profilesUrl = 'file://./customprofiles/';
     }

     // Removes default base layers when 'true'. Useful for only having 
custom layers (see below).
     BR.conf.clearBaseLayers = true;

     // Add custom tile layers
     // URL template see http://leafletjs.com/reference.html#tilelayer
     // Multiple entries separated by comma (,)
     BR.conf.baseLayers = {
         'WmsMapsforge': 'http://127.0.0.1:8080/{z}/{x}/{y}.png'
         // 'display name': 'url'[,]
         // e.g. for offline tiles with 
https://github.com/develar/mapsforge-tile-server
         //'Mapsforge Tile Server': 'http://localhost:6090/{z}/{x}/{y}.png'
     };

     // Base layer to show on start, as position number in the layer 
switcher, starting from 0, default is first
     BR.conf.defaultBaseLayerIndex = 0;

     // Initial route line transparency (0-1, overridden by stored 
slider setting)
     BR.conf.defaultOpacity = 0.67;

     // Minimum transparency slider value on load, values between 0 and 
1 (0=invisible).
     // 0 = no minimum, use stored setting; 1 = always reset to full 
visibility on load
     BR.conf.minOpacity = 0.3;

     BR.conf.routingStyles = {
         trailer: {
             weight: 5,
             dashArray: [10, 10],
             opacity: 0.6,
             color: 'magenta'
         },
         track: {
             weight: 5,
             color: 'magenta',
             opacity: BR.conf.defaultOpacity
         },
         trackCasing: {
             weight: 8,
             color: 'white',
             // assumed to be same as track, see setOpacity
             opacity: BR.conf.defaultOpacity
         },
         nodata: {
             color: 'darkred'
         }
     };

     // transit (intermodal routing) demo config
     if (BR.conf.transit) {

         BR.conf.profiles = [
             '../im/bike',
             '../im/foot',
             '../im/like-bike',
             '../im/like-foot',
             'trekking',
             'fastbike',
             'shortest',
             'moped',
             'car-test'
         ];

     }
})();

**Comment by Dirk--** [comment]
just a quick Leaflet.VectorGrid test:
https://maps.grade.de/Leaflet.VectorGrid_120.html
'maxNativeZoom' of tile source is '10' 
As mentioned in [issues/153](https://github.com/nrenner/brouter-web/issues/153) , overzooming sucks....

**Comment by Dirk--** [comment]
today a first shot at Leaflet.VectorTileLayyer:
https://maps.grade.de/Leaflet.VectorTileLayyer.html
- overzooming works like expected
Limitations:
- no point features support (yet)

**Comment by Dirk--** [comment]
and finally updated my ol vector map 
https://maps.grade.de/cemt.html 
and tile-source (maxZoom 14) 
https://tiles.grade.de/tiles.py/cemt-vector-2020/{z}/{x}/{y}.pbf

**Comment by nrenner** [comment]
Thanks for the updates.

Are you going to test [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet) with [Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/overview/) as well?

Right now, your layer looks simple enough for the plugins you already tested (beside the missing features) and Mapbox GL JS would probably be overkill, just like for the Mapillary coverage layer. But as soon as you want anything more advanced, like text label rendering, Mapbox GL JS would probably be the best option?

What is your stack to generate the vector tiles? When you say cheap, this means probably generating and uploading all tiles as static files in advance, without generation on request and automatic updates?

And by the way, why are you querying the Overpass API on point click, when vector tiles would allow including the data and interacting with it on the map?

**Comment by Dirk--** [comment]
- ok, the next days I will try mapbox-gl-leaflet as well  ...
- my 'cheap' vector-tiles setup https://wiki.openstreetmap.org/wiki/User:Kannix/vector-tiles

overpass query on click:
- the user gets up-to-date data (eg. phone number of bridge/ lock)
- I also query seamark, leisure, amenity, shop (data that is not on CEMT vector-tile layer, but might make the inland navigator happy)

**Comment by Dirk--** [comment]
and here comes test number 3: https://maps.grade.de/Leaflet.mapboxGL.html
- drawback: no data-driven styles for 'line-dasharray' https://github.com/mapbox/mapbox-gl-js/issues/3045

**Comment by nrenner** [comment]
Hm, zooming is a lot slower than with Leaflet or Mapbox GL JS alone.

**Comment by Dirk--** [comment]
thanks to Norbert's hints, I managed to inject a vector-tile-layer: 
https://wiki.openstreetmap.org/wiki/User:Kannix/brouter/vector-tiles

**Comment by Dirk--** [comment]
after fiddling with maplibreGL/mapboxGL the last days, I would vote for this.
- supported by mapbox, openTiles, MapTiler (and offer tools and infrastructure needed)
- fairly easy setup, just decide base or overlay and link a single 'style' file (containing all about tile source and styling)
Vector-Layers are great for those, wanting their own maps with little effort!

**Comment by Dirk--** [comment]
Sorry for uglifying the code, I am just no programmer ...

I would like to show two variants:
- https://brouter.grade.de/index-alpha.html (injecting vector-layer to BR.Map)
- https://brouter.grade.de/index-beta.html (direct injection of vector-layer into recovered leaflet map object)

Relevant changes located at index-[].html (end of file) and /dist/brouter-web-[].js (search for 'grade.de') 

Any pro up to beautifying the vector-layer idea?

**Comment by nrenner** [comment]
We now have MapLibre GL JS integrated (13efb48), see:
- short doc [in CONTRIBUTING.md](https://github.com/nrenner/brouter-web/blob/master/CONTRIBUTING.md#vector-tiles--dem)
- Mapillary layer as an example (commit d5a6a0a).
