### ISSUE TITLE
Display current point of altitude graph when selecting point on the trace

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#29]
Currently, when mouse moves over the left graphic X-axis distance / Y-axis altitude, the equivalent point is shown on the route as blue point.
But when you do the opposite, it does not work. I would like to use it to see the distance between 2 points on my route so that I can split the route in equivalent steps.
Is this possibility planned.. or did I miss it as #28 :)?

**Comment by nrenner** [comment]
No, this feature is actually missing :) The elevation plugin added this a while ago, but there were some glitches and because of the line marker it didn't work right away, so I postponed adding this.

**Comment by bagage** [comment]
Thanks for adding it to the 0.6.0 milestone then, I will look forward to its release now!

**Comment by bagage** [comment]
Awesome, thanks @nrenner!
