### ISSUE TITLE
HTML draw priority and color of POI markers

### ISSUE THREAD

**Issue by radlerandi** [nrenner/brouter-web#316]
The HTML draw priority (if this is the right term) of POI markers seems a little bit weird.
Sometimes they are behind waypoint markers, sometimes in front of them.
In my opinion it would be best, if they are always displayed on top of waypoints.
And because both types of markers are shades of blue it is a bit hard to spot them on a map with a lot of waypoints (especially right now when they are behind them)

example link https://tinyurl.com/ydhkt5eu
(in the south of the track there is another POI marker, at the same zoom level it shows a different behaviour https://tinyurl.com/y9c4xg2l )

![1](https://user-images.githubusercontent.com/6453989/85203842-a3f7dc00-b310-11ea-9132-49c2ec8f6c8d.PNG) ![2](https://user-images.githubusercontent.com/6453989/85203844-a4907280-b310-11ea-9bc4-b8f3a162e538.PNG) ![3](https://user-images.githubusercontent.com/6453989/85203845-a4907280-b310-11ea-8d68-2714b765f454.PNG) ![4](https://user-images.githubusercontent.com/6453989/85203846-a5290900-b310-11ea-818c-7714bfedf6df.PNG) ![5](https://user-images.githubusercontent.com/6453989/85203847-a5290900-b310-11ea-9b59-a29bca2ff10c.PNG) ![6](https://user-images.githubusercontent.com/6453989/85203849-a5c19f80-b310-11ea-9e3c-90f16185b44a.PNG) ![7](https://user-images.githubusercontent.com/6453989/85203850-a5c19f80-b310-11ea-9693-544bce9683b6.PNG) ![8](https://user-images.githubusercontent.com/6453989/85203852-a65a3600-b310-11ea-92a1-573219bad023.PNG)

**Comment by bagage** [comment]
Thanks for reporting the issue @radlerandi! Indeed it would make sense to have a fixed Z-order.
We have global issue with colors though (because background maps use various colors and we have a lot of features which need different ones too), but it can definitely be improved.

I think this is a good first issue for new comers, so labeling as is.

**Comment by radlerandi** [comment]
ok
