### ISSUE TITLE
resized profile box is transparent

### ISSUE THREAD

**Issue by jotpe** [nrenner/brouter-web#32]
When resizing the profiles box over the normal border its background is sometimes transparent:

![profilebox](https://cloud.githubusercontent.com/assets/3539168/9917100/17ed3be8-5cc0-11e5-999a-42947dba6967.png)

**Comment by nrenner** [comment]
It gets a solid background when you click into the textarea, i.e. when it has the focus. This is sort of on purpose.

What is missing is the ability to maximize/resize the entire profile control, not just the textarea, this is only enabled as an ugly workaround until there is a proper solution.

**Comment by nrenner** [comment]
Won't fix, see #35
