### ISSUE TITLE
Delete last point

### ISSUE THREAD

**Issue by francwalter** [nrenner/brouter-web#33]
Hello
this is more a feature request: like in GPSies possible, in the brouter-web there is strongly a button missing to delete just the last point (or I am not finding it).
It is possible to delete the whole track, and it is possible to move the last point, but not possible to delete the last point.
Possible to implement?
Thanks

frank

**Comment by nrenner** [comment]
There is no button, but you can click on any point to delete it.

**Comment by francwalter** [comment]
Thank!
I didnt know this. Maybe then a delete button not necessary, but more intuitive it would be.

**Comment by poutnikl** [comment]
More intuitive, but less handy, with extra pointer moving toward the button.

**Comment by nrenner** [comment]
The cursor currently changes to "pointer" when hovering a marker, to indicate that it is clickable/interactive, and there is a descriptive tooltip for the marker. An improvement could be a more specific cursor symbol, e.g. with a trash can, or an extra delete button when hovering/approaching the marker.

When referencing GPSies, do you mean the "undo" button (lower right in the [track creator](http://www.gpsies.com/createTrack.do))?

This does more than just deleting the last point, it takes back any previous action, e.g. restores the previous position of a moved point.

**Comment by francwalter** [comment]
Yes, I mean the "Rückgängig" (Letzte Aktion rückgängig machen) Button, id="undoCounter"

**Comment by radlerandi** [comment]
I came here to Brouter@Github just to look, wether an issue for this is already open/closed. 
I'm planing a "ride every road" in my neighbourhood and it would extremely useful if i could remove the last waypoint(s) by "b" or "u" key (back, undo) or any other key. Since brouter has hotkeys q/esc and d i thought that it would be possible to add such a key.

**Comment by francwalter** [comment]
I just now came back to this issue, because I forgot about it and was searchin' again for this "undo" function :)
So after about 10 minutes of search I found my own topic here :) :)
Still I miss for intuitive use that button.
It would be enough if there were any help button where all functions and buttons are shortly explained.
