### ISSUE TITLE
Dark lines at degrees of longitude / latitude when hill shading layer ist displayed

### ISSUE THREAD

**Issue by Negativland** [nrenner/brouter-web#335]
In higher zoom levels (11 and above), BRouter-web draws dark lines at each 10th degree of longitude and each 10th degree of latitude, examples:

https://brouter.de/brouter-web/#map=15/50.0000/10.0000/osm-mapnik-german_style,HikeBike.HillShading&profile=vm-forum-velomobil-schnell

https://brouter.de/brouter-web/#map=13/40.0000/20.0000/osm-mapnik-german_style,HikeBike.HillShading&profile=vm-forum-velomobil-schnell

… but not everywhere on the planet. Where degrees of lon/lat are not multiples of 10, this problem does not seem to appear.

**Comment by nrenner** [comment]
All maps in BRouter-Web are from external providers, so nothing we can do.

The Hillshading layer is part of the Hike & Bike Map, you get to the original site with the Hillshading link on the bottom right:
http://hikebikemap.org/?zoom=15&lat=50&lon=10&layer=HikeBikeMap
http://hikebikemap.org/?zoom=13&lat=40&lon=20&layer=HikeBikeMap

My impression is that this map is not really maintained anymore.

Suggestions for an alternative hillshading layer are welcome.

**Comment by alu-ka** [comment]
Alternative hillshading: https://cycling.waymarkedtrails.org/#?map=15!50!10
