### ISSUE TITLE
Feature Request: display electrified option

### ISSUE THREAD

**Issue by xyre** [nrenner/brouter-web#338]
Hello everybody. 

It would be great if the electrification of the railway routing could also get displayed. Probably easiest would be to display the electrified option (https://wiki.openstreetmap.org/wiki/Key:electrified) in the data table.

thanks and kind regards!

**Comment by nrenner** [comment]
The key `electrified` is not available in the underlying data ([lookups.dat](https://github.com/abrensch/brouter/blob/master/misc/profiles2/lookups.dat)).

You would need to open an issue to add it in the backend (https://github.com/abrensch/brouter), but I fear the [rail profile](https://github.com/abrensch/brouter/blob/master/misc/profiles2/rail.brf) is only meant as a very basic example and not for more sophisticated uses.
