### ISSUE TITLE
Basic mobile support

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#34]
Touch support for controls (stopPropagation for touch events?), see reported issues:

[brouter web: Pulldown menu do not work](https://groups.google.com/d/msg/osm-android-bikerouting/knPyGLZO-Rw/gex4v5WMBgAJ)
- Profile and Alternative option lists not selectable

[Is there any internet browser for android devices which works with http://brouter.de/brouter-web/ (altitude profile, 4 possibilities, GPX download)?](https://groups.google.com/d/msg/osm-android-bikerouting/ZGjjeD-IpLI/mdF3SSZn2AkJ)
- not able to insert (copy and paste) Profile code
- not able to click/touch on GPX download

**Comment by bagage** [comment]
I know that you did some work regarding this issue @nrenner (and maybe #35), can you share the current status please? I'd again gladly help to make it (and #35 too) happens!

**Comment by nrenner** [comment]
Was going to ask and share what I have. I would be happy if you would take over the mobile support!

Actually, there isn't much yet, just some first experiments, see the `mobile-test` branch. I also have some notes, I will clean these up and make a wiki page tomorrow.

What are your ideas? What would be your approach?

**Comment by nrenner** [comment]
@bagage See wiki pages [Mobile](https://github.com/nrenner/brouter-web/wiki/Mobile) and [Mobile code snippets](https://github.com/nrenner/brouter-web/wiki/Mobile-code-snippets). So I guess that's all I have right now.

**Comment by bagage** [comment]
Thanks, awesome! Your wiki seems complete enough of existing issues; I have yet no solution as a developer, but I'll dig into some code & your references & other responsive design maps to be inspired from.
I'll update you when I have more precise ideas.

**Comment by RoPP** [comment]
[Here](https://github.com/RoPP/brouter-web) attempt to make BRouter-web a little bit more mobile friendly. 
This is still a WIP branch and there is still some missing features but it should be enough to test and see if it is the way to go.

![screen shot 2016-08-09 at 11 49 05](https://cloud.githubusercontent.com/assets/45775/17512954/a3a35502-5e2a-11e6-8036-6e6e86f3d578.png)

**Comment by nrenner** [comment]
Wow, that's already a working mobile version!

Some thoughts:
- Profile name: consider long names e.g. 'vm-forum-velomobil-schnell'
- Elevation graph: What was the reason for having our own implementation? What are your plans for that?
- Options: while this is Ok for mobile, on the desktop I would still like being able to switch through profiles/alternatives (e.g. up/down keys) and see the result without a modal blocking the screen.
- No left pane / sidebar: not really needed for mobile, but I think we can't do without on desktop, esp. for data tab (missing?) and future turn instructions list #42 and tag graph #45, that all should be next to the map and synchronize highlight on hover.

**Comment by bagage** [comment]
I will continue the work started by @RoPP, but here are some replies:
* long names won't fit on small screens, maybe we should avoid having too long names? In my opinion this is not a very important information anyway once you selected it.
* i'll fix up/down shortcuts on desktop.
* data tab should indeed be readded on desktop. Considering #42 and #45 let's see when they happen!

**Comment by bagage** [comment]
I will continue the work started by @RoPP, but here are some replies:
* long names won't fit on small screens, maybe we should avoid having too long names? In my opinion this is not a very important information anyway once you selected it.
* i'll fix up/down shortcuts on desktop.
* data tab should indeed be readded on desktop. Considering #42 and #45 let's see when they happen!

In the mean time is there any ETA for next release (to use #49 and #50 as soon as possible)? Thanks.

**Comment by poutnikl** [comment]
Longnames can be used quite often, referring to values of various flags or tunables. Especially with my  [profile generator](https://github.com/poutnikl/Brouter-profiles/blob/master/sedbatch.bat )
See e.g. "Car-FastEco-TollFree-SecondaryRoads.brf"

**Comment by nrenner** [comment]
> - long names won't fit on small screens, maybe we should avoid having too long names? In my opinion this is not a very important information anyway once you selected it.

Not sure about avoiding long names, maybe switching to an alternative short name or shorten display with "..." in the middle on small screens. But agree that as a simple solution we can also just not show it.

> - i'll fix up/down shortcuts on desktop.

One idea would be to directly integrate the two dropdowns into the top bar.

> - data tab should indeed be readded on desktop. Considering #42 and #45 let's see when they happen!

Forgot to mention the [Itinerary](https://github.com/nrenner/brouter-web/blob/master/js/control/Itinerary.js) control that is shown as tab in the transit demo (see config.js).

Generally, the mobile version already looks great, just a bit too focused on mobile for my taste right now. I don't insist on keeping the current left pane, some other collapsible [Sidebar](https://github.com/nrenner/brouter-web/wiki/Mobile#sidebar-examplesalternatives) will also do for the data table and for editing the profile.

My original motivation for brouter-web was to build some kind of IDE for profile development and a planning tool with a focus on desktop. So mobile support would be great, it just shouldn't affect the desktop experience too much, e.g. by requiring more clicks than before or slowing down feedback loops.

**Comment by nrenner** [comment]
> In the mean time is there any ETA for next release (to use #49 and #50 as soon as possible)? Thanks.

Well, the plan was to have [version 0.6.0](https://github.com/nrenner/brouter-web/milestone/1) ready for the start of the bike season - so much for ETAs. Already was thinking about splitting the milestone, but still wanted to look for icon set alternatives and do some other minor stuff.

But now that we have exceeded the Bing usage limit, I really should add a replacement and get some release out soon.
