### ISSUE TITLE
eslint: location.hostname() is not supported in Opera 71 

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#353]
There is a new compat error related to `location.hostname` in config.js when running `yarn lint`:

>   2:18  error  location.hostname() is not supported in Opera 71  compat/compat
>   2:20  error  location.hostname() is not supported in Opera 71  compat/compat

**Comment by bagage** [comment]
Also, it would probably be worth adding `yarn lint` to `package.json` test script?

**Comment by nrenner** [comment]
Hm, running `yarn lint` I don't see these messages, I just get:
```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```

> Also, it would probably be worth adding yarn lint to package.json test script?

Yes

**Comment by bagage** [comment]
Yes @nrenner to have the error you have to upgrade `"eslint-plugin-compat": "^3.3.0",` to `3.3.1` or more, then `yarn && yarn lint` should raise the error :).

**Comment by bagage** [comment]
But I tested with opera 72 locally and it works great, I think this is a false positive, see https://github.com/amilajack/eslint-plugin-compat/issues/419
