### ISSUE TITLE
Allowed zone as buffer around admin boundary

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#358]
Follow-up to #357. See also [[de] Corona Bewegungseinschränkung 15 km](https://github.com/nrenner/brouter-web/wiki/%5Bde%5D-Corona-Bewegungseinschr%C3%A4nkung-15-km).

@mjaschen would you be interested in implementing this? Otherwise I might give it a try today.

I will be looking into potential Overpass API queries.

**Comment by mjaschen** [comment]
The OSM Wiki has some details about administrative boundaries: <https://wiki.openstreetmap.org/wiki/DE:Grenzen#Grenzen_in_Deutschland>

I'm not sure what a good UI for that feature would look like. Ideas that came to my mind:

- search form (similar to the existing location search) in which address, city, county ("Landkreis")) can be entered; show results as a drop-down list with an indicator which level of administrative boundary would be rendered when an entry is selected
- query the surrounding administrative boundaries when clicking at a location on the map → how can the user choose the right level of boundary in this case? A modal dialog?
- in each case load the selected administrative boundary polygon from Overpass Turbo, expand it by 15 km and use it as allowed zone (similar to the existing radius tool)
- keep the current radius-zone-tool unchanged as it already covers the requirements for allowed zone around the own address

Selecting the correct administrative boundary level would be the next challenge:

- "Landkreise" and "Kreisfreie Städte" are a level 6 boundary (for Brandenburg), that seems to be unambiguous
- a german "Gemeinde" has the administrative boundary level 8, but there are "Verbandsgemeinden"/"Ämter" which have level 7. Sachsen-Anhalt explicitly mentions "Verbandsgemeinden", others don't (Bayern, Hessen, Thüringen).

**Comment by nrenner** [comment]
There is also https://wiki.openstreetmap.org/wiki/DE:Grenze.

My idea was to use the current UI (allowed zone button) and automatically determine what (if any) rules apply to the coordinate that the user clicked. This would be done by checking whicht state boundary it is in and hardcoded rules.

I'm also unsure about admin_level for Gemeinde/Verbandsgemeinde.

**Comment by nrenner** [comment]
Here is a draft of potential Overpass API queries.

Alternatives might be:
- export and include the Bundesland geometries and use a point-in-polygon check with turf to determine which rule applies
- use Nominatim reverse geocoding instead of Overpass API, we [already use that](https://github.com/nrenner/brouter-web/blob/87c571d97698ccf99ab2a943e5273e6ff5ea0ff0/js/control/Export.js#L112-L129) to query places for the track name

## Bundesland

```
[out:json];
is_in(47.7261896, 9.5322653);
area._[admin_level="4"];
out;
```

http://overpass-turbo.eu/s/12d6
http://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%3B%0Ais_in%2847.7261896%2C%209.5322653%29%3B%0Aarea._%5Badmin_level%3D%224%22%5D%3B%0Aout%3B%0A

## Gemeinde/Verbandsgemeinde

```
[out:json];
is_in(47.7261896, 9.5322653)->.a;
(
  area.a[admin_level="7"];
  area.a[admin_level="8"];
)->.p;
relation(pivot.p);
out geom;
```

http://overpass-turbo.eu/s/12de
http://overpass-api.de/api/interpreter?data=%20%20%5Bout%3Ajson%5D%3B%0A%20%20is_in%2847.7261896%2C%209.5322653%29-%3E.a%3B%0A%20%20%28%0A%20%20%20%20area.a%5Badmin_level%3D%227%22%5D%3B%0A%20%20%20%20area.a%5Badmin_level%3D%228%22%5D%3B%0A%20%20%29-%3E.p%3B%0A%20%20relation%28pivot.p%29%3B%0A%20%20out%20geom%3B%0A

There is also a way to output individual geometries as GeoJSON, so we would not need a library like [query-overpass](https://github.com/perliedman/query-overpass#api) or [osmtogeojson](https://github.com/tyrasd/osmtogeojson):
https://dev.overpass-api.de/blog/flat_world.html

The 15 km buffer can be done with [Turf.js buffer](https://turfjs.org/docs/#buffer) that we already use.

**Comment by bagage** [comment]
Since there is more and more context-aware features in BRouter, and now that turf is already embedded, it might be worth to privilegies:

> export and include the Bundesland geometries and use a point-in-polygon check with turf to determine which rule applies

Benefits to me are:

- no need for external providers (eg. it will work offline too, for instance if/when I get the time to make the Android PWA/TWA)
- no user geodata "leaking", eg better privacy.
- no async query, eg better responsivity.

This would be useful for:

- country specific limited areas (France - which is currently not active but I might be reactivated later, Germany, Ireland ?, etc.)
- country specific code (only [on my instance](https://github.com/bagage/brouter-web/blob/dev/js/index.js#L23-L31) but I'm using that for France Bicycle Annual Poll)
- it could be used for country specific rules if we wanted to in the future (specific limitations or such).

The complexity of the German system seems way higher than the French one though, so good luck with that! :).

**Comment by Negativland** [comment]
Nice feature, but it has a little bug: when the browser ist set to another language than german (i. e. english) it draws a buffer zone of only 1 km around the home location; see screenshot attached.

![Screenshot from 2021-01-19 10-47-02](https://user-images.githubusercontent.com/22883877/105017694-5c6f3500-5a44-11eb-8cb7-486a1971870b.png)
