### ISSUE TITLE
Using browser language to determine country-specific features is flawed

### ISSUE THREAD

**Issue by Negativland** [nrenner/brouter-web#360]
I don't know if anyone reads comments on already closed issues, so please see https://github.com/nrenner/brouter-web/issues/358#issuecomment-762730701

**Comment by nrenner** [comment]
Thanks for reporting. I find it better to not re-open implemented feature requests, but to open a separate issue for a bug like you did here.

**Comment by nrenner** [comment]
*from [#358 (comment)](https://github.com/nrenner/brouter-web/issues/358#issuecomment-762730701) by @Negativland:*

Nice feature, but it has a little bug: when the browser ist set to another language than german (e. g. english) it draws a buffer zone of only 1 km around the home location; see screenshot attached.

![Screenshot from 2021-01-19 10-47-02](https://user-images.githubusercontent.com/22883877/105017694-5c6f3500-5a44-11eb-8cb7-486a1971870b.png)

P. S.: the "1 km go-to-zone" can be set worldwide which is also a bit odd.

**Comment by nrenner** [comment]
We currently use the browser language setting to determine if the French or German radius rules apply or if the button should appear at all. I already got another report, so the language setting is less reliable than I hoped.

As a workaround you can override the language by passing it in the URL:
https://brouter.de/brouter-web/?lng=de-DE
https://brouter.de/brouter-web/?lng=de-DE#map=10/50.0977/8.6641/osm-mapnik-german_style&ringgo=8.677826,50.111332,15000

> P. S.: the "1 km go-to-zone" can be set worldwide which is also a bit odd.

This is an additional bug, the check to not add the button outside FR/DE does not work.

**Comment by nrenner** [comment]
My only idea right now is to check on every map move if the map center is inside the country boundary of FR or DE, either in addition or as a replacement for the browser language check.

**Comment by Negativland** [comment]
>  language setting is less reliable than I hoped.
(…)
> This is an additional bug, the check to not add the button outside FR/DE does not work.

From the user perspective it's the same, because the buffer zone depends on the location you're in, not the language you speak.

Possible solutions:

1. Change the function to "set buffer zone (where applicable)". If the user then sets his home location in germany, the 15 km rule is used; if e. g. in the UK it just says "you're lucky – no limitation"
2. … make it a general "choose your activity radius". So by default, one can choose to move no further than n km from home. Wherever limitations apply accordingly, these are used (aos of today in FR and DE).

**Comment by nrenner** [comment]
You're right. Implemented 1. (sort of) in #362.

I'm trying to keep the number of buttons on the screen as minimal as possible, especially didn't want to show this one for users that don't need it. But hiding doesn't really make sense here, as when zoomed far out we would need to show it anyway.

Not sure about a general solution 2, I don't really see the use case and personally don't want to spend time on it.

**Comment by Negativland** [comment]
Good choice. Keep it simple und useability and GUI.

Btw, to make the situation even more complicated, some german states (like Hessia and Rhineland-Palatinate) just dropped the 15 km rule…

**Comment by nrenner** [comment]
> some german states (like Hessia and Rhineland-Palatinate) just dropped the 15 km rule…

Thanks for the info, I updated Hessia [in the wiki](https://github.com/nrenner/brouter-web/wiki/%5Bde%5D-Corona-Bewegungseinschr%C3%A4nkung-15-km). For [Rhineland-Palatinate](https://github.com/nrenner/brouter-web/wiki/%5Bde%5D-Corona-Bewegungseinschr%C3%A4nkung-15-km#rheinland-pfalz) I haven't found a mention in the new regulation either, do you have a source? Somehow I missed this in the news, even though I'm also following the spiegel.de Corona-News.

But generally this doesn't affect the code, it doesn't tell you if the rule applies or not, it only implements the different definitions of the rule.

**Comment by Negativland** [comment]
I've bookmarked https://www.bundesregierung.de/breg-de/themen/coronavirus/corona-bundeslaender-1745198 as a directory to the corona rules of the states.

[Hessia](https://www.hessen.de/fuer-buerger/corona-hessen/fragen-und-antworten-zu-den-wichtigsten-regelungen) clearly says that the 15 km rule was dropped. [RLP](https://corona.rlp.de/de/aktuelles/corona-regeln-im-ueberblick/) just does not mention that rule any more; from that I conclude that they've also dropped that rule.

I don't know if other states also dropped the rule. In these times I don't cycle further than RLP…

**Comment by nrenner** [comment]
Thanks.
