### ISSUE TITLE
communicate lack of elevation data

### ISSUE THREAD

**Issue by phi-gamma** [nrenner/brouter-web#365]
Latitudes north of 60° seem to have elevation data only between 10° and 30°
east. [0] Which is not you guys’ fault but still a bit frustrating when
planning a trip.

It would be great if the lack of elevation data were indicated somehow. Perhaps
a message could be displayed in the corner of the screen or on the altitude plot.
As it is, it looks rather like a bug in the application itself.

Thanks to @bagage on IRC for nudging me here.

[0] Examples for that boundary:

- bottom 60° N: http://brouter.de/brouter-web/#map=16/59.9985/9.2634/OpenTopoMap,Waymarked_Trails-Cycling&lonlats=9.264672,60.001142;9.266518,59.99742&profile=fastbike
- left 10° E: http://brouter.de/brouter-web/#map=16/60.2772/9.9975/OpenTopoMap,Waymarked_Trails-Cycling&lonlats=9.996827,60.278494;10.007688,60.277739&profile=fastbike
- right 30° E: http://brouter.de/brouter-web/#map=15/69.4232/30.9871/OpenTopoMap,Waymarked_Trails-Cycling&lonlats=31.005484,69.430062;30.96908,69.422591&profile=fastbike

**Comment by bagage** [comment]
Thanks @phi-gamma for the issue! There's also https://github.com/nrenner/brouter-web/issues/203 for extra information about the missing elevation data.
