### ISSUE TITLE
Is it possible to get help to create a new pull request?

### ISSUE THREAD

**Issue by EssBee59** [nrenner/brouter-web#368]
Hello,
I would like to create new pull requests (for #356 and #332), but I am not familar with the branch/fork and pull technologies....
Is it possible to get help? (or better, someone creates the pull reqests directly!) 
My changes are already well tested, a documentation is also availlable. 
Regards
Ess Bee

**Comment by mjaschen** [comment]
Hi!

did you make your changes on a cloned Git repository of brouter-web?

**Comment by bagage** [comment]
Hi @EssBee59, the procedure should be:

1. Click on `Fork button` on https://github.com/nrenner/brouter-web/ page: 
![image](https://user-images.githubusercontent.com/1451988/107803860-7a8a3580-6d63-11eb-91f6-d3974fef9bb1.png)
2. Then clone your repository locally with: `git clone git@github.com:EssBee59/brouter-web.git`
3. Modify the code as you wish.
4. Commit with it with a brief explanation of the changes: `git commit -am "Improve voice hint generation. Fix #356"` for instance.
5. Push it: `git push`
6. Create a pull request by opening https://github.com/nrenner/brouter-web/compare/master...EssBee59:master

And voilà!

**Comment by EssBee59** [comment]
As I am not familiar with repositories I have a local installation on my PC.
So I make the changes locally, and test locally first.
When the tests are succesfull, I install the "dist"  on an instance of brouter.de (brouter.de/essbee)
The changes are documented in both issues, by need I can deliver more documentation
Thank for your help and regards
Ess Bee

**Comment by mjaschen** [comment]
Maybe it's easiest to create an archive of your local BRouter installation and provide it as download or send it as mail attachment so that someone else can integrate the patches and create the pull-requests. I've some time tomorrow and would take a look if it's ok with you.

**Comment by EssBee59** [comment]
mjaschen,
Thank for your proposal, that I liked to accept!!
Please send me a mail addrees where I can send my changes 
Reagrds
Ess bee

**Comment by mjaschen** [comment]
mjaschen@gmail.com should work :-)

**Comment by EssBee59** [comment]
Thank´s all for your help!

**Comment by nrenner** [comment]
Some more information:

GitHub used to have nice, short step-by-step guides that I can't find anymore. They seem to have rewritten the docs, and now I fear this is too much for starting:
[Collaborating with issues and pull requests - GitHub Docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests)

From a quick search this seems to be a nice guide:
[How to make your first pull request on GitHub](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)

There is also GitHub Desktop if you prefer using a UI over command line  (Windows and MacOS, also as [Linux Fork](https://github.com/shiftkey/desktop)):

1. [Setting up GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/setting-up-github-desktop) and Git
2. [Cloning and forking repositories from GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop#forking-a-repository)
3. [Committing and reviewing changes to your project](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/committing-and-reviewing-changes-to-your-project)
4. [Pushing changes to GitHub](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/pushing-changes-to-github)
5. [Creating an issue or pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request#creating-a-pull-request) (missing!?)
