### ISSUE TITLE
Total length in meter

### ISSUE THREAD

**Issue by jotpe** [nrenner/brouter-web#38]
When comparing different routes, it would be helpful, if the user could see the distance in meter (maybe as tooltip?)

**Comment by poutnikl** [comment]
But Brouter web already displays the distance on the left, if you mean the total one.

**Comment by jotpe** [comment]
Actual it is ```Length: 24.6 km```,
but ```Length: 24.699 km``` would be more precise.

**Comment by poutnikl** [comment]
Well, are you aware that referring the route length  by 5 valid digit precission 
is nonsense in mathematical and physical point of view, 
when the accuracy is much worse ?

**Comment by jotpe** [comment]
I am sorry, but I think your answer is not constructive.

But I can explain it in other words.
It would be helpful to see the distance in meter. For example route one is ```24699 m``` and route two ```24695 m```. Right now you cannot see such small differences. This would help to determine, if costs in total are higher because of a longer way or a more "difficult" way.

**Comment by poutnikl** [comment]
Why do you think it is not constructive ?  

if there is one value 24699 +/- 200 and the other 24695 +/- 200, the difference 4 is statistically insignificant.

**Comment by nrenner** [comment]
I missed a more precise format when comparing short walking distances myself. But I would like to keep the short formatting as it is easier to read and usually precise enough.

One idea was to show more digits when the length is lower than 10 km, but that wouldn't help with your example of 24.6 km and using multiple formats might be confusing.

Using a tooltip might be an idea but is not ideal as you can't see both values at once when comparing using two windows. Maybe switching formats on click might be an idea.

**Comment by jotpe** [comment]
I'm fine with a tooltip.

**Comment by jotpe** [comment]
Thanks.
