### ISSUE TITLE
Mean Costfactor

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#39]
I think, that it could be useful to display the mean route costfactor = total cost / length, instead of, or rather in parallel to the currently displayed total cost. 

In context of profile preferences,

the Total cost is an extensive, length dependent parameter, an absolute measure of route optimality, if a user modifies the routing by alternatives, nogos or viapoint. But is say nothing about the route quality in profile context, unless related to the length.

While the Mean costfactor is an intensive, length independent parameter, a measure of route quality, according to profile preferences. Note that it is not exactly the mean costfactor, rather effective mean cosfator, as uphill/downhill cost is involved as well,

**Comment by poutnikl** [comment]
E.g. 
route A has length 50 km, cost 60000, therefore mean costfactor 1.2
route B has length 35 km, cost 55000, therefore mean costfactor 1.57

Most users are  choosing  lower total route cost and Route B,
but some are choosing lower mean costfactor and Route A, voting for. longer, more demanding route with selections of more pleasant ways..

**Comment by nrenner** [comment]
Sounds like a good idea.

I just fear that the difference will not always be that clear as in your example and with costs converging towards 1 without an upper boundary will not be as meaningful and intuitive as usual ratings. But will need to test with some read world examples.

**Comment by poutnikl** [comment]
I agree differences will be smaller, I intentionally chose big one. But I do not much understand your reasoning , the mean cost/length seldom converges to 1, it is typically for me 1.5-2.

The optimal way boosting can be managed  in profiles as well, by 
costfactor = rawcostfactor . X - (X-1 )  , X >= 1

But i had in mind rather regular users, to be able to check it on the web

**Comment by jotpe** [comment]
Good idea!
