### ISSUE TITLE
Geocoder input collapses right after expand on mobile

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#393]
When tapping on the search icon on mobile, the input field is shown, which triggers the the phone keyboard to open. Right after that, the seach input disappears again. Only when long tapping, the input remains.

The reduced screen size by the keyboard causes the left buttons to wrap, but commenting out the [toolbar wrapping](https://github.com/nrenner/brouter-web/blob/fbcfd8cf8e2e8a0f44b1fe1432ccbe6db35a06a7/css/style.css#L57-L66) doesn't help.

Tested on Android with Samsung Galaxy and the latest Leaflet Control Geocoder version 2.2.0. First reported by @Phyks.

Can somebody please have a look, I would like to continue with #68.

**Comment by bagage** [comment]
I'll take a look at it if nobody is interested in the week-end.

**Comment by mjaschen** [comment]
I don't have the time to take a look at the moment but maybe the following findings are of some use:

- ✅ works as expected on iOS (iPhone X, latest iOS 14)
- ✅ works as expected in Chrome @ Android (Nokia 8, Android 9)
- ✅ works as expected in Edge @ Android (Nokia 8, Android 9)
- 🚫 fails as described by @nrenner in Firefox and Firefox Nightly @ Android (Nokia 8, Android 9)

A workaround is long-tapping as @nrenner mentioned or by tapping and short swiping to the right (into the input field area).

**Comment by nrenner** [comment]
> fails as described by @nrenner in Firefox and Firefox Nightly @ Android (Nokia 8, Android 9)

Forgot to mention that I only tested in Firefox.
