### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by CoolsoftComputing** [nrenner/brouter-web#400]
Hello
sometimes the tracks (paths) are not shown on the map, it would take an option to force a straight line.
![123](https://user-images.githubusercontent.com/54242137/115135492-2c223d00-a019-11eb-82a9-8bc3327821c7.png)

**Comment by nrenner** [comment]
Existing, proper paths that are missing in the map can be added to [OpenStreetMap](https://www.openstreetmap.org).

A straight line feature is in the works, see #68.

**Comment by CoolsoftComputing** [comment]
I changed it under OpenstreetMap, and saw talks about this problem.  Maybe put 2 waypoint and link it simply. 
thanks a lot for you quit reply.
Benoit
