### ISSUE TITLE
brouter.damsy.net : "Strava segments" not working

### ISSUE THREAD

**Issue by robobobeng** [nrenner/brouter-web#401]
The "Strava segments" feature on the Damsy.net instance of BRouter-web is not working.

Protocol:

1. Open https://brouter.damsy.net/latest and tick the "Strava segments" checkbox
![image](https://user-images.githubusercontent.com/41967635/115688467-7c700680-a35b-11eb-9fbb-02726c06ff0c.png)

2. Zoom in to a level of zoom greater than or equal to 13 (e.g. https://brouter.damsy.net/latest/#map=14). The "Strava segments" buttons on the left-hand side of the window should be now ungreyed:
![image](https://user-images.githubusercontent.com/41967635/115688999-f4d6c780-a35b-11eb-9c51-b6e4047e943c.png)

3. Click on either of these buttons. This results in a Strava API Error : 
`Impossible d'afficher les segments Strava : {"message":"Authorization Error","errors":[{"resource":"Application","field":"","code":"invalid"}]}`
![image](https://user-images.githubusercontent.com/41967635/115689119-10da6900-a35c-11eb-9dd2-4404b18b42fa.png)

**Comment by robobobeng** [comment]
@bagage is this feature an outdated one?

**Comment by bagage** [comment]
No, thanks for reporting it, it should be fixed now though this is outside of brouter codebase and I should handle api key renewal better!

**Comment by nrenner** [comment]
Is this related to [leaflet.stravasegments#4](https://gitlab.com/bagage/leaflet.stravasegments/-/issues/4)? I couln't get it to work back then.
