### ISSUE TITLE
Add Swisstopo (Swiss Map Raster or Vector) baselayer

### ISSUE THREAD

**Issue by fidelius-dc** [nrenner/brouter-web#402]
Hello,

As all Swisstopo maps are freely available now, it would be great to add them to the layer selection. In WMS they were alredy available for a long time. It would be a huge advantage for planning in Switzerland.

https://www.swisstopo.admin.ch/en/swisstopo/free-geodata.html#189_1614237763665

**Comment by nrenner** [comment]
The link is more about downloading raw geo data? What do you have in mind specifically?

The only layer types we support right now, is the OSM png tile schema or compatible WMTS layers.

**Comment by fidelius-dc** [comment]
Ok, I see. brouter uses wmts, and I figured out that i need to add

https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg

as custom baselayer. THANKS.

I think it would be a good idea to add this to the extended list of baselayers for Switzerland.

Further documentation on the swisstopo WMTS here: http://api3.geo.admin.ch/services/sdiservices.html#wmts
Thanks a lot!

**Comment by phylor** [comment]
For all googlers: the following link can be used to add aerial photographs from Swisstopo. Quite useful, e.g. to figure out what type of road it is.

https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg

**Comment by nrenner** [comment]
> https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg

Generally I'm a bit unsure about adding non-OSM maps, as it might cause confusion when the route and the map don't match and it is a bit at odds with promoting OSM.

But there seems to be a demand for it, so I don't want to be too restrictive either.

**Comment by fidelius-dc** [comment]
Hi, I fully understand your concerns - Brouter made me an OSM contributor in the first place! 

But as it's hidden in the additional layers I consider it as the same like TopPlusOpen. It's rather for the advanced user, that sould be able to figure out, that routing is based on OSM and understand that you'll run into inconsistencies using these maps.

Thanks you

**Comment by fidelius-dc** [comment]
as there is #422 now, I guess we can close this
