### ISSUE TITLE
Export track with name that contains Cyrillic symbols

### ISSUE THREAD

**Issue by korzhyk** [nrenner/brouter-web#404]
Hello everyone,

I several times faced with problem when try to export track and always downloading file with name like ` - 40km.gpx`. I see an warning about filename sanitization regex, but also I know about there some problems with Cyrillic in RegEx due to use a lot of unicode range.
Also I find the line that this regex must be in sync with server one.
https://github.com/nrenner/brouter-web/blob/5c70e30c1376f609992218bc499bc86f90982f52/config.template.js#L128-L129

So what is the best way to resolve this issue?

Can we just add some unicode space in regex, ex.: https://regexr.com/5s97r

**Comment by rkflx** [comment]
Hi,

thanks for your report. The way filenames are handled has changed recently, see 7aa2fcb9 (change not deployed to production yet, though). We now rely on the browser to remove restricted characters from the filename, which should finally allow sensible filenames beyond ASCII again, not only for Cyrillic.

I got a chance to perform some tests with an Edge 810 last week, will add more comments later. Feel free to test with your devices/apps too, in particular of interest would be:
- Which device/app are you using?
- Use **trackname** with unicode characters you'd like to use: Does it crash your device/app when importing the GPX? Is everything displayed correctly?
- Rename file to use unicode characters in **filename**: Can you copy the file from where you saved it to the target device? Is it listed there? Does it crash when importing?

See also #194, #202, #269.

**Comment by korzhyk** [comment]
Hello,

 I just got feedback from my «bicycle» friends, they using a lot of garmin, wahoo, lezyne and bryton. And only Bryton has issues with special/cyrillic characters in filename.

As for me, I'm using Lezyne with official mobile app and no any issues with cyrillic wasn't found.

**Comment by nrenner** [comment]
Should now be supported by client-side formatting (#399) and download (7aa2fcb) and is already online.

The RegEx is no longer in use for that, as now the browser takes care of both the filename and proper encoding for XML and JSON.
