### ISSUE TITLE
"operation killed by thread-priority-watchdog" error even for very short routes

### ISSUE THREAD

**Issue by robobobeng** [nrenner/brouter-web#423]
BRouter-web has been throwing the "operation killed by thread-priority-watchdog" error a lot of times these last 2 days, on both instances http://brouter.de/brouter-web and https://brouter.damsy.net/latest.

I have tried calculating very short routes (less than 2 km long) both with the standard trekking profile and the fastbike profile. I have tried changing my web browser (I tried with Google Chrome and with Mozilla Firefox), and I tried from several devices (one laptop and one smartphone).

Is there a problem with the routing engine itself?

**Comment by mjaschen** [comment]
Can you provide a link to the planned route?

Maybe I'm able to take reproduce the described behavior on my BRouter-Web instance and take a closer look into the BRouter server log.

**Comment by robobobeng** [comment]
The issue does not seem to be reproducible this morning, which is good news.

**Comment by nrenner** [comment]
See [brouter.de under heavy load from china robots](https://groups.google.com/g/osm-android-bikerouting/c/ZuSYKkVN6mc/m/N9niJAvtBQAJ).
