### ISSUE TITLE
Update the backend BRouter to latest 1.4.2 release

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#43]
Brouter-web with older BRouter 1.4.1 is not compatible with updated syntax of the latest BRouter release 1.4.2, if a profile uses recently implemented operators like e.g. SUB or LESSER.

It would be good to get the BRouter updated.

**Comment by nrenner** [comment]
Do you mean the [Readme](https://github.com/nrenner/brouter-web/blob/master/README.md#installation) description or the hosted http://brouter.de/brouter-web instance?

**Comment by nrenner** [comment]
Ah, I see, exported GPX from brouter.de online service still says ``creator="BRouter-1.4"``, current code has ``creator="BRouter-1.4.2"``.

@abrensch is providing the backend hosting and would need to do the update.

**Comment by poutnikl** [comment]
I am sorry, I have thought it was clear.
Tthe latter, Brouter-Web interface. 

As it refuses profiles with new syntax. I had to replace "Sub A B"  by a workaround "Add A multiply -1 B"

**Comment by poutnikl** [comment]
I am sorry, I have thought it was clear.
Tthe latter, Brouter-Web interface. 

As it refuses profiles with new syntax. I had to replace "Sub A B"  by a workaround "Add A multiply -1 B"

**Comment by poutnikl** [comment]
I have raised the request on Brouter Google group as well.

**Comment by nrenner** [comment]
Seems to be updated now.
