### ISSUE TITLE
Info flag is drawn behind route

### ISSUE THREAD

**Issue by tilmanb** [nrenner/brouter-web#431]
The information element that appears on mouseover on the route is displaying behind the route. See the attached screenshot for details.

![grafik](https://user-images.githubusercontent.com/779297/122909709-c1adb600-d355-11eb-9934-11dd9857189d.png)

Route is here https://brouter.de/brouter-web/#map=14/52.0727/9.9091/standard,route-quality&lonlats=9.90057,52.065103;9.909067,52.084148 .

**Comment by rkflx** [comment]
Thanks for the report! You might have missed #408 when searching for existing issues, though ;)

Feel free to close the issue (which apparently I am not allowed to do, along with adding a "duplicate" label...).
