### ISSUE TITLE
[Feature request] Turning directions

### ISSUE THREAD

**Issue by OgreTransporter** [nrenner/brouter-web#436]
It would be great if you could automatically add turn-by-turn directions as waypoints when downloading. This simplifies the navigation, because e.g. Oruxmaps reads out these hints during the WP navigation. Therefore, you do not need to have the map constantly in view.

**Comment by vodie** [comment]
You can add turn-by-turn direction if you set the right turnInstructionMode:
![_20210704_165053](https://user-images.githubusercontent.com/45155869/124389700-94172400-dce8-11eb-950a-29729e558cfa.JPG)

**Comment by OgreTransporter** [comment]
Thank you very much! I have not seen this option.
