### ISSUE TITLE
Use cycleway:surface for surface statistics

### ISSUE THREAD

**Issue by theraser** [nrenner/brouter-web#438]
Since cycleway:surface and footway:surface are getting more and more popular and are already supported by BRouter (see https://github.com/abrensch/brouter/issues/131 for details) it would be nice to use these tags for calculating the surface statistics.

Example: https://brouter.de/brouter-web/#map=17/50.13421/8.69458/standard&lonlats=8.696172,50.135486;8.694914,50.13251

Both footway and cycleway got a surface-tag (see https://www.openstreetmap.org/way/849709593) and if you use a profile which uses these tags it will show up at the data details tab - but it's counted as "Unknown" at the "Analyse route" tab:

<img src="https://user-images.githubusercontent.com/7988080/124825272-b4a6de80-df73-11eb-97a9-3a4b39e98a00.png" width="600">

<img src="https://user-images.githubusercontent.com/7988080/124825285-b83a6580-df73-11eb-9815-680ce3761a2d.png" width="600">

This just got me because I wondered why there are **so many** "Unknown" surfaces at some routes :smiley:

**Comment by mjaschen** [comment]
If anyone is interested in testing the fix – I pushed it to bikerouter.de:

Example: https://bikerouter.de/#map=17/50.13421/8.69459/standard&lonlats=8.696172,50.135486;8.694914,50.13251

**Comment by theraser** [comment]
Looks awesome, thanks a lot! Tested a few more bicycle tracks (different tagging styles), all worked as expected.

**Comment by pkubowicz** [comment]
This isn't correctly fixed. [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:cycleway:surface) suggests tagging like:
```
surface=paved
cycleway:surface=asphalt
footway:surface=paving_stones
```
I think it's bad advice (you won't find a square centimeter with 'paved' in the terrain, all is either asphalt or paving stones, there aren't 3 types of surface). But unfortunately people tag this way, so routing should support it.

Today, BRouter says cycling along such a way is 100% paved ([example](http://brouter.de/brouter-web/#map=19/50.03149/19.91601/standard,Waymarked_Trails-Cycling&lonlats=19.916486,50.031549;19.916118,50.031418)). But it should say it's 100% asphalt.

The code from 9ca93e4 is unclear in ordering of tags, so I don't know if the order is random, or something else sorts tags.

**Comment by quaelnix** [comment]
Here is an example: https://brouter.de/brouter-web/#map=16/51.7907/11.3052/standard,route-quality&lonlats=11.311067,51.78809;11.307776,51.796078 where the current aliasing method does not produce the correct result even if `processUnusedTags` is enabled.
