### ISSUE TITLE
Black bar when hillshading is active

### ISSUE THREAD

**Issue by samarutuk** [nrenner/brouter-web#440]
When hillshading is active, a black bar (perhaps the white sausage equator known from legends?) always appears in my region:
![grafik](https://user-images.githubusercontent.com/46650176/126131361-e2fe4cdf-0d05-4d5a-be40-264e2f64b089.png)

It also appears on the hikeandbike.org map, from which the hillshading originates, i.e. it is not really a brouter issue. However, it is not beautiful and it is surprising that no one has noticed it. I'll try to contact the makers of the hikeandbike.org map, maybe they can fix the bug. If it concerns someone, the best solution is to choose a map that already offers hillshading, e.g. CyclOSM.

**Comment by nrenner** [comment]
The hikeandbike hillshading layer is not available anymore (#475), so we switched to a different one recently.
