### ISSUE TITLE
Allow loops

### ISSUE THREAD

**Issue by ZettaScript** [nrenner/brouter-web#442]
The map is also useful when planning a bike trip for sport (not going from A to B, but from A to A), but this use is made difficult because the software is optimized for finding the best way from A to B, which is not always the thing we want.

Currently if I want to make a loop, I can't because clicking on the selected path or on a point does not add a point.

It would be great to have a "distance" range parameter, then you just have to place a start point a optionally other points, then the engine finds a loop going from the start point and ending at the start point.

This behavior could be enabled via a "loop" option in settings.

I don't know whether the engine allows this.

**Comment by bagage** [comment]
That's something that is indeed regularly wished, you can upvote #236 to increase the chance for someone to pick it up :).
