### ISSUE TITLE
Ampersand (&) in point of interest prevents proper POI export to GPX

### ISSUE THREAD

**Issue by ghost** [nrenner/brouter-web#446]
When a point of interest (POI) is added with an ampersand (`&`) in the name, upon export any text after the `&` as well as any POI created after the POI with the `&`.
(It's possible this happens with other characters that XML doesn't like, though I haven't tried.)

Example: GPX export for the following link
https://brouter.de/brouter-web/#map=5/51.124/0.615/standard&lonlats=6.788006,51.43705;6.789722,51.434749&pois=-2.021484,51.890297,foobar;6.943359,51.096855,foo%26bar;14.72168,51.234641,foobar2

In browser there are 3 POI (`foobar`, `foo&bar`, `foobar2`), but in the GPX file exported I see only
```xml
<gpx ...>
 <wpt lon="-2.021484" lat="51.890297">
  <name>foobar</name>
 </wpt>
 <wpt lon="6.943359" lat="51.096855">
  <name>foo</name>
 </wpt>
 <trk>
...
```

**Comment by mjaschen** [comment]
Hi,

I tried it myself at [bikerouter.de](https://bikerouter.de) and get the following:

URL: https://bikerouter.de/#map=5/51.124/0.615/standard&lonlats=6.788006,51.43705;6.789722,51.434749&pois=-2.021484,51.890297,foobar;6.943359,51.096855,foo%26bar;14.72168,51.234641,foobar2

GPX export result:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- track-length = 290 filtered ascend = 2 plain-ascend = 2 cost=721 energy=0.0kwh time=47s -->
<gpx 
 xmlns="http://www.topografix.com/GPX/1/1" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" 
 version="1.1" 
 creator="BRouter-Web 2021.32">
 <wpt lat="51.890297" lon="-2.021484"><name>foobar</name></wpt>
 <wpt lat="51.096855" lon="6.943359"><name>foo&amp;bar</name></wpt>
 <wpt lat="51.234641" lon="14.72168"><name>foobar2</name></wpt>
 <trk>
  <name>Duisburg-Mitte (0,3 km)</name>
  <trkseg>
   <trkpt lat="51.43703" lon="6.78802"><ele>38.5</ele></trkpt>
   <trkpt lat="51.437057" lon="6.788105"><ele>38.75</ele></trkpt>
   <trkpt lat="51.436876" lon="6.788265"><ele>39.25</ele></trkpt>
   <trkpt lat="51.435929" lon="6.788911"><ele>39</ele></trkpt>
   <trkpt lat="51.435067" lon="6.789491"><ele>40.25</ele></trkpt>
   <trkpt lat="51.434745" lon="6.789709"><ele>40.5</ele></trkpt>
  </trkseg>
 </trk>
</gpx>
```

The `&` is escaped correctly. 

@nrenner implemented [escaping of XML data](https://github.com/abrensch/brouter/commit/f59cbbb5adcd012e180e139aa03665ff840f4fb4) data some time ago in the BRouter server part and it works as the result above shows (POI names are escaped [here](https://github.com/abrensch/brouter/blob/5510eac7ec73f1f900b22c41fff40cac5c5a678e/brouter-core/src/main/java/btools/router/OsmTrack.java#L545)).

My guess is, that brouter.de runs an older version of the BRouter server where that fix is missing. Maybe @abrensch can bring some light to the dark …

**Comment by nrenner** [comment]
The updated server is still showing the behaviour. Might also be some parameter splitting issue, although the name is escaped in the server URL.

Anyway, we now do formatting in client, which relies on automatic escaping by the browser XML APIs, so this is fixed now for brouter-web.
