### ISSUE TITLE
Adding customisable maximum allowed radius globally

### ISSUE THREAD

**Issue by jgOhYeah** [nrenner/brouter-web#450]
Hello,
Firstly, thanks to everyone who has worked on this project. It is by far the best mapping and route planning system I have come across for bikes.

I see that support has been added for certain countries to have an allowed radius / area for pandemic restrictions. Would it be possible to make the allowed radius feature available globally with a circle of selectable size?

I live in Australia and the rules regarding lockdowns change pretty regularly with little notice. Generally they involve a radius limit ranging from 2.5km to 20km from your home for excercise. The rules in NSW are slightly different, being in the same local government area that you live in or a 5km radius, however I think a circle with customisable center point and radius would be simpler to implement and more widely usable.

I am happy to have a go at implementing something, but I haven't got too much experience with nodejs and docker. Any input / suggestions, existing solutions or reasons to not do this would be appreciated :).
Thanks

**Comment by jgOhYeah** [comment]
It has taken me a while to get around to it and the way most of the world seems to be heading, the need for this feature seems to be getting less urgent, however I have had an attempt at making the radius limit usable outside France and Germany.

Currently, the radius defaults to 10km and can be adjusted by clicking on the marker in the middle and using the number entry box as shown in the included short video - most things for this to happen were already implemented. Is there a better / preferred method of setting the radius? I note that the no go area tool uses a draggable point to resize it, however I am not sure this would be precise enough in the context of (hopefully not required again) restrictions and lockdowns. The number entry box is also the easiest method I could think of to implement :).

I am unsure however what the best approach to the behaviour of this tool should be in Germany. Currently, it limits the area to the current state + a user settable radius. Should this be left as is, brought back in line with the rest of the world to just have a circle around a point or a menu added to change between the two?

I don't have a publicly available server to demonstrate at the moment, but I am working in [this fork/branch](https://github.com/jgOhYeah/brouter-web/tree/worldwide_limited_go)

https://user-images.githubusercontent.com/33143109/152717159-b2e5d741-2cdc-4569-aa5b-26fe9473ec16.mp4

.

**Comment by nrenner** [comment]
Looks like a nice addition.

I already thought about either removing that feature altogether or how to make it more generally useful, not sure there is a use case though.

I haven't heard of any area restrictions in Germany this winter, so I think we can remove or comment out the country-specific parts.

**Comment by jgOhYeah** [comment]
I think for most users it would probably not be as relevant anymore, although there are still a few countries that are in or haven't ruled out restrictions for the virus (China and various Pacific Island countries including Tonga spring to mind) - not sure if they have a radius limit though.

As a hypothetical scenario, it might be useful for cycling obsessed bank robbers under house arrest or on certain bail conditions, although not sure if that would ever happen :).

Up to you whether it stays or goes. Git history can always bring it back if it is (hopefully never) needed again.

**Comment by nrenner** [comment]
Still not sure what to do with the go-to zone feature, some thoughts:
- I would definitely remove the state-based part for Germany and keep it in an archive branch or tag
- the toolbar button should be less prominent, depending on #498 
  - or no button, but drawing a no-go area first, then have some way to invert it into a go-to zone
- or removing the feature altogether and archiving it as branch or tag

In any way, feel free to submit a PR, so it would at least be archived with the rest.

@bagage what do you think?

**Comment by bagage** [comment]
Hard to say if there are valid use cases for it now: for me it's fine to archive that feature completely :) otherwise I think it should be reworked to be less visible I agree

**Comment by mjaschen** [comment]
> or removing the feature altogether and archiving it as branch or tag

+1

**Comment by jgOhYeah** [comment]
Agree with the thinking of this feature no longer having much of a valid use case and it can be removed. I personally haven't used it or wished for it for the last while. I will submit and close a pull request with the modifications I did back in February for archive purposes.
