### ISSUE TITLE
Default or/and last used for POI names

### ISSUE THREAD

**Issue by printpagestopdf** [nrenner/brouter-web#454]
I recognized, that in the last Version of brouter-web it is not longer possible to use an empty POI name. That is necessary, because brouter seems to produce errors, e.g. if this should be exported as gpx.

But sometimes it could be useful to add many POI's where names doesn't matter, only interested in marking the points.

So wouldn't i make sense to preset the POI name input? As an approach use the previous entered value and if there isn't one then a default e.g. POI.

So it would be easy to fast add a large amount of POI's and not violating the non empty name rule?

**Comment by printpagestopdf** [comment]
For me, a prefilled entry in the POI dlg makes it more usable, the change was very small (for real perhaps the default should be a config value):

@@ -1,6 +1,7 @@
 BR.PoiMarkers = L.Control.extend({
     markersLayer: null,
     circlego: null,
+	lastPOIname: "POI",
 
     options: {
         shortcut: {
@@ -84,8 +85,10 @@ BR.PoiMarkers = L.Control.extend({
         bootbox.prompt({
             title: i18next.t('map.enter-poi-name'),
             required: true,
-            callback: function (result) {
+			value: this.lastPOIname?this.lastPOIname:"POI",
+            callback:  (result) => {
                 if (result !== null) {
+					this.lastPOIname=result;
                     self.addMarker(e.latlng, result);
                 }
             },

**Comment by nrenner** [comment]
Empty names will be allowed again, as they are supported by client-side formatting. So no need for default names.
