### ISSUE TITLE
Escape key doesn't work with Safari

### ISSUE THREAD

**Issue by adaigre** [nrenner/brouter-web#459]
I'm using brouter-web on Safari 15.1 (macOS 11.6.1).
The escape key is useful for stopping route drawing, but it has no effect on Safari.

Works well with Firefox.

**Comment by mjaschen** [comment]
Hi,

I tried it on Monterey with all updates installed, it works for me. 

Safari Version 15.1 (17612.2.9.1.20)
macOS 12.0.1 (21A559)

**Comment by adaigre** [comment]
It was the Vimari extension who was blocking escape key usage... So no issue here.
Thanks for your work!
