### ISSUE TITLE
Add IGN France baselayers and overlays

### ISSUE THREAD

**Issue by sylvainavelo** [nrenner/brouter-web#463]
Hello,

Since summer 2021, IGN France web services are accessible without key (as it used to be for years).
Lists in french : https://geoservices.ign.fr/services-web-experts

I suggest to add baselayers such as aerial pictures, a base map and an overlay with administrative boundaries. All of those are WMTS tile layers compatible with brouter map display.

The idea comes from a french cyclist requesting a way to add french departments boundaries on BRouter, and using an IGN WMTS layer is a possible solution : https://twitter.com/sylvainavelo/status/1462853551139524615

It will be very much like what has been done for Swisstopo baselayers (#402).
I've seen and I understand the concern about adding non-OSM maps.

I'm working on the issue but will submit the PR only if it meets approval.

**Comment by nrenner** [comment]
What are the usage terms though? E.g. in Germany official maps are often open for private use but not for embedding in map services.

I don't see the use case or general demand for admin boundaries, so I would rather not want those.

**Comment by sylvainavelo** [comment]
Usage is free for any use, including commercial, under the terms of this license : https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf
Like a CC-BY, mentioning paternity is required.
And also the date of last update... But as it is a web service, I can't figure out how this can be achieved. It's probably a minor concern.

The license is clear for the data itself but it lacks information specific to web services. How much can you request the service ? (in terms of requests per minutes). I can't find. The Swiss give that information quite clearly [here](https://www.geo.admin.ch/de/geo-dienstleistungen/geodienste/terms-of-use.html) for instance. I will ask for details.

**Comment by nrenner** [comment]
> I will ask for details.

Have you asked?

Not sure that would help much, as we can't really tell or control what our usage would be.

**Comment by sylvainavelo** [comment]
Yes I asked and it took some time to have this answer. Sorry for the late follow up :

- They contact users individually when they have clues on how to find them if their usage is dangerous for their infrastructure.
- They block IPs if necessary but not automatically.
- On their current infrastructure, it is time consuming to track users that have an unfair usage.
- They are aware that in most cases, the client application has no mean to track unfair usage as well.
- Use in an application with 10 000 users a day would be fair use (I am surprised they said users per day and not a metric using the number of requests). That seems not very specific.

**Comment by nrenner** [comment]
> Use in an application with 10 000 users a day would be fair use 

Sounds like a lot, we probably won't reach that with a country-specific layer that needs to be configured.

What layers should we add? A recent [thread](https://groups.google.com/g/osm-android-bikerouting/c/VS47Fi1ijMQ/m/3aDtKQqOAQAJ) was about IGN Scan25 (requires a key) and IGN Plan25.

**Comment by sylvainavelo** [comment]
I pushed 2 base layers. That's actually an old thing I did when submitting the issue.

That's a start. I will later have a look at the Scan25 layer which is a lot richer than the one I added.

![image](https://user-images.githubusercontent.com/14272233/189740976-3c321045-633e-4c12-8201-108b3bf8b4c7.png)

![image](https://user-images.githubusercontent.com/14272233/189741074-94f6c7ac-d5d7-4ffe-842d-c55cffc5a2b9.png)

**Comment by nrenner** [comment]
I guess the Scan25 layer requires a key. Please provide instructions how to obtain one with a PR or send me a key with private mail.

You can prepare an empty entry in [keys.template.js](https://github.com/nrenner/brouter-web/blob/master/keys.template.js) and search for usage examples using the names there.

**Comment by nrenner** [comment]
I'm going to add short names for the map link, cause they're too long for mobile screens, would those be Ok:
- IGNF Photos
- IGNF Plan
- IGNF Topo

**Comment by sylvainavelo** [comment]
Yes, those are ok.
Sorry I didn't pay attention to the mobile look.

**Comment by nrenner** [comment]
No worries, very minor issue and only in combination with overlays.

I think we can close the issue?

**Comment by sylvainavelo** [comment]
Yes sure 👍
