### ISSUE TITLE
Bad routing on shortest/hiking profiles across restriction=no_right_turn + except=bicycle

### ISSUE THREAD

**Issue by joernheissler** [nrenner/brouter-web#469]
Hello,

https://brouter.de/brouter-web/#map=18/53.59353/9.96837/standard&lonlats=9.96667,53.593428;9.96652,53.593256&profile=shortest
https://www.openstreetmap.org/relation/3517068
![shortest-route](https://user-images.githubusercontent.com/865592/149098565-84f64242-3837-4b09-882c-7af4a91b45b1.png)

This used to work until recently. Was anything changed in the profiles?

**Comment by polyscias** [comment]
See the [patch of @vodie for brouter](https://github.com/abrensch/brouter/pull/392/commits/5f62723cbb5700f5a813a3fca2f20fdb5d4bc127).

This was changed indeed [changed](https://github.com/abrensch/brouter/issues/307) with the last release.

A good work-around for now is to change your foot profile:

    assign considerTurnRestrictions = true   # %considerTurnRestrictions% | Set to true to take turn restrictions into account | boolean

Change the true to false
