### ISSUE TITLE
Brouter web stopped working properly

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#47]
with default Trekking profile, the BR web allows me to set waypoints, but refuses to calculate even trivial ( short and simple ) routes. ( using latest PaleMoon Browser )

**Comment by nrenner** [comment]
Working for me, both in Firefox and PaleMoon on Ubuntu.

Any error message in BRouter-Web or in the Browser Console (Ctrl+Shift+K) (apart from the CSS parsing errors)?

**Comment by poutnikl** [comment]
Web provides no error msg, behaves just like calculating the route forever.
The console gives this

[20:40:55.238] SecurityError: The operation is insecure. @ http://brouter.de/brouter-web/dist/brouter-web.js:46
--
[20:41:10.700] TypeError: t is undefined @ http://brouter.de/brouter-web/dist/brouter-web.js:36

I have also noticed that the standard profile code, appearing in the left bottom window recently, is not displayed anymore.

**Comment by nrenner** [comment]
Can now reproduce in Pale Moon with Cookie setting Keep until: "ask me every time".
(Edit > Preferences > Privacy: 
History: "Use custom setting for history", [x] Accept cookies from sites)

Error occurs when accessing localStorage for transparency slider. I will need to handle that exception, therefore leaving this issue open.

As a workaround you can add "brouter.de" to "Exceptions..." or alter the Cookie/History settings.

Related links:
http://meyerweb.com/eric/thoughts/2012/04/25/firefox-failing-localstorage/
https://bugzilla.mozilla.org/show_bug.cgi?id=365772

**Comment by poutnikl** [comment]
I confirm it is cookie management related, as I had it set to Ask every time. when I changed it ti Until Expire, it has started working again.
