### ISSUE TITLE
Hillshading and Hike&Bike layers show tile "Contact [[User:TheDJ]] ..."

### ISSUE THREAD

**Issue by robobobeng** [nrenner/brouter-web#475]
Since today (2022-01-22), OSM tiles don't appear properly. Some appear, some don't, and some just replaced by the following message:

![image](https://user-images.githubusercontent.com/41967635/150646191-68417920-7db2-47a0-805e-1172d0c7dd7c.png)

Of course I tried to fix the issue by adding my own tiles, I tried the 4 following URLs : 
https://tile.openstreetmap.org/${z}/${x}/${y}.png
https://a.tile.openstreetmap.de/${z}/${x}/${y}.png
https://b.tile.openstreetmap.de/${z}/${x}/${y}.png
https://c.tile.openstreetmap.de/${z}/${x}/${y}.png

Any of them yields the same result.

**Comment by nrenner** [comment]
It's not the OSM tiles, but the hillshading overlay ("Relief avec ombre" in your case), click on the checkbox to deactivate.

The website of that layer is https://hikebikemap.org/ (see the link bottom right), but fails to load due to other errors.

We probably need to look for alternatives, but I'm not sure if there are any we can use.

**Comment by nrenner** [comment]
According to [this comment by TheDJ](https://phabricator.wikimedia.org/T187601#7642399), all tiles from **tiles.wmflabs.org** are not available anymore, unless someone volunteers to keep maintaining that server:

> FYI. I have now made tiles.wmflabs.org tiles return [a static image](https://tiles.wmflabs.org/osm/slippymap.html). I don't feel like dragging this thing on for another 4 years as it is not really something i enjoy. Especially with the unreliability of the OSM database sync for wmflabs and no one invested in fixing that either. This means the following:
>
> 1. Standard multilingual OSM mapnik tiles will no longer be available to the community. Use https://tile.openstreetmap.org/${z}/${x}/${y}.png instead
> 2. The hillshading tiles will not longer be available  (i know of no alternative)
> 3. The hikebike map that we were hosting will no longer be available
> 4. The OMS black and white and nolabels style will no longer be available
>
> If anyone is interested in taking it over, i'm willing to show you around the server. If no one volunteers, it will likely be deleted soon in the upcoming purge: https://wikitech.wikimedia.org/wiki/News/Cloud_VPS_2021_Purge

**Comment by HollyBoni2** [comment]
Any updates, is there any way to fix this issue? BRouter is my favourite route planner, and I always used OSM with hillshading. 😕

**Comment by nrenner** [comment]
I still hope the tile service will be resumed soon.

There are some comments in this Wikimedia task, from potential admins, maybe moving static hillshading tiles somewhere else and an ongoing database reload:
https://phabricator.wikimedia.org/T187601#7642399

**Comment by pou-lagah** [comment]
is the integration of the Hillshade function (arcgis) possible ?

https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/hillshade-function.htm

**Comment by nrenner** [comment]
Thanks for the suggestion, but I don't see how.

I had searched there for hillshading tile layers before, but hadn't found one that is meant as overlay, i.e. that is transparent in flat regions:
https://www.arcgis.com/home/search.html?q=hillshading

I do have other ideas but will need to check.

**Comment by HollyBoni2** [comment]
BTW I live in Hungary and I just discovered that there was a "Hillshade Hungary" option in the optional layers menu... Not sure what it is but it works. So happy!
![opkopk](https://user-images.githubusercontent.com/100024465/167153965-6dd73915-a5c4-4141-993c-3d5c20e91a65.PNG)

**Comment by nrenner** [comment]
The idea is to use Terrain Tiles from Open Data on AWS (Amazon Web Services):
https://registry.opendata.aws/terrain-tiles/

I haven't seen any specific usage terms, but it seems they can be used without a key.

The tiles contain raw DEM (Digital Elevation Model) data encoded as PNG. So they need to be rendered to hillshading dynamically in the Browser (e.g. using WebGL).

I guess the way forward for that would be to include [Maplibre GL JS](https://maplibre.org/projects/maplibre-gl-js/).

[Demo](https://norbertrenner.de/share/hillshading-gl-leaflet.html)

The Maplibre bundle is a quite big - almost five times the size of Leaflet (minified but not compressed):
- 690 KB [dist/maplibre-gl.js](https://yarnpkg.com/package/maplibre-gl?files)
- 141 KB [dist/leaflet.js](https://yarnpkg.com/package/leaflet?files)

So the idea is to only load Maplibre when the layer is actually used, using [Dynamic Imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports):

[Lazy loading demo](https://plnkr.co/edit/OP9WoZUqJHPCMq52?open=lib%2FMaplibreGlLazyLoader.js&preview) (filter devtools Network tab by `.js` and observe when activating the Hillshading overlay)

I'm working on a PR for that.
