### ISSUE TITLE
What are "segments" and how are they calculated?

### ISSUE THREAD

**Issue by robobobeng** [nrenner/brouter-web#481]
For a few months, the elevation profile has been divided into a succession of segments of differents colors (the color depends on the average slope of the segment).

But more recently, the segment length is explicitly displayed when hovering the mouse over the segment:
![image](https://user-images.githubusercontent.com/41967635/155322270-4b98444c-f423-45bc-81c5-39977bfe4f94.png)

Which leads me to the question: how exactly is one route divided into segments? How are they really computed?

**Comment by nrenner** [comment]
I don't know the details myself, I think the segments are computed in the [geo-data-exchange](https://github.com/alexcojocaru/geo-data-exchange/#geo-data-exchange) lib, see description and source code there.

See also original PR #345 and discussion in #416.
