### ISSUE TITLE
English placenames

### ISSUE THREAD

**Issue by thany** [nrenner/brouter-web#483]
Take a look at any country where you can't understand their letters. Wouldn't it be much more helpful if it would show romanised/anglisised placenames? This data is available in OSM for the most part.

Example:
![image](https://user-images.githubusercontent.com/152227/159366729-a8196eb5-abd1-43d1-b9ce-bc53ee5773a6.png)

Good luck finding anything 😬

**Comment by mjaschen** [comment]
You can select other map styles in the layers tab, some of them show transliterations for local names, e.g. OpenStreetMap.de:

![](https://docs.google.com/uc?id=10UVDDEQ_R00anKnGybuDgH5Y7wjw0soj)

**Comment by thany** [comment]
Oh I see, very nice. I never selected that one, because in my head it indicated it was going to be German, which I'm sadly not very good at.

Thanks for following up.
