### ISSUE TITLE
Multiple legs

### ISSUE THREAD

**Issue by thany** [nrenner/brouter-web#487]
Would be immensely helpful if it were possible to create a route that consists of multiple legs.

In case you don't use the same means of transportation for the entire route, which is entirely sensible, you would have to switch profiles mid-route, which of course is not possible. Also the point that ends one leg, and starts the next leg, might not be on the *exact* same location (like when switching from train to car).

So essentially the feature request is to be able to create multiple routes, and export them to a single file.

(and yes, I know merging them is dead simple, but a LOT of mapping things are dead simple, but lots of simple steps do not always result in a simple overall process).

**Comment by mjaschen** [comment]
I think this is a duplicate, see #430

**Comment by thany** [comment]
Yes, that one most likely covers my use case. Thanks for following up though.
