### ISSUE TITLE
Hiking route is unneccesarily avoiding a road

### ISSUE THREAD

**Issue by thany** [nrenner/brouter-web#489]
Hiking is avoiding this road for some reason. Doesn't make much sense to me, for two reasons:

1. In Japan ALL non-expressways are legally walkable, with or without a sidewalk.
2. This is a road with perfectly usable sidewalks, as is even indicated on the map itself. See screenshot.

![image](https://user-images.githubusercontent.com/152227/160260425-584b4e37-ffd3-4f8d-8423-9c4584bb5eba.png)

The fact that it's also entirely ignoring the underpass at the road crossing near the end, is forgivable as it doesn't appear to be on the map. Unnecesary detours, however, are a lot more difficult to deal with to get a good route.

http://brouter.de/brouter-web/#map=18/33.27918/131.50377/standard&lonlats=131.500482,33.279566;131.506906,33.279319&profile=hiking-beta

**Comment by mjaschen** [comment]
Such details are entirely in the responsibility of the used routing profile. You may want to take a look in the profile's repository: https://github.com/poutnikl/Brouter-profiles

**Comment by thany** [comment]
Is that confirming it needs a fix? Or I don't know what you're trying to tell me exactly...

Either way, I'm sure there's something in the profile that causes this issue, but I have never seen that language. I can only blindly try stuff, but I can't hope to make a proper fix.

**Comment by mjaschen** [comment]
I don't think a fix is needed.

The example shows a regional speciality which could be taken into account with a special routing profile. At least it's nothing that should apply globally, IMHO.

No matter how you slice it – it's a routing profile issue, not an issue for BRouter-web and should therefore be discussed in the profile's repository: https://github.com/poutnikl/Brouter-profiles

**Comment by EssBee59** [comment]
Hello Thany,

I had a look at your question:
If you try to force the route on the footway defined on the side of the highway, you will get a gig surprise:
(by using this link as example)
 
http://brouter.de/brouter-web/#map=18/33.27905/131.50339/standard&lonlats=131.500482,33.279566;131.501809,33.279207;131.502641,33.279072;131.503783,33.279207;131.505015,33.279348;131.506906,33.279319&profile=hiking-beta

Not only the  the underpass at the road crossing near the end is not defined in the OSM map:
3 further parts of the footway are not in OSM, smaking it unpossible to use this footway for your tour!!!

If the footway is usable, you should consider the corresponding changes in OSM!

I do not see any issue (or  weekness) in the Brouter-engine or in the hiking-profile.
Regards
**EssBee**

**Comment by EssBee59** [comment]
![Japan_OSM](https://user-images.githubusercontent.com/50321352/160545905-0db0d94e-36fb-4b43-8710-5f34a669233a.JPG)
This screenshot shows one of the footway part:
On the left side you can see a OSM warning (sorry it is in german!), it says "footway is near from a road, BUT NOT CONNECTED!)
The first tool-box invites you to connect!

**Comment by thany** [comment]
I see. I guess I can do that. This might help for other routing apps as well, presumably. Thanks for looking into it.

Just to be clear: those disconnected paths cannot be interpreted as "cross the road and carry on on the other side", can they? They have to be connected with a path, tagged as a zebra crossing, or whatever else it is?

**Comment by EssBee59** [comment]
"not connected" is for me the same as "dead end"...
Some meters are missing in the OSM map, making a routing unpossible:
To allow a routing, both footways on the screenshot above (the res marked and the one on the left) must be connected, as example with a point on the road in the middle.
(no idea why it was not mapped so: mapping error or real issue as a barrier /a wall, crossing is vorbidden by law for pedestrian..)
