### ISSUE TITLE
Ways with different `surface` tag variants counted twice in track statistics

### ISSUE THREAD

**Issue by stesie** [nrenner/brouter-web#494]
With #460 brouter-web now supports ways with a `cycleway:surface` tag. However, if a way has both a `surface` and a `cycleway:surface` tag (and brouter is invoked with `processUnusedTags` so both are returned), ... then brouter-web counts this way twice in the track statistics:

<img width="262" alt="Screenshot of track statistics w/ ~150m way type and ~310m surface type" src="https://user-images.githubusercontent.com/113068/167133728-8c3ff960-da8d-4dd4-98ad-08d5c14ce543.png">

Example: https://bikerouter.de/#map=19/49.79318/9.94119/osm-mapnik-german_style&lonlats=9.940186,49.793385;9.942198,49.792959

**Comment by mjaschen** [comment]
That's on me I guess ;-)

I'll fix it ASAP.

**Comment by stesie** [comment]
If you've got a brouter backend with `footway:surface` in `lookups.dat` it could even be three to choose from :-)

Prefering any specialized variant should likely be fine unless `processUnusedTags` is set. Then it's up to the profile if it's considering it (since it's a cycling profile) or not. With `processUnusedTags` set however it'll yield wrong statistics with non-bike profiles.

Personally I'd lean towards prefering any specialized variant (and falling back to plain e.g. `surface`) in favour of little complexity and accept wrongs stats for car profiles... (yet, as a cyclist, I might be biased :joy:)

**Comment by mjaschen** [comment]
I think we can safely assume that the majority of BRouter-web users utilize it to plan cycling routes ;-)

So I'm with you and think it's ok to prefer the specialized `*:surface` variants over `surface` when both are present.

**Comment by mjaschen** [comment]
FYI, I've implemented a fix.

I'll wait with the pull request until the branches for #68 are merged.

**Comment by nrenner** [comment]
Could you please make a PR now, planning a release in the coming week.

**Comment by nrenner** [comment]
Fixed in #550
