### ISSUE TITLE
OSM data not updated in BRouter

### ISSUE THREAD

**Issue by mendberg** [nrenner/brouter-web#495]
BRouter seems not to be updating OSM data. 

https://www.openstreetmap.org/way/224629857 
was updated with changeset 
https://www.openstreetmap.org/changeset/120349737#map=17/50.12810/8.51578
nine days ago when surface=concrete and  smoothness=intermediate was added. In BRouter it's still unknown/unknown:
https://brouter.de/brouter-web/#map=16/50.1277/8.5124/standard&lonlats=8.512902,50.130806;8.51876,50.125331&profile=vm-forum-velomobil-schnell

**Comment by mjaschen** [comment]
It seems the data files were last updated on 2022-04-21, see the timestamps here: http://brouter.de/brouter/segments4/

Maybe @abrensch can take a look.

Meanwhile you can use alternative BRouter-web instances with more recent routing data. For example, at https://bikerouter.de/ the routing data is updated from OpenStreetMap every 6 hours.

Your example route shows the correct data in the analysis tab there: https://bikerouter.de/#map=16/50.1277/8.5124/standard&lonlats=8.512902,50.130806;8.515112,50.12875;8.51876,50.125331&profile=vm-forum-velomobil-schnell (but only if a via point is set)

**Comment by mendberg** [comment]
If only bikerouter.de's velomobile profile wasn't **that** outdated… which makes it useless for me.

**Comment by mjaschen** [comment]
Oh, I had no idea. Will update the profile tomorrow!

**Comment by mendberg** [comment]
TIA. 👍 It's missing some features and pre–sets like "no_steps". (Maybe the recumbent profile is outdated, too. I don't use that a lot.)

**Comment by mjaschen** [comment]
(Profiles updated @ [bikerouter.de](https://bikerouter.de/))

**Comment by mjaschen** [comment]
(@nrenner I think this issue can be closed as the routing data is created on a daily basis again)
