### ISSUE TITLE
Different incline in elevation chart, but same route

### ISSUE THREAD

**Issue by cannothing** [nrenner/brouter-web#496]
Reproducing the behavior:

Use this route: https://brouter.m11n.de/#map=13/47.4726/9.7931/osm-mapnik-german_style&lonlats=9.741783,47.494937;9.781094,47.464773;9.836865,47.466971;13.044205,47.797755&profile=Trekking-MTB-strong
Have a look at the elevation chart at km 10 the dark red segment. It is telling it is a segment of 3,3 km with the incline of 7-9 %.

Cut of the last routing point Salzburg. Now i get a elevation chart, wich tells me, that summed up I have  segments of 2,1 km with an incline of 10-15.

I think this is a difference, that would change decisions.

**Comment by nrenner** [comment]
The grouping of the incline segments is done in an external library, can you please open an issue there: 
[alexcojocaru/geo-data-exchange](https://github.com/alexcojocaru/geo-data-exchange/).
