### ISSUE TITLE
Improving the Brouter gpx export.

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#499]
[Locus 3.50.1 Navigation Commands & Icons_2p.pdf](https://github.com/nrenner/brouter-web/files/9548796/Locus.3.50.1.Navigation.Commands.Icons_2p.pdf)

The current BRouter gpx export does not fully reflect the planner quality.

What bothers me most ?
You need to add a separate preset for each individual app.
The waypoint list is polluted by many Locus turn waypoints.
Multiple turn wpt pollute the map view by imports in other apps.

Expected:

A compact neat waypoint list with **only desired** waypoints.
A track with ALL data **discreetly** present in the trackpoints.
The existing apps are not badly affected by the extra data.

**Comment by nrenner** [comment]
Is this the same or a related request as in this Groups entry?
[Gpx export by Brouter web. (OSM Android bikerouting group)](https://groups.google.com/g/osm-android-bikerouting/c/rOObP6si_rE/m/-68zBrb0BgAJ)

**Comment by 0709wiwiwi** [comment]
Correct zaterdag, 14 mei 2022, 00:09p.m. +02:00 van Norbert Renner  ***@***.*** :

**Comment by nrenner** [comment]
From a quick glance I'm not sure I understand what kind of export the linked file is and what the use case is.

I will only take time to look into this after the upcoming release, maybe someone else can help figuring this out?

**Comment by 0709wiwiwi** [comment]
Hello EssBee59.

Question I am often asked.  
There is no existing gpx navigation standard, or is it there ?

Answer: 
That is absolutely correct, and there probably never will be such one. 
The gpx standard only provides the necessary tools to produce something nice with it.
Just like you go into a craft shop and buy a hammer and chisel and a piece of marble.
An artist will probably carve a nice sculpture out of it, another will smash the marble.

The gpx [EN]sym.

The gpx [EN] sym is so here nicely used to add the basic turn instructions and also to generate the turnsymbols.
The English standard text or [EN]text as such is very important as even other tags are edited in any local language..

The idea of using the gpx [EN] sym for turns is a idea copy from Garmin tcx course files where the [EN]PointType is used for the same purpose.

Therefore by Garmin excist a very limited text list by the Garmin tcx course standard with the correct text expression to be used into the [EN]PointType.
In tcx courses the [EN] PointType text by this standard is used to generate you the (in app translated) basic turn instruction and the turn Icon generation. 

Compare the PointType in a tcx course file and notice this is very similar with the well known gpx sym usage. 

In the Locus app this mode by gpx is available and nicely operational since years ago already now. 
In other words this is a tcx clone by gpx files but without the limitations by the Garmin tcx standard.
Locus had a turn text list available so I just had to use the same ones, no need to reinvent any new ones.

The Locus sym text where shown and available in Github in the past, but I do not find them anymore in Github.
Anyway I copied all of them and have put them in a nice readable document list with all supported turn instructions by the Locus [EN]sym text.
Have a look at the serial number in this list and you will notice this is the same as the figure for turns in the Locus extension by navigation waypoints.
Find the turnlist here: https://www.dropbox.com/s/cmgzoqp2c3ctpad/Locus%203.50.1%20Navigation%20Commands%20%26%20Icons_2p.doc?dl=0

This idea by [EN]sym has so been started already about 10 years ago. 
The method to navigate by gpx in Locus is however still a little bit unknown.

Had this been suggested by Garmin such was of course immediately been accepted universally even when the standard sym text was in any [XX] language. 

The idea and the later implementations have than had some evolution, this step by step, into the currently here proposed tested and most simple method.
I do use and test this already for a longer period and I can't imagine to use it in any other more simple robust way than by the instructions in the trackpoints.

The mode by trackpoints is super simple to understand, is super discrete and even is friendly for older apps, is very robust, and delivers you an immediate TRUE real tracknavigation at import in the navigation app, but thereby still by the also integrated Shaping and Via Planner Points allows you the comfort and the flexibility to fastly replan any design even allows to redesing smaller segment parts so quite fast and easily.

Your Question:
What app do use such a generated trackfile ? Answer: Locus app at import.
What router engine does generate such a trackfile: The RouteYou web planner.

As the Brouter web planner is nice and fast and easy to operate it should be very welcome to have an export gpx file in that same easy discrete trackfile format anyway. 

Find some descriptive of historic development steps in the attached pdf.
Item: True track navigation.

Best Regards,
Willy.

Better move to Github Brouter ? Sure ? 
[True Track Navigation.pdf](https://github.com/nrenner/brouter-web/files/8764987/True.Track.Navigation.pdf)

**Comment by EssBee59** [comment]
Hello @0709wiwiwi,

Thank for the clarification!
The Brouter allready supports currently 5 versions for the turn instructions...

But your comment above about "polluation" is not correct:
Brouter-web users have the choice for a version (default is "turninstructionmode=autochoose = no turn instruction!)
Only a problem remains when the GPX is intended for many friends using different navi.apps... 

Anyway:
Yes, I prefered to have only one standard version... but have no idea which version can/will get "standard" or at leat "industry standard".

Yes, please move the request (including the clarification above) to the Brouter for further discussion.
Regards

**Comment by nrenner** [comment]
> Better move to Github Brouter ? Sure ?

No, not sure yet.

We're about to switch to client-side formatting, where it might be easier to add additional format options and features.

**Comment by 0709wiwiwi** [comment]
Quote: Yes, I prefered to have only one standard version... but have no idea which version can/will get "standard" or at leat "industry standard".

Indeed @ EssBee59 but we should have no illusions, only the big Garmin could force this. If the popular apps already use a corresponding method, this would certainly be welcome. In my opinion, this can only be encouraged if there is also a usable gpx file offer from popular route planners such as BRouter. So someone will have to take the reins. Otherwise it will remain a dream.

Plug and Play gpx file directly navigation ready upon import into the app.
Regarding the BRouter Locus export the advantage is that there is a ready made gpx export but directly usable Via points are missing.
The advantage of this proposal is that this gpx track file contains everything that is needed and it is also very discreet and not disturbing.

I have of course also tried the other app mentioned osmand. I still find it a very complex app. I notice in forums recurring remarks about wrong turn instructions. This does not encourage to start working with osmand. I took a closer look at one message: https://github.com/osmandapp/OsmAnd/issues/14331
This file contains a trk(track) and a (rte) route. With the (rte) route, the osmand app should then calculate itself independently. The (rtept) route point positions are away from road junctions.
And yet the generation of the turn instructions goes wrong. If you import this file into the much simpler Cruiser app (with osrm or Brouter engine) it does calculate correctly.

You may understand why I prefer a Locus compatible ready-made Brouter gpx output using instructions in track points. Do you still want to change and recalculate? It is possible because the Via points (Shaping) Planner points are also neatly and discretely present for you to work with them directly.
