### ISSUE TITLE
List intialcosts in CSV for debugging

### ISSUE THREAD

**Issue by torotil** [nrenner/brouter-web#5]
I'm playing around with a custom routing profile based on the fastbike preset. I've extended it with an additional cost for stop signs and traffic lights but I'm having difficulty with debugging it.

Is there any way I can see the initialcosts for nodes? They don't appear to show up anywhere in the CSV export.

**Comment by nrenner** [comment]
BRouter CSV export has now a ``NodeCost`` column, also available in the "Data" tab in the Web Client as ``node$``.
