### ISSUE TITLE
Trails Overlays problem?

### ISSUE THREAD

**Issue by fidelius-dc** [nrenner/brouter-web#500]
Hi, since 1 or 2 days the overlays for the waymarked cycling, hiking and MTB trails don't display anymore. Is a server down? Hope this gets fixed soon. In the meantime i'm stuck to CyclOSM baselayer.

**Comment by mjaschen** [comment]
It's an error @ waymarkedtrails.org. I guess we've to wait until someone there fixes it.

**Comment by nrenner** [comment]
See also [waymarked-trails-site#417 Trails showing problem](https://github.com/waymarkedtrails/waymarked-trails-site/issues/417)

**Comment by fidelius-dc** [comment]
thanks, let's hope they can fix their tileserver soon.

**Comment by fidelius-dc** [comment]
they solved it - waymarkedtrails are back
