### ISSUE TITLE
Searching by coordinates

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#52]
It could be great if the BRouter-web was able to search for the points not only by an address or place name, but also by the coordinates in usual formats.

It is very common during solving the routing issues, that users provide coordinates. I have used them indirectly,  searching in google maps, locating the place, and searching it in the BRouter-web. 

That is not very convenient..

**Comment by nrenner** [comment]
Search/Geocoding is currently provided by [Nominatim](https://nominatim.openstreetmap.org/) (via [Leaflet Control Geocoder](https://github.com/perliedman/leaflet-control-geocoder) plugin), which is also used on osm.org.

With a quick search I found the resolved issue "[Be generous in accepting coordinate formats](https://github.com/twain47/Nominatim/issues/147)" and from there the [current implementation](https://github.com/twain47/Nominatim/blob/1542a006cbb315812316e6788ad68f7f3010e557/lib/lib.php#L607-L683) for coordinate support and some [test cases](https://github.com/twain47/Nominatim/blob/702f9477aba67037e1233837a75eb68361004b99/tests-php/Nominatim/NominatimTest.php#L85-L113).

So it does support coordinate input in some formats/variations. For missing formats I would suggest to open an issue for Nominatim (although I might switch to some other service with autocompletion in the future). Or maybe someone knows a JavaScript coordinate parser?

**Comment by poutnikl** [comment]
I guess the provided links are sufficient.
