### ISSUE TITLE
Custom uploaded profiles in local BRouter-web instance

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#53]
I was successful in configuring BRouter-web to run locally in my Windows. I have added selection of my profiles to the config.js. so I can select them as if they were the standard ones.
See [Screenshot of profile selection](http://forum.locusmap.eu/index.php?topic=4613.msg45094#msg45094)

All works fine, if I use untouched standard profiles, or my profiles, now "standard" profiles as well.
But if I modify them in the text field and upload them back, so they get <custom>, the routing for such <custom> profiles never finishes, even if trivially short. 

The custom profile with random numeric name is created in the folder specified in BRouter java launch command. So does such custom profile is listed in the command line  in the BRouter console window.

What am I doing wrong ?

---

I run BRouter web as http://localhost:8000/brouter-web/
after running the batch below, placed in server.cmd in BRouter main folder:

---

@echo off

REM BRouter standalone server
REM java -cp brouter.jar btools.brouter.RouteServer <segmentdir> <profile-map> <customprofiledir> <port> <maxthreads>

REM maxRunningTime is the request timeout in seconds, set to 0 to disable timeout
set JAVA_OPTS=-Xmx1024M -Xms512M -Xmn8M -DmaxRunningTime=300
set CLASSPATH=./brouter.jar

start "BRouter server" java %JAVA_OPTS% -cp %CLASSPATH% btools.server.RouteServer .\segments4 .\profiles2 .\customprofiles 17777 1

start "Python file provider" s:\PFiles\Python27-32\python.exe -m SimpleHTTPServer

**Comment by nrenner** [comment]
Hm, I don't see anything obvious that could be wrong. I just tested with the latest BRouter release on Ubuntu and local upload should be working in general.

Are there any errors in the server or the Browser console (Ctrl-Shift-i)?
Is the profile saved to the customprofiles folder complete (when you open it in a text editor)?

**Comment by poutnikl** [comment]
Thanks for the reply.  I will check the profile completeness when I return home.
For now, what looks at least suspicious are the Brouter.jar parameters  
`.\segments4 .\profiles2 .\customprofiles`
While I would suppose   .(dot) should mean for all 32 parameters the current folder ( the BRouter home data folder in my case), it measn the current folder just for .\segments4 and  .\profiles2.
On contrary,  dot in  .\customprofiles does not mean current folder, but currentfolder\profiles2.

Is possible, that BRouter and BRouter-web did not negotiate well, where the custom profiles are stored ?

**Comment by nrenner** [comment]
You are right, just checked the code, the customprofiles parameter is relative to the profiles folder. Not sure if that is a problem, but you could try ``..\customprofiles`` instead.

The client does not really *need* to know where the customprofiles folder is. The path setting in config.js is only optional for displaying the currently selected profile and this is independent from loading and processing a profile on the server.

**Comment by poutnikl** [comment]
So, the custom profiles are complete.
I have prviously used for customeprofiles folder just dot as well, what causes profiles landing at profiles2 folder, but without any effect.
Errors seems near none, but this one>
SyntaxError: JSON.parse: bad escaped character at line 8 column 28 of the JSON data
L.BRouter<._handleRouteResponse()
brouter-web.js:36
o.Util.bind/<()
brouter-web.js:1
brouter-web.js:36:1605

the debugger points to line
L.BRouter=L.Class.extend({statics:{URL_TEMPLATE:BR.conf.host+"/brouter?lonlats={lonlats}&nogos={nogos}&profile={profile}&alternativeidx={alternativeidx}&format={format}",URL_PROFILE_UPLOAD:BR.conf.host+"/brouter/profile",PRECISION:6,NUMBER_SEPARATOR:",",GROUP_SEPARATOR:"|",ABORTED_ERROR:"aborted"},options:{},format:"geojson",initialize:function(t){L.setOptions(this,t),this.queue=async.queue(L.bind(function(t,e){this.getRoute(t.segment,e)},this),1),this.queue.kill=function(){var t=this.tasks;this.drain=null,this.tasks=[],t.forEach(function(t){t.callback(L.BRouter.ABORTED_ERROR)})}},setOptions:function(t){L.setOptions(this,t)},getUrlParams:function(t,e){return{lonlats:this._getLonLatsString(t),nogos:this._getNogosString(this.options.nogos),profile:this.options.profile,alternativeidx:this.options.alternative,format:e||this.format}},parseUrlParams:function(t){var e={};return t.lonlats&&(e.lonlats=this._parseLonLats(t.lonlats)),t.nogos&&(e.nogos=this._parseNogos(t.nogos)),t.alternativeidx&&(e.alternative=t.alternativeidx),t.profile&&(e.profile=t.profile),e},getUrl:function(t,e){var o=this.getUrlParams(t,e),r=L.Util.template(L.BRouter.URL_TEMPLATE,o);return r},getRoute:function(t,e){var o=this.getUrl(t),r=new XMLHttpRequest;return o?(r.open("GET",o,!0),r.onload=L.bind(this._handleRouteResponse,this,r,e),r.onerror=L.bind(function(t,e){e(BR.Util.getError(t))},this,r,e),void r.send()):e(new Error("Error getting route URL"))},_handleRouteResponse:function(t,e){var o,r;return 200===t.status&&t.responseText&&"application/vnd.geo+json"===t.getResponseHeader("Content-Type").split(";")[0]?(r=JSON.parse(t.responseText),o=L.geoJson(r).getLayers()[0],e(null,o)):void e(BR.Util.getError(t))},getRouteSegment:function(t,e,o){this.queue.push({segment:[t,e]},o)},uploadProfile:function(t,e,o){var r=L.BRouter.URL_PROFILE_UPLOAD;xhr=new XMLHttpRequest,t&&(r+="/"+t),xhr.open("POST",r,!0),xhr.onload=L.bind(this._handleProfileResponse,this,xhr,o),xhr.onerror=function(){var t=this;o("Upload error: "+t.statusText)},xhr.send(e)},_handleProfileResponse:function(t,e){var o;200===t.status&&t.responseText&&t.responseText.length>0?(o=JSON.parse(t.responseText),e(o.error,o.profileid)):e("Profile error: no or empty response from server")},_getLonLatsString:function(t){for(var e="",o=0;o<t.length;o++)e+=this._formatLatLng(t[o]),o<t.length-1&&(e+=L.BRouter.GROUP_SEPARATOR);return e},_parseLonLats:function(t){var e,o,r=[];if(!t)return r;e=t.split(L.BRouter.GROUP_SEPARATOR);for(var n=0;n<e.length;n++)o=e[n].split(L.BRouter.NUMBER_SEPARATOR),r.push(L.latLng(o[1],o[0]));return r},_getNogosString:function(t){for(var e,o="",r=0;r<t.length;r++)e=t[r],o+=this._formatLatLng(e.getLatLng()),o+=L.BRouter.NUMBER_SEPARATOR,o+=Math.round(e.getRadius()),r<t.length-1&&(o+=L.BRouter.GROUP_SEPARATOR);return o},_parseNogos:function(t){var e,o,r=[];if(!t)return r;e=t.split(L.BRouter.GROUP_SEPARATOR);for(var n=0;n<e.length;n++)o=e[n].split(L.BRouter.NUMBER_SEPARATOR),r.push(L.circle([o[1],o[0]],o[2],L.Draw.Circle.prototype.options.shapeOptions));return r},_formatLatLng:function(t){var e="";return e+=L.Util.formatNum(t.lng,L.BRouter.PRECISION),e+=L.BRouter.NUMBER_SEPARATOR,e+=L.Util.formatNum(t.lat,L.BRouter.PRECISION)}}),L.bRouter=function(t){return new L.BRouter(t)};

**Comment by nrenner** [comment]
The error looks like the client can't read the server response, maybe some encoding issue?

Could you post the response, please: With Ctrl-Shift-i go to the Network tab, provoke the error, right click on the last (?) line and select "Copy Answer".

**Comment by poutnikl** [comment]
It looks strange, as it triggers 2 network responses with response code 200 = OK
First is POST profile, the second is GET
***
POST:
{
  "profileid": "custom_1474519161334"
}
***
GET:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "creator": "BRouter-1.1",
        "name": "brouter_.\customprofiles\1474519161334_0",
        "track-length": "1483",
        "filtered ascend": "37",
        "plain-ascend": "37",
        "cost": "2338",
        "messages": [
          ["Longitude", "Latitude", "Elevation", "Distance", "CostPerKm", "ElevCost", "TurnCost", "NodeCost", "InitialCost", "WayTags", "NodeTags"],
          ["17135558", "49385374", "250", "1483", "1450", "0", "187", "0", "0", "highway=tertiary", ""]
        ]
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [17.136931, 49.406331, 213.25],
          [17.137000, 49.406225, 213.25],
          [17.137581, 49.405213, 214.75],
          [17.137712, 49.405002, 214.75],
          [17.137974, 49.404528, 214.25],
          [17.138107, 49.404195, 214.0],
          [17.138377, 49.403549, 215.25],
          [17.138434, 49.403409, 215.5],
          [17.138439, 49.403344, 215.75],
          [17.138438, 49.403255, 216.25],
          [17.138365, 49.403057, 217.5],
          [17.137781, 49.402330, 223.75],
          [17.138152, 49.402177, 222.5],
          [17.138896, 49.401907, 221.25],
          [17.139200, 49.401774, 221.25],
          [17.139655, 49.401520, 222.25],
          [17.140272, 49.401025, 224.25],
          [17.140569, 49.400842, 224.5],
          [17.141148, 49.400538, 224.25],
          [17.140967, 49.400234, 224.75],
          [17.140955, 49.400066, 225.0],
          [17.140952, 49.399325, 227.75],
          [17.141261, 49.398673, 232.0],
          [17.141325, 49.398573, 232.5],
          [17.141911, 49.397664, 234.25],
          [17.142212, 49.397178, 234.0],
          [17.142091, 49.397006, 234.75],
          [17.141648, 49.396218, 237.5],
          [17.141334, 49.395658, 239.5],
          [17.140884, 49.394856, 250.75]
        ]
      }
    }
  ]
}

**Comment by poutnikl** [comment]
Note that the same stalling behaviour ( but debug responses not tested ) occured with Firefox (45.0.2) in Safe mode with disabled addons, to test if NoScript , uBlock origin or Requst policy addons interfere.

Can it matter that I relolaced to batch placement and default folder to the main folder ?

**Comment by nrenner** [comment]
Thanks, now I can track it down to the following line:

``"name": "brouter_.\customprofiles\1474519161334_0",``

The single backslash '\' is invalid in the (Geo)JSON response. Removing the directory part from the name doesn't work on Windows - and thus custom profiles won't work, haven't noticed before.

Needs to be fixed on the server side.

**Comment by poutnikl** [comment]
I got it as server side = localhost:17777 brouter.jar server, being on Arndt's court side......

**Comment by nrenner** [comment]
Yes, the brouter.jar and abrensch/brouter repository, but I'm going to take care of this. Just was implying that I will create a separate issue/pull request, probably after the current short brouter-web release I'm working on.

**Comment by poutnikl** [comment]
Temporary workaround is creation of dedicated test profile in the profiles2 and add its name to the config.js file of brouter-web. Modification need The page reload or a new page instance is needed if modified.

**Comment by nrenner** [comment]
I submitted a [pull request](https://github.com/abrensch/brouter/pull/69) for BRouter, meanwhile you could try using this:
[brouter.jar.zip](https://github.com/nrenner/brouter-web/files/534447/brouter.jar.zip)

**Comment by poutnikl** [comment]
Thanks, it works now.
