### ISSUE TITLE
button for reversing the direction of the track

### ISSUE THREAD

**Issue by bosdla** [nrenner/brouter-web#54]
Hi!
One feature I am missing quite a lot is, reversing the track.
if you have the following points: Start - A-B-C-D-Finish, clicking the "new" button should trigger the generation of a track: Finish-D-C-B-A-Start

Is is possible to implement?
Thanks Bosdla

**Comment by poutnikl** [comment]
+1  - I think the route reversal would be very useful feature.

**Comment by bosdla** [comment]
in my point of view best option to implement would be to add a second link on top of permalink: reverselink or something similar

**Comment by nrenner** [comment]
Agree this would be useful, but seems not to be supported yet by the underlying [Leaflet.Routing](https://github.com/Turistforeningen/leaflet-routing) plugin. And as I'm thinking about switching to [Leaflet Routing Machine](http://www.liedman.net/leaflet-routing-machine/), I would want to evaluate that first.
