### ISSUE TITLE
BRouter (web) U-turn command missing.

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#548]
Current: BRouter (web) does not generate U-turns.

Desired: Brouter (web) generates U-turns.

Generating U-turns (180° track returns) is very valuable. By generating U-turns you can avoid unclear or false turn indications.
Especially when navigating with "display off" and with TTS audio indication mainly, U-turns can prevent very serious wrong turn instructions. How the confusion can arise without those U-turns can be found in the link to the google BRouter discussion group.

As I can't post a zipped file in this github gps forum with the necessary gpx examples. ?  Strange....
So pse have a further look for all the details here:
https://groups.google.com/g/osm-android-bikerouting/c/-ljF8nqbFZc/m/4CjP2PQ7AAAJ

**Comment by polyscias** [comment]
This looks to me more like a [brouter issue](https://github.com/abrensch/brouter/issues) then a brouter-web issue, so it might be good to move this issue there.

**Comment by 0709wiwiwi** [comment]
And how do I most optimally move this issue than toward the https://github.com/abrensch/brouter/issues
To say how to remove it from here (can it be deleted ?) or maybe just leave it here too ? No ? Advise pse ?

**Comment by polyscias** [comment]
The brouter issue is https://github.com/abrensch/brouter/issues/436

To keep the discussion on one place I think it is better to close this one.

**Comment by bagage** [comment]
Thanks @polyscias for creating the issue!
