### ISSUE TITLE
turnInstructionCatchingRange

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#554]
turnInstructionCatchingRange.

The intention may be noble, but the result brings mostly more problems than benefits.
As the default value of 40, which is far too large, leads to mostly strange bad results.
A default value of 8 is sure more optimal, or even the complete removal of the rule.

The problem has already been demonstrated with confusingly bad results.
https://groups.google.com/g/osm-android-bikerouting/c/1zl5NSLR0y8

The next test with the file indicated in the link gave another strange result.
https://github.com/nrenner/brouter-web/issues/375#issuecomment-787744237
This is a test with the gpx file Freiburg - Titisee.
We are only going to use the initial part here.

Demo using the Android Kurviger (Cruiser) app. 

Kurviger allows to freely choose tracks or routes for display or calculation.
(_The BRouter web import unfortunately misses this simple choice_)
The Kurviger app compactly shows the yellow dot locations with the turnpoints.
(_In BRouter web you are working blind, you don't know where the turnpoints are_).
The Kurviger app shows both the planner's waypoint list and the turnpoint list.
(_In BRouter web you work blind, only after export (too late) you have a control_)

The Kurviger import sequence can be followed in the gif file.

- _The previously chosen routing engine is by the offline BRouter app_. 
- _Routing profile (bicycle) with turninstructionsCatchingRange = 8_.

![Kurviger gpx trk and rte import](https://user-images.githubusercontent.com/54167201/172320317-856740e8-2f63-40cb-8afc-8fdfc57f7fe1.gif)

- So we first select and import the desired gpx trk_rte file.
- We select (trk)track as visual template, and (rte)route to calculate.
- We notice route points as Via Points > we convert them to Shaping Points.
- The yellow dots are the Turn Points, the underlying white circles Shaping Points.
- The critical Shaping Points positioned at road junctions are so better removed.
- See the Turnpoints calculated by the Brouter engine with turninstructionCatchingRange = 8.
- Then see what happens with a turninstructionCatchingRange = 40.
- And finally a result through the Cruiser app and the online OSRM router.
  (Kurviger motor (GH) profiles do not route into the Freiburg inner city)  ;-)
- Notice the OSRM engine does not generate that continue instruction ;-)

Translated with www.DeepL.com/Translator (free version)

**Comment by nrenner** [comment]
This repository is about the web frontend / user interface only. Please open this issue in the backend repository "[abrensch/brouter](https://github.com/abrensch/brouter)" where the engine and app code and profiles are maintained.

Generally (see also brouter-web "About"):
- server / backend, routing engine, Android app, profiles, brouter.de site:  
  https://github.com/abrensch/brouter/issues
- web client / frontend:  
  https://github.com/nrenner/brouter-web/issues

You can also see this when searching:
https://github.com/abrensch/brouter/search?q=turnInstructionCatchingRange
