### ISSUE TITLE
Any way to disable beeline feature?

### ISSUE THREAD

**Issue by thof** [nrenner/brouter-web#557]
Is there any easy way to disable beeline feature similarly to `draw` function (https://github.com/nrenner/leaflet-routing/blob/dev/src/L.Routing.js#L786)? I know there is a `toggleBeelineDrawing` function but even if it's disabled it still responds to a click event on an existing segment (https://github.com/nrenner/leaflet-routing/blob/dev/src/L.Routing.Edit.js#L360) which is undesirable from my perspective. Actually the line 366 from the mentioned function is what I'd like to modify as it always set `beeline` to true:
```
prev._routing.beeline = !prev._routing.beeline;
```

I believe it would be more correct if the "Toggle straight line" button turned off the beeline feature completely including clicking on a segment. It should also depend on the drawing mode if it's active or not. I tried to modify the code as described but failed unfortunately.

Background: I'm maintaining my fork of brouter-web adding Google Street View integration and this beeline feature really interferes with it.

**Comment by nrenner** [comment]
`draw` only refers to appending new segments, not editing.

You should be able to disable editing like this (haven't tried): 
[routing](https://github.com/nrenner/brouter-web/blob/f92d2e222794dc3ef3f689ce9e57cb8099bf678a/js/index.js#L299).[_edit](https://github.com/nrenner/leaflet-routing/blob/773314a37940b32b2fec84886611ecbd4d6f3df9/src/L.Routing.js#L122-L123).[disable()](https://github.com/nrenner/leaflet-routing/blob/773314a37940b32b2fec84886611ecbd4d6f3df9/src/L.Routing.Edit.js#L68)

**Comment by thof** [comment]
This is perfect, exactly what I needed. Here is the patch https://github.com/thof/brouter-web/commit/2aede019ad0f6dc6ee32fe342efdc4411d9df893 in case anyone has a similar request.
Thanks for your prompt help, I appreciate it.
