### ISSUE TITLE
Route drawing stops working by random

### ISSUE THREAD

**Issue by hgdrn** [nrenner/brouter-web#561]
I've been having watching a weird problem for a few weeks. I cannot say when it has started exactly, but I guess it was three or four weeks ago when it started.

Regardless if I'm using Firefox or any Chrome/Chromium browser (Vivaldi, Brave, Edge, ...,, regardless if I'm using Win10 or Linux: when drawing a new route brouter-web stops working by random, and it continues to work again by random or if I'm deleting the last way point or if switch to another window and back to the browser. brouter-web isn't calculating anything in this time (no high load), it's just in a mode where it doesn't accept another click for a new way point and doesn't draw the dashed line from the last way point to the cursor position.

I recorded a short video to demonstrate it: [https://www.youtube.com/watch?v=Ect6JnqJagg](https://www.youtube.com/watch?v=Ect6JnqJagg)

- I'm using Marcus' installation at https://bikerouter.de/
- I click on the URL bar to reload the page
- I set a start point
- I add a way point
- brouter-web stopped working, no dashed line visible anymore, no clicks getting accepted
- after 20 seconds the dashed line is visible for a short time (I don't know why) and gets invisble again
- I switched to another window and back again, then brouter-web continued working

What I've examined so far:

- it's not an OS problem
- it's not a browser problem (all browsers, see above)
- it's not a plugin problem (tested it in a private window without any plugins)
- it's not a location problem (tested it on several start locations in Germany)
- it's not a bikerouter.de problem, the problem occurs on brouter.de/brouter-web, too
- it's not a profile problem, it doesn't make a difference if i'm using "Rennrad" or "Trekking Rad" on Marcus' installation
- one can force brouter-web to work again by deleting the last way point or by simply switching tasks ("Alt Tab")
- the browser Dev Tools show absolutely nothing (is there a verbose option one can set to enable debugging? sorry if FAQ)

**Comment by nrenner** [comment]
Thanks for the detailed report and testing!

We don't have a verbose option or similar for debugging.

I haven't noticed that yet, but I also see this issue after clicking around for a while.

I suspect this is caused by some specific event order or race condition when drawing is disabled on marker or line hover after the click and missing a mousout for enabling again. There have been a couple of changes to route drawing because of the straight line feature. I will have to investigate.

**Comment by nrenner** [comment]
Can also be reproduced by just moving the cursor accross the route line multiple times in draw mode until drawing is disabled (gets enabled again with next hover).

Should be fixed in the repo now.
