### ISSUE TITLE
style.css modifications are not tracked by gulp watch

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#57]
When modifying the `style.css` file, I have to run `gulp` manually to get it properly generated even if `gulp watch` is running.
I can see in `gulpfile.js` various mentions to `styles` folder but it is commented: should it be working?

**Comment by nrenner** [comment]
Sorry, somehow the notification for this issue got lost.

Watching CSS hasn't been implemented yet. I have been running ``gulp styles`` manually, and when tweaking CSS I sometimes edit directly in Chrome and copy over when done.
