### ISSUE TITLE
'Unhewn_cobblestone' surface shown as 'unknown' in track analysis

### ISSUE THREAD

**Issue by r2r2r2o** [nrenner/brouter-web#572]
It appears that track analysis recognizes unhewn_cobblestone surface as 'unknown'. I do not know if that also applies to other infrequently used surface types.

![image](https://user-images.githubusercontent.com/24614373/176479667-d15be1ab-9c75-4710-8d76-b721d8d9c296.png)
![image](https://user-images.githubusercontent.com/24614373/176480469-db261485-6a27-4751-b9aa-421e5704ecda.png)
![image](https://user-images.githubusercontent.com/24614373/176480929-0d2efc05-7f8f-4f4b-abb7-895f131c914b.png)

**Comment by stesie** [comment]
That's more an issue with brouter, which doesn't have a mapping in https://brouter.de/brouter/profiles2/lookups.dat ;-)

**Comment by afischerdev** [comment]
Yes, there already is an issue for that #270 and an update discusstion ##416

**Comment by nrenner** [comment]
> Yes, there already is an issue for that #270 and an update discusstion #416

Links should probably be abrensch/brouter#270 and abrensch/brouter#416.
