### ISSUE TITLE
Adding Default Vector Layer and/or Overlay via config.js

### ISSUE THREAD

**Issue by mjaschen** [nrenner/brouter-web#573]
As far as I interpret that correctly, adding default layers/overlays via `BR.conf.overlays` in `config.js` is only possible for tile server URLs at the moment, e.g.

```javascript
    BR.conf.overlays = {
        'Orienteering': 'https://tiler4.oobrien.com/oterrain_global/{z}/{x}/{y}.png',
        'Smoothness': 'https://{s}.tile.bbbike.org/osm/bbbike-smoothness/{z}/{x}/{y}.png',
    }
```

As BRouter Web also supports vector maps as of version 0.18 it'd be desirable to add vector maps to the default lists too (e.g. by referencing a `style.json`).

A more general approach would be the possibility to enable any of the configured layers/overlays from `tree.js` in the default layers/overlays list `BR.conf.baseLayers` or `BR.conf.overlays` (maybe by referencing them by their ID/name).

**Comment by nrenner** [comment]
Yes, the layer configuration in `config.js` is still separate from the layer tree configs in the `layers` directory and only supports XYZ layers without additional options (#51). 

What I also haven't looked at yet is adding vector tiles as custom layer, but that might be pretty straightforward in [_addLayer](https://github.com/nrenner/brouter-web/blob/f68d32b1f2b5ea34202c2bd62d7a91770942b7f0/js/control/Layers.js#L119-L125)?

I'm not sure what the way to go is, but I was thinking about deprecating the layer part in `config.js`, as the custom layers UI is basically a replacement for that. Maybe adding a JSON export/import there so you can share and backup the layers added in the UI or configure as file and import.

For customizing the `layers` tree and referencing own layer definitions with options, there could be a way to override the settings in the `layers/conf` folder, probably as a separate config file. E.g. for overriding the `BR.confLayers.defaultBaseLayers` and `BR.confLayers.defaultOverlays` defined in the layers [config.js](https://github.com/nrenner/brouter-web/blob/master/layers/config/config.js).

**Comment by mjaschen** [comment]
> What I also haven't looked at yet is adding vector tiles as custom layer, but that might be pretty straightforward in [_addLayer](https://github.com/nrenner/brouter-web/blob/f68d32b1f2b5ea34202c2bd62d7a91770942b7f0/js/control/Layers.js#L119-L125)?

Adding such a layer was as simple as putting the layer config (`layer-name.geojson`) and the style (`layer-name-style.json`) into `layers/mvt` and adding an entry `layer-name` in `tree.js` at the desired position. Works perfectly - but is of course only feasible when running an own instance (but editing config.js also requires control over the instance, so not really problem in this scenario).

Adding support for user-providable vector layers via “Custom Layers” would be another feature I guess.

> For customizing the layers tree and referencing own layer definitions with options, there could be a way to override the settings in the layers/conf folder

That's the hint I needed – with `BR.confLayers.defaultOverlays` in [config.js](https://github.com/nrenner/brouter-web/blob/master/layers/config/config.js#L17) it's easily possible to promote an overlay to the default list (if already configured via `layers/mvt/*`).

Import/Export would be fine, at least for experienced users. But most people doesn't even know what a powerful variety of maps and overlays is hidden behind that little “More” button. People regularly look at me in amazement when I demonstrate them the overpass overlays. I think here is room for improving UI/UX. But also in a separate ticket ;-)

As far as I'm concerned, this issue can be closed. Thank you very much for pointing me in the right direction.
