### ISSUE TITLE
Ascend calculation

### ISSUE THREAD

**Issue by EssBee59** [nrenner/brouter-web#578]
Hello,

It seems, the calculation of the "Ascend" depends on the number of used route points:

First I created a route using 2 route points:

.. /#map=9/49.5609/8.7849/osm-mapnik-german_style&lonlats=8.695385,50.049443;8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike

Then, using the "load track as route" I "reload" the same route with many many route points:

#map=9/49.5252/8.5487/osm-mapnik-german_style&lonlats=8.695385,50.049443;8.696078,50.015579;8.681951,50.002069;8.678888,49.986579;8.659381,49.980925;8.657799,49.979908;8.657829,49.976709;8.654738,49.97645;8.653396,49.966356;8.654837,49.963701;8.654396,49.961745;8.652741,49.961558;8.648838,49.931183;8.641456,49.932475;8.63842,49.928717;8.636968,49.915613;8.625179,49.914626;8.594934,49.906937;8.596957,49.904674;8.598296,49.898634;8.592832,49.898308;8.587181,49.884648;8.587544,49.880483;8.565109,49.879961;8.565378,49.870567;8.555909,49.869326;8.556609,49.864173;8.5551,49.863914;8.554079,49.861235;8.563509,49.830234;8.579481,49.828252;8.589711,49.809926;8.598318,49.801335;8.603307,49.784238;8.623759,49.768397;8.619367,49.755134;8.610746,49.754043;8.608928,49.730673;8.608106,49.731826;8.61173,49.727008;8.613702,49.720747;8.613083,49.717722;8.617599,49.710756;8.61909,49.703464;8.621884,49.70024;8.621736,49.683183;8.619691,49.682607;8.619138,49.677508;8.622508,49.677924;8.626312,49.669239;8.633818,49.661696;8.639895,49.645774;8.638918,49.642212;8.641929,49.635378;8.641447,49.626666;8.648747,49.619997;8.654523,49.611438;8.654651,49.606127;8.651617,49.605591;8.649241,49.596211;8.650442,49.593911;8.649312,49.590623;8.653702,49.582025;8.647076,49.581356;8.647555,49.57614;8.645547,49.576159;8.649503,49.565431;8.644568,49.558343;8.644557,49.556232;8.637377,49.550218;8.63953,49.548764;8.629897,49.546988;8.630903,49.540508;8.621098,49.540354;8.618014,49.527835;8.607652,49.514731;8.601387,49.50273;8.602121,49.499338;8.606584,49.498898;8.608024,49.484571;8.611243,49.484055;8.605428,49.478123;8.60646,49.474282;8.602942,49.473829;8.598333,49.468899;8.607567,49.457456;8.609184,49.450727;8.614268,49.44674;8.603894,49.440069;8.599238,49.425917;8.594122,49.418093;8.594863,49.416052;8.592568,49.410343;8.592194,49.402601;8.598112,49.395283;8.598276,49.386807;8.583131,49.365566;8.583201,49.362154;8.573564,49.337168;8.560242,49.329746;8.554198,49.321757;8.558045,49.317993;8.553959,49.313378;8.562199,49.307412;8.563242,49.304147;8.565147,49.303933;8.569249,49.298638;8.565089,49.29517;8.567619,49.293152;8.560034,49.286254;8.566728,49.285347;8.566429,49.284437;8.533414,49.233241;8.52665,49.220116;8.524666,49.219118;8.515132,49.204171;8.511133,49.202347;8.509686,49.195041;8.496385,49.172822;8.482837,49.158473;8.483883,49.157808;8.482361,49.156878;8.484945,49.153389;8.483568,49.151411;8.483982,49.148585;8.474963,49.136626;8.47661,49.131633;8.474209,49.124839;8.476871,49.120773;8.472669,49.104757;8.41102,49.022734;8.416843,49.018664;8.412667,49.016921;8.411957,49.013721;8.410333,49.013786;8.408311,49.011082;8.41003,49.009664;8.41016,49.006106;8.403457,49.005644;8.402423,48.999287;8.399005,48.998345;8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike

And high differences appear in the calculated ascends!
A minor problem, but some times I like to compare the ascends of existing tracks, and this is currently not occurate.
(Probably the filtering on ascend should be applied on the full route, not on each intermediate route)

**Comment by nrenner** [comment]
Not a client issue, see [brouter#447 (comment)](https://github.com/abrensch/brouter/issues/447#issuecomment-1181542775):

**Comment by quaelnix** [comment]
It becomes a client problem if the client composes the total ascent from the ascents of individual segments of the total route - as brouter-web does. Because then the state of the elevation buffer is lost at the via points.
