### ISSUE TITLE
Add IGN layer

### ISSUE THREAD

**Issue by RemiF1908** [nrenner/brouter-web#579]
Hello, in France, the IGN (national institute of geography) provide a good layer of France : https://geoservices.ign.fr/services-web-experts-ortho

It is better than Esri, if you can add it, it could be verry nice.

Rémi.

**Comment by nrenner** [comment]
Did you close this on purpose?

**Comment by RemiF1908** [comment]
Yeah, sorry, I didn't see that this layer was already on brouter. It's my ba :/
