### ISSUE TITLE
Download links in Firefox open file instead of downloading

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#6]
http://forum.openstreetmap.org/viewtopic.php?pid=434055#p434055

**Comment by riyazpanarwala** [comment]
Same issue happens for me.
i am using quantum firefox. download attribute works only on same origin.

**Comment by nrenner** [comment]
This issue has been solved by adding a [Content-Disposition: attachment ](http://stackoverflow.com/questions/1012437/uses-of-content-disposition-in-an-http-response-header) HTTP header in the server response.

Still works for me with current Firefox 58.0.2 on Ubuntu. Is your question related to brouter.de or local installation or what is your use case?

**Comment by riyazpanarwala** [comment]
i am using firefox quantum 59.0b5.

**Comment by nrenner** [comment]
Also works on Firefox Nightly 60.0a1.
Just to make sure: are we talking about http://brouter.de/brouter-web/?

**Comment by riyazpanarwala** [comment]
Yeah your code is working perfectly fine. 
I just wanted to confirm that Mozilla has not solved that issue.  Right ??

**Comment by nrenner** [comment]
Yes, the same-origin restriction still exists.
