### ISSUE TITLE
Cannot use localization with Chrome50+ in http mode

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#60]
Cf [this](https://www.mapsmarker.com/faqs/geolocaton-https-only/). We might instead disable the button on such browers then? Reported in #59.

![screen shot 2016-12-22 at 09 06 20](https://cloud.githubusercontent.com/assets/24696260/21420494/fdb3dd5e-c825-11e6-9f1d-cd1922c727e4.png)

**Comment by davidmartinezros** [comment]
Hi @bagage!

I have the same problem.

And I don't want to pay for a https domain.

Any clue for using navigation.localization? Can I use any other service that don't need https mode?

**Comment by bagage** [comment]
@davidmartinezros I really don't know - I don't think proper workarounds exist, but you can acquire HTTPS certificate for free now using [letsencrypt](https://letsencrypt.org/). 

By the way @nrenner do you think it could be added on brouter.de website?

**Comment by nrenner** [comment]
> We might instead disable the button on such browers then?

Yes, already thought it might make sense to either disable or hide the geolocation button, maybe with an explaining tooltip (on mobile?) message. Or at least have a more user-friendly error message. Ideally implemented by the [Locate plugin](https://github.com/domoritz/leaflet-locatecontrol) with a cusomizable tooltip/message?

Not sure if there is a proper way to detect this limitation though, the [Google article](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only#can_i_detect_at_runtime_if_the_geolocation_was_blocked_because_of_not_being_on_a_secure_context) only suggests parsing the error message (which might differ across browsers).

> [...] but you can acquire HTTPS certificate for free now using letsencrypt.
> By the way @nrenner do you think it could be added on brouter.de website?

@abrensch?

**Comment by bagage** [comment]
@abrensch Do you think you can set it up for brouter.de? Ideally redirecting all traffic from http to https would be even better. Configuring https with letsencrypt is quite easy, if you need assistance on it I can help.

**Comment by nrenner** [comment]
The locate control is now only added in a secure context, as this is now required by most Browsers (row "Secure context required"):
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Browser_compatibility
