### ISSUE TITLE
Barriers and dimensions

### ISSUE THREAD

**Issue by axelos** [nrenner/brouter-web#603]
# preamble

Add the existence of barriers on bicycle facilities and consider dimensional data. This includes these two types of barriers:

### barrier=bollard

"Solid pillar or pillars made of concrete, metal, plastic, etc., and used to control traffic. Bollards may be used to block vehicular traffic completely while allowing passage of pedestrians and bicycles, or to prevent criminals using vehicles from ramming shops."

### barrier=cycle_barrier

"Cycle barriers (or pedestrian chicanes) are fence-like barriers positioned along paths, footways, cycleways or tracks which serve to either slow cycle access or prevent it entirely depending on spacing and layout. Often made of steel, and laid out in a staggered chicane layout. The intent may also be to discourage motor vehicle access to the protected way: motorcycles and mopeds specifically. 
Perhaps counterintuitively, cycle barriers are sometimes intended to permit access by cyclists to cycle routes while denying access to other vehicles. However, not all cycles are able to pass through them."

On these barriers, the passage dimensions are measured:

**maxwidth:physical=*** for the maximum passage width
**spacing=*** for the distance between the grids,
**opening=*** for the (smallest) opening or passage width of the grid elements,
**overlap=*** for the overlap of adjacent grid elements.

# interest

The interest is to add a menu on the interface allowing the user to indicate the dimensions of his bike. With this Brouteur calculates according to the dimensions indicated via the previous values which barriers are passable and impassable.

### Sources

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier

**Comment by nrenner** [comment]
Those width tags are currently not in the backend routing data ([lookups.dat](https://github.com/abrensch/brouter/blob/master/misc/profiles2/lookups.dat)), nor would the engine consider bike dimensions (to my knowledge). The frontend interface would automatically generate corresponding input fields in the profile options tab once there are such parameter descriptions in the profile.

So please open this issue in the backend:
https://github.com/abrensch/brouter
