### ISSUE TITLE
Remove permalink, regenerate URL instead

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#62]
Instead of having a "permalink" somewhere on the website, it would be better if the URL is regenerated automatically on change: for instance using [Leaflet hash](https://github.com/mlevans/leaflet-hash) or one that is still maintained. 

This would be a great improvement and is part of why I don't like about #56 new-version.

**Comment by nrenner** [comment]
Yes, switching to leaflet-hash (or whatever) is one of the tasks with higher priority, as most maps use a hash URL nowadays and people are used to that.

**Comment by nrenner** [comment]
Recently stumbled upon [leaflet-fullHash](https://github.com/KoGor/leaflet-fullHash) that also supports active layers (current [Permalink](https://github.com/shramov/leaflet-plugins/blob/master/control/Permalink.js) control adds the active base layer only).

Ideally existing links and bookmarks would still work.

**Comment by bagage** [comment]
Fixed via #74.
