### ISSUE TITLE
Translations: make website localizable (i18n)

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#63]
Currently the website is only in English. Would be great if it was localized, for instance by using [Leaflet.i18n](https://github.com/yohanboniface/Leaflet.i18n) or [gulp-html-i18n](https://www.npmjs.com/package/gulp-html-i18n).

**Comment by nrenner** [comment]
A lot of [OSM-related projects](https://wiki.openstreetmap.org/wiki/Translation#Editors_and_other_contributing_tools) use [Transifex](http://transifex.com/) for translation, which seems to be free for Open Source projects. There is also an [OpenStreetMap group](https://www.transifex.com/openstreetmap/public/), but mostly with editing-related projects.

**Comment by nrenner** [comment]
- [[OSM-dev] Reminder: OpenStreetMap Organisation on transifex](https://lists.openstreetmap.org/pipermail/dev/2017-June/029920.html)
- [Replace update_locales with Transifex client usage by simon04 · Pull Request #408 · tyrasd/overpass-turbo](https://github.com/tyrasd/overpass-turbo/pull/408/files)

**Comment by bagage** [comment]
OK so I've quickly looked around and in my opinion:

* either we go for the overpass approach, copy/pasting their code. Pros: should be quick and easy. Cons: not standard at all.
* othewise, I propose to drop bower+gulp in favor of npm+webpack, and use [webpack-i18n](https://github.com/webpack-contrib/i18n-webpack-plugin) for instance. Pros: (hopefully) simplify build system and remove deprecated gulp/bower couple. Cons: will take more time for sure. I've no experience with webpack but I guess it's a good occasion to learn :).

What do you think @nrenner or anybody else?

**Comment by nrenner** [comment]
There are two parts to this:
1. synchronizing translation files with Transifex
2. the actual translation lookup function

Both need to work together and agree on the translation file layout and structure.

I only noted the overpass-turbo PR as a current example of a [Transifex CLI Client](https://docs.transifex.com/client/introduction) integration. But there are other examples using Transifex, see "at Transifex" links on the [Translation wiki page](https://wiki.openstreetmap.org/wiki/Translation) or the [Transifex OpenstreetMap group](https://www.transifex.com/openstreetmap/public/). Don't know what they use or if Transifex is offering or recommending a JS library for the 2. part.

I'm all for using standard libraries, but don't know if webpack-i18n really is what people use, there seems to be little documentation, so i wonder:
- will it work with Transifex formats?
- how about replacing text in HTML (I only see a JS "__" function)?

**Comment by nrenner** [comment]
As webpack-i18n is translating at build-time it can't support variables and [plurals](https://docs.transifex.com/formats/json#section-plurals-support). We probably don't need that, just something to be aware of.

Other libs I found:
https://github.com/globalizejs/globalize
https://github.com/i18next/i18next
https://github.com/airbnb/polyglot.js

**Comment by nrenner** [comment]
We now have a project on Tranisfex and a common team with Vespucci and others:
https://www.transifex.com/openstreetmap/brouter-web/

**Comment by bagage** [comment]
It looks like something like [i18next](https://github.com/i18next/i18next) + [loc-i18next](https://github.com/mthh/loc-i18next) could do the trick. But I'm facing issues with modules/requires yet - not sure how we should handle that. Still learning things there :).

**Comment by nrenner** [comment]
> But I'm facing issues with modules/requires yet - not sure how we should handle that.

There should be a global variable `i18next`, see [JSFiddle](https://jsfiddle.net/jamuhl/dvk0e8a9/#tabs=js,result,html) linked from [Getting started](https://www.i18next.com/overview/getting-started), so we can ignore modules/requires?
