### ISSUE TITLE
Profile: better display name

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#64]
Currently profile are displayed by their id which is suboptimal. 
It would be great to have a proper name (eg `shortest` -> `Shortest` at least), and maybe also a description of it that we could display once #56 is merged?

**Comment by bagage** [comment]
@nrenner I've committed https://github.com/bagage/brouter-web/commit/5915849f8024f4e5b195f626ebf1b3e5ef8aa02a (live on demo server). Having a small (4/5 words) for each profile is thus possible -- one drawback is that it changes `BR.config.profiles` (that was an array previously and now an object).
Thus if you think I should do a PR, this migration issue has to be addressed first.

**Comment by nrenner** [comment]
Don't know how a later translation solution (#63) would work in this case exactly, but I suppose the currently used filename could serve as a key to lookup the translated profile name from a language file. Therefore changing the config structure to add profile names, only to later change it back again when in separate files, is not ideal.

An intermediate workaround could be to programmatically replace hyphens with spaces and to capitalize the first letter when building the select options.

> and maybe also a description of it that we could display

From my point of view that already exists in the form of a comment in the loaded profile source text.

**Comment by bagage** [comment]
Was fixed with i18n implementation :).
