### ISSUE TITLE
Nutzung des Statshunters Browser-Plugin seit 2022-24 nur noch eingeschränkt möglich

### ISSUE THREAD

**Issue by j3n53r** [nrenner/brouter-web#640]
Das Statshunter Browser-Plugin (getestet in firefox und brave)  ermöglicht das dynamische Einblenden von eigenen Explore-Tiles sowie gefahrenen Routen als Ebene in im Browser, unter anderem bei brouter/bikerouter, Strava, RWGPS und Komoot.

https://statshunters.com/
https://addons.mozilla.org/de/firefox/addon/statshunters/
https://chrome.google.com/webstore/detail/statshunters/ldhkneiheabejbefhgjddpamijajabmm

Mindestens seit Version 2022-24 gibt es im Bikerouter das Problem, dass die eingeblendeten Tiles einige Optionen bei der Routen-Planung zerschießen, sofern die Kacheln eingefärbt (also bereits eingesammelt) sind. Die anderen Planungsseiten sind nicht von diesem geänderten Verhalten betroffen.

Punkt-für-Punkt-Planung ist nach wie vor problemlos möglich, Zwischenpunkte setzen nur noch im sehr kleinen Radius um bereits bestehende Punkte. Drag&Drop des Tracks ist ebenfalls nicht mehr möglich, da der Cursor nicht mehr am Track "haftet".

Ausblenden der Tiles reaktiviert die normale Funktionsweise von brouter.

Vermutlich eine Frage der Ebenen-Reihenfolge.

Vor dem benannten Update funktionierte die Kombination statshunters + bikerouter traumhaft.

Anhängend ein Beispielbild für "nicht haftenden Cursor"
![brouter_kein_punkt_in_tile_möglich](https://user-images.githubusercontent.com/113439707/189897157-f0c246b6-c03b-46b7-bd19-9f5610d67124.png)

**Comment by mjaschen** [comment]
(a) prüf bitte mal, ob es nur nur <https://bikerouter.de> betrifft und nicht andere Instanzen von BRouter-Web, z. B. <http://brouter.de/brouter-web/> → falls ja, ist das hier nicht der richtige Ort für die Fehlermeldung
(b) die Vermutung mit der Ebenenreihenfolge teile ich; ein von den Symptomen her gleiches Problem hatte die Squadrats-Extension, das wurde aber innerhalb von Minuten gefixt → frag doch mal bitte direkt bei Stan von Statshunters nach, ob er die Reihenfolge anpassen kann

**Comment by j3n53r** [comment]
1.0.8 des Plugins ist online für firefox und in prüfung für chrome und co.

Problem behoben. Issue kann zu.
