### ISSUE TITLE
Allow walking/pushing bike on public_transport=platform?

### ISSUE THREAD

**Issue by hungerburg** [nrenner/brouter-web#669]
Even though this is not the main goal, Brouter is best of breed for hiking, that is, pedestrian. So I was a bit surprised, that it does shy from public_transport=platform.

Indeed public_transport=platform is a badly specified tag. From the description it is not clear, that it should be even traversable. Yet, it often gets used to map something, that routers can use just like a footway. Sadly, it is also very often creating islands, trapping routers. Still, if there was a way around those problems, it should be worthwhile for a pedestrian router to search them.

Here link to a constructed example - https://brouter.de/brouter-web/#map=17/47.28118/11.25191/osm-mapnik-german_style,route-quality&lonlats=11.251105,47.280831;11.249563,47.281081&profile=hiking-mountain - But people start hikes from there, so the detour is a bit annoying.

**Comment by nrenner** [comment]
This will be added with [brouter#458 (comment)](https://github.com/abrensch/brouter/pull/458#issuecomment-1299779561), so closing here.
