### ISSUE TITLE
latest commit (23.1.2017) breaks it for me

### ISSUE THREAD

**Issue by abrensch** [nrenner/brouter-web#67]
naked html startup without any active contents, bot firefox + chrome

all o.k. with commit 1e26cb1027e6144db34669a3621dc15a43c67360 (12.12.2016)

**Comment by nrenner** [comment]
This commit removes the `dist` folder - with the concatenated and minified build targets that the `index.html` uses - from the source repository. 

So now you need to build these files locally (requires those installed, see [Build section in readme](https://github.com/nrenner/brouter-web#build)):
* make sure using current dependencies by running `npm install` and `bower install`
* run the build with `gulp`
