### ISSUE TITLE
Leaflet 1.0: Touch style in desktop browsers

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#69]
Since Leaflet 1.0, larger controls (e.g. zoom buttons) for touch screens are set in Chrome but not in Firefox, on the same desktop machine without a touch screen.

This is because the `leaflet-touch` class is set on [Map.js](https://github.com/Leaflet/Leaflet/blob/059a722b5be57a6f591a2ab69494021be992af34/src/map/Map.js#L1017) init depending on [`L.Browser.touch`](https://github.com/Leaflet/Leaflet/blob/703ae02aa8cbd0b87be5b01e77754b83ad732267/src/core/Browser.js#L97), which is now `true` in all desktop browsers supporting Pointer Events ([currently](http://caniuse.com/#feat=pointer) Chrome, IE, Edge and Opera).

This has changed from v0.7 to v1.0 when `maxTouchPoints` was removed from the `L.Browser.pointer` test in Leaflet/Leaflet#3839, which is part of the `touch` test. So the `touch` flag has now a different meaning:
* "true for all browsers on touch devices." - [0.7.x](http://leafletjs.com/reference.html#browser-touch)
* "true for all browsers supporting touch events." - [1.0.0](http://leafletjs.com/reference-1.0.0.html#browser-touch)
* "true for all browsers supporting touch events. This does not necessarily mean that the browser is running in a computer with a touchscreen, it only means that the browser is capable of understanding touch events." - [1.0.3](http://leafletjs.com/reference-1.0.3.html#browser-touch) (clarification)

Issues like Leaflet/Leaflet#5266 and similar have been closed as working as expected, pointing to [You Can't Detect A Touchscreen](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/). Which is fair enough, and although I see the point, I find that article a bit opinionated, and it's also a bit old (05/2013).

So I would rather tend to revert to the previous touch style behavior in our application - accepting that it won't work for all cases - by adding a separate test in addition to the touch flag, using the removed `maxTouchPoints` and perhaps the `any-pointer` media query:

http://playground-leaflet.rhcloud.com/wocu/edit?html,output

Based on these sources:

`maxTouchPoints` - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints), [Can I use](http://caniuse.com/#feat=pointer) (part of Pointer Events)

- [Pointer Events - W3C Recommendation](https://www.w3.org/TR/pointerevents/#widl-Navigator-maxTouchPoints)
  > While a maxTouchPoints value of greater than 0 indicates the user's device is capable of supporting touch input, it does not necessarily mean the user will use touch input. Authors should be careful to also consider other input modalities that could be present on the system, such as mouse, pen, screen readers, etc.
- [IE10 User Agent String Update](https://blogs.msdn.microsoft.com/ie/2012/07/12/ie10-user-agent-string-update/)  
  > If you’re detecting touch support client-side, do not sniff the user agent string; use
  > navigator.msMaxTouchPoints instead. If the property exists and returns
  > a value greater than zero, the user’s PC has touch capability. For example:
  `var hasTouch = navigator.msMaxTouchPoints > 0; `

  but:
  > In Internet Explorer 10 on Windows 7, this property always returns a value of zero, regardless of the capabilities of the device.

  [msMaxTouchPoints/maxTouchPoints property (Internet Explorer)](https://msdn.microsoft.com/library/hh772144(v=vs.85).aspx)
- [Detecting touch: it's the 'why', not the 'how' - Mozilla Hacks](https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/) (04/2013)
    ```javascript
    if (('ontouchstart' in window) ||
        (navigator.maxTouchPoints > 0) ||
        (navigator.msMaxTouchPoints > 0)) {
        /* browser with either Touch Events of Pointer Events
            running on touch-capable device */
    }
    ```

`any-pointer` Media Query - [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-pointer), [Can I use](http://caniuse.com/#feat=css-media-interaction)

- [Interaction Media Features and their potential (for incorrect assumptions) - Dev.Opera](https://dev.opera.com/articles/media-features/) 
  > Use any-pointer or any-hover for lowest common denominator
    ```css
    @media (any-pointer:coarse) {
        /* at least one input is “coarse”
        make buttons and other “touch targets” bigger */
    }
    ```
- [Modernizr Pointer Media Query detect](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/mediaquery/pointermq.js)

**Comment by cyrilchapon** [comment]
Any status on this ? :)

**Comment by nrenner** [comment]
I've been waiting if there is any feedback on this and related issues. Also little progress with my development efforts in general, unfortunately.

The idea is still to override the touch style in the application like in the JS Bin, maybe generalized into a separate flag:

```js
    // revert touch style (large icons) when touch device/coarse pointer
    // querying is available and negative
    if (L.Browser.touch) {
      var removeTouchStyle = false;

      if ('maxTouchPoints' in navigator) {
        removeTouchStyle = navigator.maxTouchPoints === 0;
      } else if (window.matchMedia && window.matchMedia('(any-pointer:coarse),(any-pointer:fine),(any-pointer:none)').matches) {
        removeTouchStyle = !window.matchMedia("(any-pointer:coarse)").matches;
      } else if ('msMaxTouchPoints' in navigator) {
        removeTouchStyle = navigator.msMaxTouchPoints === 0;
      }

      if (removeTouchStyle) {
        L.DomUtil.removeClass(map.getContainer(), 'leaflet-touch');
      }
    }
```
http://playground-leaflet.rhcloud.com/wocu/edit?html,output

I'm a bit unsure about this, as I don't have different devices to test. Although results from running the JS Bin on [Microsoft Browser screenshots](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/?) turned out as expected.
