### ISSUE TITLE
highway surface "chipseal" is "Unknown" in Surface Category List

### ISSUE THREAD

**Issue by mcliquid** [nrenner/brouter-web#695]
It's extremely rare, but there are a few streets in my area that are actually chipseal.
The wiki describes the properties pretty well. OSM-Wiki: https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal
The main points in distinguishing it from normal asphalt:
- There is always a risk of loose gravel constituents, which can affect stone chips as well as skid resistance
- In summer at hot temperatures sticky tar spots can form due to tire rotations
- `smoothness` is mostly intermediate instead of good

Currently `surface=chipseal` is categorized in "Unknown", which I find a pity for the evaluation. Therefore, I would be happy if there was either a separate category for chipseal or to include this in "Paved".

Here is one example: https://bikerouter.de/#map=19/47.47594/9.66634/standard&lonlats=9.665203,47.476227;9.667355,47.475544

**Comment by polyscias** [comment]
See abrensch/brouter/pull/458, this is something for a lookups.dat update.

surface is one of the keys with the many different key values, see https://taginfo.openstreetmap.org/keys/surface#values and I do not think it is wise to add every different value.

I did create a script in the past to check unsupported values and their frequency:

```
----- surface
surface=artificial_turf -- 25400 unknown
surface=tartan -- 23119 unknown
surface=woodchips -- 6045 unknown
surface=trail -- 5880 unknown
surface=cement -- 3257 unknown
surface=acrylic -- 3034 unknown
surface=hard -- 2196 unknown
surface=chipseal -- 1880 unknown
surface=ice -- 1775 unknown
surface=metal_grid -- 1475 unknown
surface=interlock -- 1317 unknown
surface=granite -- 1037 unknown
surface=unpaved_minor -- 1022 unknown
```

I think it is fine to add paved as an alias to chipseal.

**Comment by polyscias** [comment]
Yes, the lookups.dat update is something for the backend and has nothing to do with this repo.
