### ISSUE TITLE
API Key Required for OpenCycleMap + Outdoors

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#70]
API Key Required for OpenCycleMap + Outdoors started to appear
as  map watermarks today on Brouter web.

I suppose it is a message for the Brouter web server, or the end user if running the web locally.
Does it mean there is possibly a countdown for the map services if the key is not managed in time ?

**Comment by poutnikl** [comment]
Perhaps asking the user for API Key, if available, storing it locally ( cookie? ) and provide it to the map server ?

**Comment by nrenner** [comment]
Fixed now, thanks for reporting.

Such API keys are meant per application, letting users register would be cheating.

But you can use your own key for the local installation. Update to [version 0.6.2](https://github.com/nrenner/brouter-web/releases/tag/0.6.2) by downloading the zip file. Then add the [thunderforest line](https://github.com/nrenner/brouter-web/blob/master/keys.js.template#L13) with your key to an existing `keys.js` file (and append a "," to the previous line) or create it from `keys.js.template`.

**Comment by poutnikl** [comment]
thanks a lot. In fact, I have already managed to get my own TF key, but have failed when I was trying to insert it to my local BRouter-web installation. That use I had primarily in mind.
