### ISSUE TITLE
Version 6.2 left/down WayDataTabel wrong

### ISSUE THREAD

**Issue by womisa** [nrenner/brouter-web#72]
The new version displays in Firefox 38.0.5  in the Data ScrollPane only 2 lines. Below the ScollPane a big area are empty (white).
The previous version  was ok.

**Comment by womisa** [comment]
![brclient](https://cloud.githubusercontent.com/assets/26434002/23988437/9029622c-0a2e-11e7-93db-f7158bccbe18.png)

**Comment by poutnikl** [comment]
I confirm that for Firefox ESR 45.8.0,
In contrary to web version 0.6.1, the list of data segment row is limited to just 2 scrollable data lines.
[Randomly chosen short route](http://brouter.de/brouter-web/#zoom=13&lat=49.3225&lon=15.5041&layer=OpenStreetMap&lonlats=15.498276,49.291993|15.504799,49.338994&nogos=&profile=trekking&alternativeidx=0&format=geojson)

**Comment by bagage** [comment]
@nrenner You can cherry-pick commit 2796b6f from my repository (branch feature/mobile_support_raw) that fix this issue:

```diff
diff --git a/js/control/TrackMessages.js b/js/control/TrackMessages.js
index 5167707..71d5904 100644
--- a/js/control/TrackMessages.js
+++ b/js/control/TrackMessages.js
@@ -68,9 +68,6 @@ BR.TrackMessages = L.Class.extend({
             paging: false,
             searching: false,
             info: false,
-            // flexbox workaround: without scrollY height Firefox extends to content height
-            // (^= minimum height with flexbox?)
-            scrollY: 50,
             scrollX: true,
             scrollCollapse: true,
             order: []
@@ -129,7 +126,7 @@ BR.TrackMessages = L.Class.extend({
     _getEmptyColumns: function(data) {
         var empty = new Array(data[0].length),
             i;
-    
+
         for (i = 0; i < empty.length; i++) {
             empty[i] = true;
         }
@@ -146,7 +143,7 @@ BR.TrackMessages = L.Class.extend({
     _getMessageLatLng: function(message) {
         var lon = message[0] / 1000000,
             lat = message[1] / 1000000;
-    
+
         return L.latLng(lat, lon);
     },
```

**Comment by nrenner** [comment]
Working on it. Thanks for reporting.

A newer DataTables patch version (1.10.13 instead of 1.10.5) got included, that sets `max-height` instead of `height` when `scrollCollapse` is set (since 1.10.8), which is bad in conjunction with the ` scrollY: 50` workaround.

@bagage Thanks for the hint, but it seems the workaround is still needed with the old layout. Will probably remove `scrollCollapse` since it doesn't do what I wanted anyway (adjust to actual rows height).
