### ISSUE TITLE
Integrate OpenMapSurfer

### ISSUE THREAD

**Issue by Ph1r3ph0x** [nrenner/brouter-web#73]
Maybe we can integrate OpenMapSurfer. It offers the best rendering I know of...
I attempted an integration here:
https://github.com/Ph1r3ph0x/brouter-web/commit/44c4075bbd84c6dc82aa2fa59d4237f041fec2d2
but wasn't able to test...

**Comment by nrenner** [comment]
The low zooms of OpenMapSurfer are indeed very nice. 

But the layer doesn't seem to be updated any more: "OSM-Data update: 09/05/2016". Therefore I guess I wouldn't want to integrate it.

To make your integration work, you would need to add it to the [baseLayers  list](https://github.com/nrenner/brouter-web/blob/master/js/Map.js#L67-L74) of the layer switcher and run the [build](https://github.com/nrenner/brouter-web#build).

In case you are running your own local [installation](https://github.com/nrenner/brouter-web#installation), additional layers can also be added in the [config.js](https://github.com/nrenner/brouter-web/blob/master/config.js#L70-L74) (no build necessary, just a page reload).

**Comment by bagage** [comment]
@nrenner I believe this issue can be closed since #77 allows users to add their own tiles services?

**Comment by joker234** [comment]
Since the OpenMapSurfer tiles are not available anymore you can close this issue. See also:
* https://github.com/leaflet-extras/leaflet-providers/pull/354#issuecomment-627505860
* https://ask.openrouteservice.org/t/mapsurfer-discontinued/1873

**Comment by bagage** [comment]
Thanks for the info @joker234 :)
