### ISSUE TITLE
fastbike-profile is routing over path with surface=ground, smoothness=impassable

### ISSUE THREAD

**Issue by vincentius63** [nrenner/brouter-web#756]
Given this route: http://brouter.de/brouter-web/#map=15/51.3734/7.0430/standard&lonlats=7.035675,51.375211;7.049965,51.371661&profile=fastbike

brouter-web routes over the way https://www.openstreetmap.org/way/35089605 with surface=ground, smoothness=impassable
Sure, it's a shortcut but it's no fun with a road bike and very steep.

The instance of Marcus Jaschen takes the right way, the long way:
https://bikerouter.de/#map=14/51.3667/7.0441/standard&lonlats=7.035241,51.375203;7.043631,51.374118&profile=fastbike-verylowtraffic

Expected behaviour would be to avoid such pathes (if possible as it here is). I didn't find real penalties for surface=ground and smoothness is only a dummy value in the fastbike-profile (in the fastbike-lowtraffic-profile too).

Thank you for your great work,
Vinzenz

**Comment by quaelnix** [comment]
The change in behavior has been caused by this pull request: https://github.com/abrensch/brouter/pull/579

See: https://github.com/abrensch/brouter/pull/579/files#diff-d8ddfd2207ce0e12ea5b2e06f5ae3e7df6747d5c369cc09944fe7ebd211d7d6fR264
