### ISSUE TITLE
train route - no through route

### ISSUE THREAD

**Issue by bramnz** [nrenner/brouter-web#760]
Hi all,

Is it possible to extend in brouter Europe’s only train-on-a-ferry route between Messina and Villa San Giovanni with a fictitious track so you can extend a train route between the mainland and Sicily ?

<img width="962" alt="Scherm­afbeelding 2023-07-26 om 15 57 16" src="https://github.com/nrenner/brouter-web/assets/140625784/55fab6a3-4396-456f-885a-8501f1054a9b">

**Comment by quaelnix** [comment]
Try this: [https://brouter.de/brouter-web/#map=13/38.1771/15.5978/...profile=rail](https://brouter.de/brouter-web/#map=13/38.1771/15.5978/standard&lonlats=15.554052,38.173964;15.563109,38.188091;15.562329,38.190083;15.561521,38.194684;15.561543,38.196699;15.561923,38.197325;15.566509,38.200997;15.568584,38.201792;15.627778,38.219913;15.628789,38.21993;15.629377,38.219708;15.630804,38.219008;15.632495,38.217219;15.633305,38.21625;15.645767,38.232975&straight=1,2,3,4,5,6,7,8,9,10,11,12&profile=rail)
![rail](https://github.com/nrenner/brouter-web/assets/122357328/be9701b1-bb20-472d-96e9-fa6037fb0f5b)
You can switch between normal and  bee-line mode by left-clicking on a track segment.
