### ISSUE TITLE
strange travel time result for hiking

### ISSUE THREAD

**Issue by pi3141** [nrenner/brouter-web#762]
Trip duration calculation give me unrealistic results for hiking profile. For [example](https://brouter.de/brouter-web/#map=16/42.9386/2.8776/OpenTopoMap&lonlats=2.879899,42.938957;2.865034,42.918532&profile=hiking-mountain), a 450 m climbing on a 3.5 km distance give me a trip duration of 1 hour and 6 minutes.
When I made the calculation with DAV standards, I have 450 / 300 + 3.5/4 × 1/2 = 1 hour and 56 minutes (which seems more realistic).
Is it possible to edit parameters for trip duration calculation ?

**Comment by quaelnix** [comment]
Komoot gives the following travel time estimates for this route:

| Fitness | Travel time |
| :---: | ---: |
| [Untrained](https://www.komoot.com/plan/tour/d01Ao8xzAAr8zA=EvgABMT2sMAA/@42.9275384,2.8752679,13.551z) | 1 hour and 56 minutes |
| [Average](https://www.komoot.com/plan/tour/d01Ao8xzAAr8zA=FPgABMT2sMAA/@42.9275384,2.8752679,13.551z) | 1 hour and 39 minutes |
| [In Good Shape](https://www.komoot.com/plan/tour/d01Ao8xzAAr8zA=FvgABMT2sMAA/@42.9275384,2.8752679,13.551z) | 1 hour and 23 minutes |
| [Athletic](https://www.komoot.com/plan/tour/d01Ao8xzAAr8zA=GPgABMT2sMAA/@42.9275384,2.8752679,13.551z) | 1 hour and 06 minutes |
| [Pro](https://www.komoot.com/plan/tour/d01Ao8xzAAr8zA=GvgABMT2sMAA/@42.9275384,2.8752679,13.551z) | 50 minutes |

> Is it possible to edit parameters for trip duration calculation ?

Not that I know of, but I agree that it would be nice if it were configurable.
