### ISSUE TITLE
BRouter.damsy.net - Segment data inconvenient positionning 

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#80]
I have noticed the DATA tab disappeared in the mobile web version.
I supposed it is intended to be accessible via link Segment data, ( eventually below the uploaded custom profile.). 

But the link seems inactive.  Neither the CSV download provides downloading of wanted CSV file.

I suppose it may be just not implemented yet, so the isue may hang around until done.

**Comment by bagage** [comment]
Wasn't aware of the issue because I personally do not use the DATA tab at all, so I only now roughly how it works. I'll fix this then, thanks.

**Comment by poutnikl** [comment]
It may not be that useful for end users, but is very valueable for profile developers.

**Comment by bagage** [comment]
@poutnikl Would you mind sharing a screenshot of what is missing actually? I cannot find the issue - for me data (the table) is still available below custom profile upload:
![image](https://cloud.githubusercontent.com/assets/1451988/25695265/b2daf0a6-30b2-11e7-929d-0d659b299341.png)
I believe you are talking about something else?

**Comment by poutnikl** [comment]
Huh, strange, I would bet I did create a route, but it seems I did not.
With the route created, it works and both segment data and CSV download are available.

I close it as non existent issue, I am sorry for the confusion. :-)

**Comment by poutnikl** [comment]
Having the data below the whole custom profile and having the horizontal slide bar below the whole segment data is somewhat inconvenient. I use it often even as an end user, to review quality of roads.

But I can live with that.

**Comment by bagage** [comment]
The goal is to have the best possible user experience for all users; I'll think about how to address these issues, so let's keep it open for now.

**Comment by poutnikl** [comment]
When a custom profile is used, 
but then the profile data are Cleared by button and standard Trekking profile is chosen, 
the long empty text field with now empty profile remains.

It should IMHO shrink to the previous standard size.

**Comment by bagage** [comment]
@poutnikl does current version (running on damsy.net) solve this problem? I think so but in case I missed something :).
