### ISSUE TITLE
Ghost roads in Map

### ISSUE THREAD

**Issue by kech61** [nrenner/brouter-web#815]
There are more and more ghost roads in the underlaying OSM-Map in web-client.
I had this issue with outdated OSM-Tools such as with the current version of OSMConvert bundeled with most LinuxDistris which cannot handle the new big Node/Waynumbers. Probably the variable-definitions run out off bounds.

Best regards an thanks a lot for your great work
Christian, openandromaps.org

https://brouter.de/brouter-web/#map=14/48.5213/15.4821/standard,Waymarked_Trails-Cycling

![2024-06-16 08_01_17-BRouter Web Client](https://github.com/nrenner/brouter-web/assets/6067611/34abe05c-b750-4887-afa6-4d2b42409426)

**Comment by nrenner** [comment]
These are remainders of yesterday's vandalism wave in caches of tile.openstreetmap.org, see:
- [UPDATE (13.06.2024): Wave of vandalism](https://community.openstreetmap.org/t/update-13-06-2024-neue-vandalismuswelle-strassen-kreuz-und-quer-teilweise-namen-geandert/113287)
- [The "OSM Standard tile layer" looks wrong (white lines, abusive comments etc.)](https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583/322)

I don't see those specific ones you posted, but that depends on the CDN cache and server we're assigned to. Just for my own interest, I would like to test if I can reproduce yours, so if you know how to get the HTTP headers for an example tile request from the dev tools network tab (F12), could you please post the `x-served-by` and `x-tilerender` response headers (don't mind if not)?

**Comment by kech61** [comment]
Hallo Norbert,

The remainders of Vandalism are already gone - sorry for my post here.
