### ISSUE TITLE
Routes fantômes 

### ISSUE THREAD

**Issue by tefgir** [nrenner/brouter-web#816]
Bonjour, 
Je constate ce matin en essayant de tracer un parcours l'existence de routes fantômes dont le nom est souvent en anglais ou cyrillique. 
Visible à grande échelle ici : 
https://brouter.damsy.net/latest/#map=6/43.755/10.942/cyclosm,route-quality&lonlats=7.332001,47.739323;8.129883,47.580231;8.381195,47.570833;8.585815,47.567126;8.614655,47.669904;9.062347,47.674528;9.183197,47.653251;9.472961,47.492927;9.663849,47.471679;9.379578,47.334615;9.129639,47.298762;9.073334,47.272672;8.973083,47.220918

Cordialement

**Comment by bagage** [comment]
Cf https://github.com/nrenner/brouter-web/issues/815
