### ISSUE TITLE
z-index issue on http://brouter.damsy.net

### ISSUE THREAD

**Issue by krisanselmo** [nrenner/brouter-web#84]
The CSS z-index value of the _dropdown-menu_ and _leaflet-top leaflet-left_ are the same (=1000) and it results this overlap:

![brouter web client - google chrome](https://cloud.githubusercontent.com/assets/1937089/25726594/32666540-3125-11e7-99b0-910c1529b538.jpg)

**Comment by bagage** [comment]
Yes, should be fixed on master via https://github.com/nrenner/brouter-web/commit/6e4794131f2a1aa2b91676872f6c1b601cc19814
Will update server tomorrow ;).

**Comment by bagage** [comment]
Updated & fixed, thanks!
