### ISSUE TITLE
brouter.damsy.net: Profile error: no or empty response from server

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#88]
When I launch brouter.damsy.net website and attempt to upload a custom profile, before doing anything else, I get ( repeatedly in few last days ) an error msg

         Profile error: no or empty response from server.

I remember it worked well for a version, 
that was not displaying the profile code for the standard Trekking profile.

**Comment by bagage** [comment]
Should be fixed now - it was an issue due to https transition (invalid nginx configuration). Thanks :).
