### ISSUE TITLE
Integration TileServer

### ISSUE THREAD

**Issue by womisa** [nrenner/brouter-web#93]
...from BRouter Forum.....

Hi @Nobert,

auf der Mapsforge Seite wurde ein neuer Tileserver für Taiwan gemeldet ("Tile Server for Taiwan")

==> https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md

==> https://github.com/virus-warnning/mapsforge-web

Dieser läßt sich relativ leicht auf eigene Bedürfnisse anpassen, so dass man die Openandromap Karten und Stylesheets nutzen kann!

Ich habe das mal testweise für Baden-Württemberg gemacht und in Deinem Webclient konfiguriert. Das funktioniert sehr gut.

Es gibt aber auchda teilweise Label-Renderprobleme an den Kachelgrenzen.

Wäre das nichts für eine (native?) Integration in den Webclient?

Man hätte dann eine reine Lokale Version mit MFG Maps...... und wäre unabhängig von Inet Tileserver.....

Viele Grüsse
Achim

Google translation:

Hi @Nobert,

On the Mapsforge page a new Tileserver was reported for Taiwan ("Tile Server for Taiwan")

==> https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md

==> https://github.com/virus-warnning/mapsforge-web

This can be easily adapted to your needs, so you can use the Openandromap cards and stylesheets!

I have the times testweise for Baden-Wuerttemberg and configured in your Webclient. This works very well.

But there are also partial label rendering problems at the tile boundaries.

Would not that be for a (native?) Integration into the Webclient?

One would then have a pure local version with MFG maps ...... and would be independent of Inet Tileserver .....

Many greetings
Achim

**Comment by nrenner** [comment]
Danke für die Info.

Der Demo nach scheint dieser Tileserver aber auch noch unausgereift zu sein (weiße Flecken, Gittermuster in Waldflächen).

Generell finde ich einfache Optionen für lokale Karten und eigene Stile schon interessant. Ein komplettes Offline-Paket für BRouter-Web auf dem Desktop halte ich aber für eine Nischenanforderung und mit der Kernentwicklung habe ich schon mehr als genug zu tun. Das wäre ein schönes Beispiel für ein separates Integrations-Projekt, das auch gut jemand anderes machen kann.

**Comment by womisa** [comment]
Hi Norbert,

das liegt beim Originalserver an den StyleSheets. Ich habe da auf die 
Openandromaps und dessen Stylesheets umgestrickt. Leider kenne ich mich 
mit Lefalet und JavaScript nur wenig aus.

Derzeit habe ich eine rein lokale HTM Datei mit dem Tileserver bzw. mit 
Deinem Webclient.

Die offiziellen Web-Tileserver haben immer mehr Beschränkungen. Deshalb 
bevorzuge ich eine reine lokale Lösung, ohne Webzugriff.

Viele Grüsse
Achim

Am 25.07.2017 um 18:42 schrieb Norbert Renner:

**Comment by nrenner** [comment]
> Leider kenne ich mich mit Lefalet und JavaScript nur wenig aus.

Ist eventuell auch nicht erforderlich, weil eine Integration vermutlich eher auf der Java Seite stattfinden müsste (Einbindung BRouter-Web per Browser/WebView in Java)?

> Wäre das nichts für eine (native?) Integration in den Webclient?

Wie stellst Du Dir das konkret vor? Mapsforge und BRouter Server sind in Java, das hat mit JavaScript im Browser erst mal nichts zu tun und lässt sich auch nicht direkt integrieren?

**Comment by womisa** [comment]
Hi

vielen Dank für Deine Antwort und Deinen WebClient.

Viele Grüsse
Achim


Am 26.07.2017 um 09:51 schrieb Norbert Renner:
>
>     Leider kenne ich mich mit Lefalet und JavaScript nur wenig aus.
>
> Ist eventuell auch nicht erforderlich, weil eine Integration 
> vermutlich eher auf der Java Seite stattfinden müsste (Einbindung 
> BRouter-Web per Browser/WebView in Java)?
>

...klar!
Ich habe eine reine Java Anwendung für meine Bedürfnisse 
zusammengestrickt mit Mapsforge/Openandromaps/Brouter/ und Graphhopper. 
Aber leider bisher nur auf meine Bedürfnisse (absolute Dateipfade etc.) 
zugeschnitten. Leider nicht konfigurierbar. Bei dieser 
JavaStandolone-Lösung ist keinerlei WEB-Server beteiligt.

Als Zwischenstep und als Zusatzlösung habe ich in Deinem Webclient den 
MobacServer konfiguriert und nutze die OAM Maps. Das funzt ganz gut.

Sinngemäß die gleiche Konfiguration bzw. Erweiterung in GpsMaster ==> 
http://wiki.openstreetmap.org/wiki/GpsMaster

Ich plane eben gerne meine Radtouren auf dem Desktop mit einem großen 
Bildschirm und werte da auch meine GpsTracks aus.

Ferner habe ich den
>
>     Wäre das nichts für eine (native?) Integration in den Webclient?
>
> Wie stellst Du Dir das konkret vor? Mapsforge und BRouter Server sind 
> in Java, das hat mit JavaScript im Browser erst mal nichts zu tun und 
> lässt sich auch nicht direkt integrieren?
>
...ich dachte Sinngemäß wie meine reine JavaVersion eben nur mit 
Applets, aber in dieser Richtung habe ich bisher nichts gemacht.

**Comment by nrenner** [comment]
Auf Applets würde ich nicht mehr setzen, die werden wohl [nicht mehr lange unterstützt](https://www.heise.de/developer/meldung/Oracle-veroeffentlicht-Details-zur-Abschaffung-der-Java-Applet-API-3303569.html).

Zum Rendering im Browser wären dann eher mal Vector Tiles interessant, siehe z.B. [OpenMapTiles](https://openmaptiles.org/).


Ich hätte da eher an ein ganz einfaches Java Programm zum Bündeln der Komponenten gedacht, das BRouter Server und Tileserver startet und BRouter-Web z.B. über [JavaFX WebView](https://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm) integriert, die Kommunikation der Komponenten wäre weiterhin über HTTP. Weiß aber nicht wie gut das mit dem WebView funktioniert.

Alternativ könnte man auch schauen, wie RouteConverter die Google Maps Integration macht, laut [diesem Post](https://forum.routeconverter.com/thread-1111-post-7863.html#pid7863) per "Eclipse SWT und DJNative Swing", der Quellcode dazu müsste im Package [browser-mapview](https://github.com/cpesch/RouteConverter/tree/master/browser-mapview/src/main) sein (Html/JavaScript unter resources).

----

*Sorry to non-German speakers, see [automatic translation](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=de&ie=UTF8&prev=_t&rurl=translate.google.de&sl=de&sp=nmt4&tl=en&u=https://github.com/nrenner/brouter-web/issues/93&usg=ALkJrhjO20htLxXgeMjOcG-7N4qR6NfO-A) for this issue.*

**Comment by womisa** [comment]
Am 04.08.2017 um 17:03 schrieb Norbert Renner:
>
> Auf Applets würde ich nicht mehr setzen, die werden wohl nicht mehr 
> lange unterstützt 
> <https://www.heise.de/developer/meldung/Oracle-veroeffentlicht-Details-zur-Abschaffung-der-Java-Applet-API-3303569.html>.
>
...Danke! Das war für mich neu. Ich habe aber nie was mit Applets gemacht.
>
> Zum Rendering im Browser wären dann eher mal Vector Tiles interessant, 
> siehe z.B. OpenMapTiles <https://openmaptiles.org/>.
>
> Ich hätte da eher an ein ganz einfaches Java Programm zum Bündeln der 
> Komponenten gedacht, das BRouter Server und Tileserver startet und 
> BRouter-Web z.B. über JavaFX WebView 
> <https://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm> 
> integriert, die Kommunikation der Komponenten wäre weiterhin über 
> HTTP. Weiß aber nicht wie gut das mit dem WebView funktioniert.
>
..das habe ich mir ja zusammen gebastelt. Reines Java Programm und als 
Basis die Mapsforge Library. Für BRouter und Graphhopper brauche ich 
keinen Server starten, da diese über Ihre Api-Schnittstelle eingebunden 
sind. Leider ist das Programm nicht so weit entwickelt, dass es für 
"Jedermann" anwendbar ist. Als Maps sind alle MFG kompatible darstellbar 
zB: OpenAndroMaps. Das ist aber eine reine lokale Version.

> Alternativ könnte man auch schauen, wie RouteConverter die Google Maps 
> Integration macht, laut diesem Post 
> <https://forum.routeconverter.com/thread-1111-post-7863.html#pid7863> 
> per "Eclipse SWT und DJNative Swing", der Quellcode dazu müsste im 
> Package browser-mapview 
> <https://github.com/cpesch/RouteConverter/tree/master/browser-mapview/src/main> 
> sein (Html/JavaScript unter resources).
>

...ok. Damals habe ich das dort iniziiert ==> 
https://forum.routeconverter.com/thread-1597.html

Ps: Anbei ein Snapshot: Grün ist der geladene Gpx Enztalradweg, Weiß Via 
Verbindung Routing Pforzeim-Holzgerlingen mit drei Alternativen 
(grün,blau,grau)

**Comment by nrenner** [comment]
>  Ich habe aber nie was mit Applets gemacht.

ich auch nicht viel und ich bin mir nicht sicher, ob das so einfach geht. Zudem würde ich zumindest in der Online-Variante keine Applets haben wollen.

Es gäbe auch noch die Alternative, Java nach JavaScript zu kompilieren (z.B. [VTM](https://github.com/mapsforge/vtm) per libgdx/GWT), aber auch da wäre ich erst mal skeptisch. Generell würde ich einen JavaScript-basierten WebGL Renderer mit Vector Tiles vorziehen.

Deshalb fände ich eine umgekehrte Integration zielführender und eben auch unabhängig umsetzbar, also statt Java in die Webanwendung, die Webanwendung in ein Java-Programm integrieren (auch im Hinblick darauf, dass ich mir eine solche hybride Kombination von BRouter, Mapsforge/VTM und BRouter-Web z.B. per [Android WebView](https://developer.android.com/guide/webapps/webview.html) oder [Cordova](https://cordova.apache.org/) als vollständige Android-App vorstellen könnte). Das hängt aber auch davon ab, was das Ziel einer solchen Integration sein soll?

> ..das habe ich mir ja zusammen gebastelt. Reines Java Programm [...]

Ich weiß, ich rede aber von einem hybriden Programm, das Java und Webanwendung kombiniert. Damit man BRouter-Web Offline/lokal nutzen kann, ohne mehrere Komponenten separat installieren, starten und stoppen zu müssen.

> Für BRouter und Graphhopper brauche ich keinen Server starten, da diese über Ihre Api-Schnittstelle eingebunden sind.

Zur Kopplung mit einer Web-Komponente (WebView) geht das aber nicht so einfach.

> Damals habe ich das dort iniziiert ==> https://forum.routeconverter.com/thread-1597.html

Da geht es nur um BRouter als Routing-Engine, ich meine aber dass RouteConverter Google Maps als webbasierte Kartenoberfläche integriert hat, als Analogie zu einer BRouter-Web Integration.
